
package com.ibm.mdm.esoa.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "MasterDataServiceException", targetNamespace = "http://client.esoa.mdm.ibm.com/")
public class MasterDataServiceException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private MasterDataServiceException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public MasterDataServiceException_Exception(String message, MasterDataServiceException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public MasterDataServiceException_Exception(String message, MasterDataServiceException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.ibm.mdm.esoa.client.MasterDataServiceException
     */
    public MasterDataServiceException getFaultInfo() {
        return faultInfo;
    }

}
