package com.ibm.wcm.ods.vo;
// Generated May 31, 2018 4:53:55 PM by Hibernate Tools 5.2.6.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClientProfilePsaSrc generated by hbm2java
 */
import com.ibm.gbs.util.Constant; 
//  @Entity
//  @Table(schema = Constant.SCHEMANAME_ODS , name = "CLIENT_PROFILE_PSA_SRC")
public class ClientProfilePsaSrc  {   // implements  java.io.Serializable {

	private BigDecimal clientProfilePsaSeqNum;
	private String clientId;
	private String sourceSystemId;
	private String isGamblingConcern;
	private Date processTs;
	private String activeToSdrc;
	private String rcCoordName;
	private String phoneNum;
	private String refIntakeOwner;
	private String assignedStaff;
	private Set<CpPsaContactSrc> cpPsaContactSrcs = new HashSet<CpPsaContactSrc>(0);
	private Set<CpPsaEncounterSrc> cpPsaEncounterSrcs = new HashSet<CpPsaEncounterSrc>(0);

	public ClientProfilePsaSrc() {
	}

	public ClientProfilePsaSrc(BigDecimal clientProfilePsaSeqNum, String clientId, String sourceSystemId) {
		this.clientProfilePsaSeqNum = clientProfilePsaSeqNum;
		this.clientId = clientId;
		this.sourceSystemId = sourceSystemId;
	}

	public ClientProfilePsaSrc(BigDecimal clientProfilePsaSeqNum, String clientId, String sourceSystemId,
			String isGamblingConcern, Date processTs, String activeToSdrc, String rcCoordName, String phoneNum,
			String refIntakeOwner, String assignedStaff, Set<CpPsaContactSrc> cpPsaContactSrcs,
			Set<CpPsaEncounterSrc> cpPsaEncounterSrcs) {
		this.clientProfilePsaSeqNum = clientProfilePsaSeqNum;
		this.clientId = clientId;
		this.sourceSystemId = sourceSystemId;
		this.isGamblingConcern = isGamblingConcern;
		this.processTs = processTs;
		this.activeToSdrc = activeToSdrc;
		this.rcCoordName = rcCoordName;
		this.phoneNum = phoneNum;
		this.refIntakeOwner = refIntakeOwner;
		this.assignedStaff = assignedStaff;
		this.cpPsaContactSrcs = cpPsaContactSrcs;
		this.cpPsaEncounterSrcs = cpPsaEncounterSrcs;
	}

	//  @Id

	//  @Column(name = "CLIENT_PROFILE_PSA_SEQ_NUM", unique = true, nullable = false, precision = 31, scale = 0)
	public BigDecimal getClientProfilePsaSeqNum() {
		return this.clientProfilePsaSeqNum;
	}

	public void setClientProfilePsaSeqNum(BigDecimal clientProfilePsaSeqNum) {
		this.clientProfilePsaSeqNum = clientProfilePsaSeqNum;
	}

	//  @Column(name = "CLIENT_ID", nullable = false, length = 60)
	public String getClientId() {
		return this.clientId;
	}

	public void setClientId(String clientId) {
		this.clientId = clientId;
	}

	//  @Column(name = "SOURCE_SYSTEM_ID", nullable = false, length = 40)
	public String getSourceSystemId() {
		return this.sourceSystemId;
	}

	public void setSourceSystemId(String sourceSystemId) {
		this.sourceSystemId = sourceSystemId;
	}

	//  @Column(name = "IS_GAMBLING_CONCERN", length = 3)
	public String getIsGamblingConcern() {
		return this.isGamblingConcern;
	}

	public void setIsGamblingConcern(String isGamblingConcern) {
		this.isGamblingConcern = isGamblingConcern;
	}

	//  @Temporal(TemporalType.TIMESTAMP)
	//  @Column(name = "PROCESS_TS", length = 26)
	public Date getProcessTs() {
		return this.processTs;
	}

	public void setProcessTs(Date processTs) {
		this.processTs = processTs;
	}

	//  @Column(name = "ACTIVE_TO_SDRC", length = 10)
	public String getActiveToSdrc() {
		return this.activeToSdrc;
	}

	public void setActiveToSdrc(String activeToSdrc) {
		this.activeToSdrc = activeToSdrc;
	}

	//  @Column(name = "RC_COORD_NAME", length = 100)
	public String getRcCoordName() {
		return this.rcCoordName;
	}

	public void setRcCoordName(String rcCoordName) {
		this.rcCoordName = rcCoordName;
	}

	//  @Column(name = "PHONE_NUM", length = 100)
	public String getPhoneNum() {
		return this.phoneNum;
	}

	public void setPhoneNum(String phoneNum) {
		this.phoneNum = phoneNum;
	}

	//  @Column(name = "REF_INTAKE_OWNER", length = 160)
	public String getRefIntakeOwner() {
		return this.refIntakeOwner;
	}

	public void setRefIntakeOwner(String refIntakeOwner) {
		this.refIntakeOwner = refIntakeOwner;
	}

	//  @Column(name = "ASSIGNED_STAFF", length = 160)
	public String getAssignedStaff() {
		return this.assignedStaff;
	}

	public void setAssignedStaff(String assignedStaff) {
		this.assignedStaff = assignedStaff;
	}

	//  @OneToMany(fetch = FetchType.LAZY, mappedBy = "clientProfilePsaSrc")
	public Set<CpPsaContactSrc> getCpPsaContactSrcs() {
		return this.cpPsaContactSrcs;
	}

	public void setCpPsaContactSrcs(Set<CpPsaContactSrc> cpPsaContactSrcs) {
		this.cpPsaContactSrcs = cpPsaContactSrcs;
	}

	//  @OneToMany(fetch = FetchType.LAZY, mappedBy = "clientProfilePsaSrc")
	public Set<CpPsaEncounterSrc> getCpPsaEncounterSrcs() {
		return this.cpPsaEncounterSrcs;
	}

	public void setCpPsaEncounterSrcs(Set<CpPsaEncounterSrc> cpPsaEncounterSrcs) {
		this.cpPsaEncounterSrcs = cpPsaEncounterSrcs;
	}

}
