package com.ibm.wcm.ods.vo;
// Generated May 31, 2018 4:53:55 PM by Hibernate Tools 5.2.6.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClientProfilePapSrc generated by hbm2java
 */
import com.ibm.gbs.util.Constant; 
//  @Entity
//  @Table(schema = Constant.SCHEMANAME_ODS , name = "CLIENT_PROFILE_PAP_SRC")
public class ClientProfilePapSrcVO  {   // implements  java.io.Serializable {

	private BigDecimal clientProfilePapSeqNum;
	private String clientId;
	private String sourceSystemId;
	private Date processTs;
	private String totalAidPaid;
	private String casePayee;
	private String ssisspRecipiant;
	private String ssisspVerifSource;
	private String primaryIndicator;
	//private Set<CpPapEligSrc> cpPapEligSrcs = new HashSet<CpPapEligSrc>(0);

	public ClientProfilePapSrcVO() {
	}

	

	//  @Id

	//  @Column(name = "CLIENT_PROFILE_PAP_SEQ_NUM", unique = true, nullable = false, precision = 31, scale = 0)
	public BigDecimal getClientProfilePapSeqNum() {
		return this.clientProfilePapSeqNum;
	}

	public void setClientProfilePapSeqNum(BigDecimal clientProfilePapSeqNum) {
		this.clientProfilePapSeqNum = clientProfilePapSeqNum;
	}

	//  @Column(name = "CLIENT_ID", nullable = false, length = 60)
	public String getClientId() {
		return this.clientId;
	}

	public void setClientId(String clientId) {
		this.clientId = clientId;
	}

	//  @Column(name = "SOURCE_SYSTEM_ID", nullable = false, length = 40)
	public String getSourceSystemId() {
		return this.sourceSystemId;
	}

	public void setSourceSystemId(String sourceSystemId) {
		this.sourceSystemId = sourceSystemId;
	}

	//  @Temporal(TemporalType.TIMESTAMP)
	//  @Column(name = "PROCESS_TS", length = 26)
	public Date getProcessTs() {
		return this.processTs;
	}

	public void setProcessTs(Date processTs) {
		this.processTs = processTs;
	}

	//  @Column(name = "TOTAL_AID_PAID", length = 10)
	public String getTotalAidPaid() {
		return this.totalAidPaid;
	}

	public void setTotalAidPaid(String totalAidPaid) {
		this.totalAidPaid = totalAidPaid;
	}

	//  @Column(name = "CASE_PAYEE", length = 90)
	public String getCasePayee() {
		return this.casePayee;
	}

	public void setCasePayee(String casePayee) {
		this.casePayee = casePayee;
	}

	//  @Column(name = "SSISSP_RECIPIANT", length = 3)
	public String getSsisspRecipiant() {
		return this.ssisspRecipiant;
	}

	public void setSsisspRecipiant(String ssisspRecipiant) {
		this.ssisspRecipiant = ssisspRecipiant;
	}

	//  @Column(name = "SSISSP_VERIF_SOURCE", length = 30)
	public String getSsisspVerifSource() {
		return this.ssisspVerifSource;
	}

	public void setSsisspVerifSource(String ssisspVerifSource) {
		this.ssisspVerifSource = ssisspVerifSource;
	}

	//  @Column(name = "PRIMARY_INDICATOR", length = 1)
	public String getPrimaryIndicator() {
		return this.primaryIndicator;
	}

	public void setPrimaryIndicator(String primaryIndicator) {
		this.primaryIndicator = primaryIndicator;
	}

	//  @OneToMany(fetch = FetchType.LAZY, mappedBy = "clientProfilePapSrc")
	/*public Set<CpPapEligSrc> getCpPapEligSrcs() {
		return this.cpPapEligSrcs;
	}

	public void setCpPapEligSrcs(Set<CpPapEligSrc> cpPapEligSrcs) {
		this.cpPapEligSrcs = cpPapEligSrcs;
	}*/

}
