package com.ibm.wcm.ods.vo;
// Generated May 31, 2018 4:53:55 PM by Hibernate Tools 5.2.6.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClientProfileDemoSrc generated by hbm2java
 */
import com.ibm.gbs.util.Constant; 
//  @Entity
//  @Table(schema = Constant.SCHEMANAME_ODS , name = "CLIENT_PROFILE_DEMO_SRC")
public class ClientProfileDemoSrc  {   // implements  java.io.Serializable {

	private BigDecimal clientProfileDemoSeqNum;
	private String clientId;
	private String sourceSystemId;
	private Date processTs;
	private Set<CpDemoVehicleSrc> cpDemoVehicleSrcs = new HashSet<CpDemoVehicleSrc>(0);
	private Set<CpDemoIdmarkSrc> cpDemoIdmarkSrcs = new HashSet<CpDemoIdmarkSrc>(0);
	private Set<CpDemoPhyAddrSrc> cpDemoPhyAddrSrcs = new HashSet<CpDemoPhyAddrSrc>(0);
	private Set<CpDemoPrvAddrSrc> cpDemoPrvAddrSrcs = new HashSet<CpDemoPrvAddrSrc>(0);
	private Set<CpDemoEmplSrc> cpDemoEmplSrcs = new HashSet<CpDemoEmplSrc>(0);
	private Set<CpDemoPrvPhoneSrc> cpDemoPrvPhoneSrcs = new HashSet<CpDemoPrvPhoneSrc>(0);
	private Set<CpDemoAkaSrc> cpDemoAkaSrcs = new HashSet<CpDemoAkaSrc>(0);

	public ClientProfileDemoSrc() {
	}

	public ClientProfileDemoSrc(BigDecimal clientProfileDemoSeqNum) {
		this.clientProfileDemoSeqNum = clientProfileDemoSeqNum;
	}

	public ClientProfileDemoSrc(BigDecimal clientProfileDemoSeqNum, String clientId, String sourceSystemId,
			Date processTs, Set<CpDemoVehicleSrc> cpDemoVehicleSrcs, Set<CpDemoIdmarkSrc> cpDemoIdmarkSrcs,
			Set<CpDemoPhyAddrSrc> cpDemoPhyAddrSrcs, Set<CpDemoPrvAddrSrc> cpDemoPrvAddrSrcs,
			Set<CpDemoEmplSrc> cpDemoEmplSrcs, Set<CpDemoPrvPhoneSrc> cpDemoPrvPhoneSrcs,
			Set<CpDemoAkaSrc> cpDemoAkaSrcs) {
		this.clientProfileDemoSeqNum = clientProfileDemoSeqNum;
		this.clientId = clientId;
		this.sourceSystemId = sourceSystemId;
		this.processTs = processTs;
		this.cpDemoVehicleSrcs = cpDemoVehicleSrcs;
		this.cpDemoIdmarkSrcs = cpDemoIdmarkSrcs;
		this.cpDemoPhyAddrSrcs = cpDemoPhyAddrSrcs;
		this.cpDemoPrvAddrSrcs = cpDemoPrvAddrSrcs;
		this.cpDemoEmplSrcs = cpDemoEmplSrcs;
		this.cpDemoPrvPhoneSrcs = cpDemoPrvPhoneSrcs;
		this.cpDemoAkaSrcs = cpDemoAkaSrcs;
	}

	//  @Id

	//  @Column(name = "CLIENT_PROFILE_DEMO_SEQ_NUM", unique = true, nullable = false, precision = 31, scale = 0)
	public BigDecimal getClientProfileDemoSeqNum() {
		return this.clientProfileDemoSeqNum;
	}

	public void setClientProfileDemoSeqNum(BigDecimal clientProfileDemoSeqNum) {
		this.clientProfileDemoSeqNum = clientProfileDemoSeqNum;
	}

	//  @Column(name = "CLIENT_ID", length = 60)
	public String getClientId() {
		return this.clientId;
	}

	public void setClientId(String clientId) {
		this.clientId = clientId;
	}

	//  @Column(name = "SOURCE_SYSTEM_ID", length = 40)
	public String getSourceSystemId() {
		return this.sourceSystemId;
	}

	public void setSourceSystemId(String sourceSystemId) {
		this.sourceSystemId = sourceSystemId;
	}

	//  @Temporal(TemporalType.TIMESTAMP)
	//  @Column(name = "PROCESS_TS", length = 26)
	public Date getProcessTs() {
		return this.processTs;
	}

	public void setProcessTs(Date processTs) {
		this.processTs = processTs;
	}

	//  @OneToMany(fetch = FetchType.LAZY, mappedBy = "clientProfileDemoSrc")
	public Set<CpDemoVehicleSrc> getCpDemoVehicleSrcs() {
		return this.cpDemoVehicleSrcs;
	}

	public void setCpDemoVehicleSrcs(Set<CpDemoVehicleSrc> cpDemoVehicleSrcs) {
		this.cpDemoVehicleSrcs = cpDemoVehicleSrcs;
	}

	//  @OneToMany(fetch = FetchType.LAZY, mappedBy = "clientProfileDemoSrc")
	public Set<CpDemoIdmarkSrc> getCpDemoIdmarkSrcs() {
		return this.cpDemoIdmarkSrcs;
	}

	public void setCpDemoIdmarkSrcs(Set<CpDemoIdmarkSrc> cpDemoIdmarkSrcs) {
		this.cpDemoIdmarkSrcs = cpDemoIdmarkSrcs;
	}

	//  @OneToMany(fetch = FetchType.LAZY, mappedBy = "clientProfileDemoSrc")
	public Set<CpDemoPhyAddrSrc> getCpDemoPhyAddrSrcs() {
		return this.cpDemoPhyAddrSrcs;
	}

	public void setCpDemoPhyAddrSrcs(Set<CpDemoPhyAddrSrc> cpDemoPhyAddrSrcs) {
		this.cpDemoPhyAddrSrcs = cpDemoPhyAddrSrcs;
	}

	//  @OneToMany(fetch = FetchType.LAZY, mappedBy = "clientProfileDemoSrc")
	public Set<CpDemoPrvAddrSrc> getCpDemoPrvAddrSrcs() {
		return this.cpDemoPrvAddrSrcs;
	}

	public void setCpDemoPrvAddrSrcs(Set<CpDemoPrvAddrSrc> cpDemoPrvAddrSrcs) {
		this.cpDemoPrvAddrSrcs = cpDemoPrvAddrSrcs;
	}

	//  @OneToMany(fetch = FetchType.LAZY, mappedBy = "clientProfileDemoSrc")
	public Set<CpDemoEmplSrc> getCpDemoEmplSrcs() {
		return this.cpDemoEmplSrcs;
	}

	public void setCpDemoEmplSrcs(Set<CpDemoEmplSrc> cpDemoEmplSrcs) {
		this.cpDemoEmplSrcs = cpDemoEmplSrcs;
	}

	//  @OneToMany(fetch = FetchType.LAZY, mappedBy = "clientProfileDemoSrc")
	public Set<CpDemoPrvPhoneSrc> getCpDemoPrvPhoneSrcs() {
		return this.cpDemoPrvPhoneSrcs;
	}

	public void setCpDemoPrvPhoneSrcs(Set<CpDemoPrvPhoneSrc> cpDemoPrvPhoneSrcs) {
		this.cpDemoPrvPhoneSrcs = cpDemoPrvPhoneSrcs;
	}

	//  @OneToMany(fetch = FetchType.LAZY, mappedBy = "clientProfileDemoSrc")
	public Set<CpDemoAkaSrc> getCpDemoAkaSrcs() {
		return this.cpDemoAkaSrcs;
	}

	public void setCpDemoAkaSrcs(Set<CpDemoAkaSrc> cpDemoAkaSrcs) {
		this.cpDemoAkaSrcs = cpDemoAkaSrcs;
	}

}
