package com.ibm.wcm.ods.vo;
// Generated May 31, 2018 4:53:55 PM by Hibernate Tools 5.2.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ClientProfilePapSrcT1 generated by hbm2java
 */
import com.ibm.gbs.util.Constant; 
//  @Entity
//  @Table(schema = Constant.SCHEMANAME_ODS , name = "CLIENT_PROFILE_PAP_SRC_T1")
public class ClientProfilePapSrcT1  {   // implements  java.io.Serializable {

	private ClientProfilePapSrcT1Id id;

	public ClientProfilePapSrcT1() {
	}

	public ClientProfilePapSrcT1(ClientProfilePapSrcT1Id id) {
		this.id = id;
	}

	//  @EmbeddedId

	//  @AttributeOverrides({
			//  @AttributeOverride(name = "clientProfPapSeqNum", column = //  @Column(name = "CLIENT_PROF_PAP_SEQ_NUM", precision = 31, scale = 0)),
			//  @AttributeOverride(name = "clientId", column = //  @Column(name = "CLIENT_ID", precision = 31, scale = 0)),
			//  @AttributeOverride(name = "caseId", column = //  @Column(name = "CASE_ID", length = 50)) })
	public ClientProfilePapSrcT1Id getId() {
		return this.id;
	}

	public void setId(ClientProfilePapSrcT1Id id) {
		this.id = id;
	}

}
