package com.ibm.wcm.ods.vo;
// Generated May 31, 2018 4:53:55 PM by Hibernate Tools 5.2.6.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClientProfileMedSrc generated by hbm2java
 */
import com.ibm.gbs.util.Constant; 
//  @Entity
//  @Table(schema = Constant.SCHEMANAME_ODS , name = "CLIENT_PROFILE_MED_SRC")
public class ClientProfileMedSrcVo  {   // implements  java.io.Serializable {

	private BigDecimal clientProfileMedSeqNum;
	private String clientId;
	private String sourceSystemId;
	private Date admissionDate;
	private String numHospOvrnitePast30d;
	private String numEmgncyRmPast30d;
	private String lastHospDate;
	private String doctorName;
	private String doctorType;
	private String medProviderPhone;
	private String hepC;
	private String std;
	private String tb;
	private Date lastTbTestDate;
	private Date processTs;

	public ClientProfileMedSrcVo() {
	}

	public ClientProfileMedSrcVo(BigDecimal clientProfileMedSeqNum, String clientId, String sourceSystemId) {
		this.clientProfileMedSeqNum = clientProfileMedSeqNum;
		this.clientId = clientId;
		this.sourceSystemId = sourceSystemId;
	}

	public ClientProfileMedSrcVo(BigDecimal clientProfileMedSeqNum, String clientId, String sourceSystemId,
			Date admissionDate, String numHospOvrnitePast30d, String numEmgncyRmPast30d, String lastHospDate,
			String doctorName, String doctorType, String medProviderPhone, String hepC, String std, String tb,
			Date lastTbTestDate, Date processTs) {
		this.clientProfileMedSeqNum = clientProfileMedSeqNum;
		this.clientId = clientId;
		this.sourceSystemId = sourceSystemId;
		this.admissionDate = admissionDate;
		this.numHospOvrnitePast30d = numHospOvrnitePast30d;
		this.numEmgncyRmPast30d = numEmgncyRmPast30d;
		this.lastHospDate = lastHospDate;
		this.doctorName = doctorName;
		this.doctorType = doctorType;
		this.medProviderPhone = medProviderPhone;
		this.hepC = hepC;
		this.std = std;
		this.tb = tb;
		this.lastTbTestDate = lastTbTestDate;
		this.processTs = processTs;
	}

	//  @Id

	//  @Column(name = "CLIENT_PROFILE_MED_SEQ_NUM", unique = true, nullable = false, precision = 31, scale = 0)
	public BigDecimal getClientProfileMedSeqNum() {
		return this.clientProfileMedSeqNum;
	}

	public void setClientProfileMedSeqNum(BigDecimal clientProfileMedSeqNum) {
		this.clientProfileMedSeqNum = clientProfileMedSeqNum;
	}

	//  @Column(name = "CLIENT_ID", nullable = false, length = 60)
	public String getClientId() {
		return this.clientId;
	}

	public void setClientId(String clientId) {
		this.clientId = clientId;
	}

	//  @Column(name = "SOURCE_SYSTEM_ID", nullable = false, length = 40)
	public String getSourceSystemId() {
		return this.sourceSystemId;
	}

	public void setSourceSystemId(String sourceSystemId) {
		this.sourceSystemId = sourceSystemId;
	}

	//  @Temporal(TemporalType.DATE)
	//  @Column(name = "ADMISSION_DATE", length = 10)
	public Date getAdmissionDate() {
		return this.admissionDate;
	}

	public void setAdmissionDate(Date admissionDate) {
		this.admissionDate = admissionDate;
	}

	//  @Column(name = "NUM_HOSP_OVRNITE_PAST30D", length = 256)
	public String getNumHospOvrnitePast30d() {
		return this.numHospOvrnitePast30d;
	}

	public void setNumHospOvrnitePast30d(String numHospOvrnitePast30d) {
		this.numHospOvrnitePast30d = numHospOvrnitePast30d;
	}

	//  @Column(name = "NUM_EMGNCY_RM_PAST30D", length = 256)
	public String getNumEmgncyRmPast30d() {
		return this.numEmgncyRmPast30d;
	}

	public void setNumEmgncyRmPast30d(String numEmgncyRmPast30d) {
		this.numEmgncyRmPast30d = numEmgncyRmPast30d;
	}

	//  @Column(name = "LAST_HOSP_DATE", length = 60)
	public String getLastHospDate() {
		return this.lastHospDate;
	}

	public void setLastHospDate(String lastHospDate) {
		this.lastHospDate = lastHospDate;
	}

	//  @Column(name = "DOCTOR_NAME", length = 100)
	public String getDoctorName() {
		return this.doctorName;
	}

	public void setDoctorName(String doctorName) {
		this.doctorName = doctorName;
	}

	//  @Column(name = "DOCTOR_TYPE", length = 60)
	public String getDoctorType() {
		return this.doctorType;
	}

	public void setDoctorType(String doctorType) {
		this.doctorType = doctorType;
	}

	//  @Column(name = "MED_PROVIDER_PHONE", length = 50)
	public String getMedProviderPhone() {
		return this.medProviderPhone;
	}

	public void setMedProviderPhone(String medProviderPhone) {
		this.medProviderPhone = medProviderPhone;
	}

	//  @Column(name = "HEP_C", length = 60)
	public String getHepC() {
		return this.hepC;
	}

	public void setHepC(String hepC) {
		this.hepC = hepC;
	}

	//  @Column(name = "STD", length = 60)
	public String getStd() {
		return this.std;
	}

	public void setStd(String std) {
		this.std = std;
	}

	//  @Column(name = "TB", length = 60)
	public String getTb() {
		return this.tb;
	}

	public void setTb(String tb) {
		this.tb = tb;
	}

	//  @Temporal(TemporalType.DATE)
	//  @Column(name = "LAST_TB_TEST_DATE", length = 10)
	public Date getLastTbTestDate() {
		return this.lastTbTestDate;
	}

	public void setLastTbTestDate(Date lastTbTestDate) {
		this.lastTbTestDate = lastTbTestDate;
	}

	//  @Temporal(TemporalType.TIMESTAMP)
	//  @Column(name = "PROCESS_TS", length = 26)
	public Date getProcessTs() {
		return this.processTs;
	}

	public void setProcessTs(Date processTs) {
		this.processTs = processTs;
	}

}
