package com.ibm.wcm.ods.vo;
// Generated May 31, 2018 4:53:55 PM by Hibernate Tools 5.2.6.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import com.ibm.gbs.util.Constant;

/**
 * ClientProfileHlthSrc generated by hbm2java
 */
import com.ibm.gbs.util.Constant; 
//  @Entity
//  @Table(schema = Constant.SCHEMANAME_ODS , name = "CLIENT_PROFILE_HLTH_SRC")
public class ClientProfileHlthSrcVo  {   // implements  java.io.Serializable {

	private BigDecimal clientProfileHlthSeqNum;
	private String clientId;
	private String sourceSystemId;
	private String disabilities;
	private String smokerStatus;
	private String numTobacNicUsePast30d;
	private Date processTs;
	private String disabilityStatus;
	private Date admitDate;
	private String caseWorker;
	private String cwPhoneNum;
	private Set<CpHlthMedSrcVo> cpHlthMedSrcs = new HashSet<CpHlthMedSrcVo>(0);
	private Set<CpHlthMedImmunSrc> cpHlthMedImmunSrcs = new HashSet<CpHlthMedImmunSrc>(0);
	private Set<CpHlthInstSrc> cpHlthInstSrcs = new HashSet<CpHlthInstSrc>(0);
	private Set<CpHlthTestSrc> cpHlthTestSrcs = new HashSet<CpHlthTestSrc>(0);
	private Set<CpHlthHospSrc> cpHlthHospSrcs = new HashSet<CpHlthHospSrc>(0);
	private Set<CpHlthInsSrcVo> cpHlthInsSrcs = new HashSet<CpHlthInsSrcVo>(0);
	private Set<CpHlthMedStatusSrcVo> cpHlthMedStatusSrcs = new HashSet<CpHlthMedStatusSrcVo>(0);
	private Set<CpHlthPrvdrSrc> cpHlthPrvdrSrcs = new HashSet<CpHlthPrvdrSrc>(0);

	public ClientProfileHlthSrcVo() {
	}

	public ClientProfileHlthSrcVo(BigDecimal clientProfileHlthSeqNum, String clientId, String sourceSystemId) {
		this.clientProfileHlthSeqNum = clientProfileHlthSeqNum;
		this.clientId = clientId;
		this.sourceSystemId = sourceSystemId;
	}

	public ClientProfileHlthSrcVo(BigDecimal clientProfileHlthSeqNum, String clientId, String sourceSystemId,
			String disabilities, String smokerStatus, String numTobacNicUsePast30d, Date processTs,
			String disabilityStatus, Date admitDate, String caseWorker, String cwPhoneNum,
			Set<CpHlthMedSrcVo> cpHlthMedSrcs, Set<CpHlthMedImmunSrc> cpHlthMedImmunSrcs,
			Set<CpHlthInstSrc> cpHlthInstSrcs, Set<CpHlthTestSrc> cpHlthTestSrcs, Set<CpHlthHospSrc> cpHlthHospSrcs,
			Set<CpHlthInsSrcVo> cpHlthInsSrcs, Set<CpHlthMedStatusSrcVo> cpHlthMedStatusSrcs,
			Set<CpHlthPrvdrSrc> cpHlthPrvdrSrcs) {
		this.clientProfileHlthSeqNum = clientProfileHlthSeqNum;
		this.clientId = clientId;
		this.sourceSystemId = sourceSystemId;
		this.disabilities = disabilities;
		this.smokerStatus = smokerStatus;
		this.numTobacNicUsePast30d = numTobacNicUsePast30d;
		this.processTs = processTs;
		this.disabilityStatus = disabilityStatus;
		this.admitDate = admitDate;
		this.caseWorker = caseWorker;
		this.cwPhoneNum = cwPhoneNum;
		this.cpHlthMedSrcs = cpHlthMedSrcs;
		this.cpHlthMedImmunSrcs = cpHlthMedImmunSrcs;
		this.cpHlthInstSrcs = cpHlthInstSrcs;
		this.cpHlthTestSrcs = cpHlthTestSrcs;
		this.cpHlthHospSrcs = cpHlthHospSrcs;
		this.cpHlthInsSrcs = cpHlthInsSrcs;
		this.cpHlthMedStatusSrcs = cpHlthMedStatusSrcs;
		this.cpHlthPrvdrSrcs = cpHlthPrvdrSrcs;
	}

	//  @Id

	//  @Column(name = "CLIENT_PROFILE_HLTH_SEQ_NUM", unique = true, nullable = false, precision = 31, scale = 0)
	public BigDecimal getClientProfileHlthSeqNum() {
		return this.clientProfileHlthSeqNum;
	}

	public void setClientProfileHlthSeqNum(BigDecimal clientProfileHlthSeqNum) {
		this.clientProfileHlthSeqNum = clientProfileHlthSeqNum;
	}

	//  @Column(name = "CLIENT_ID", nullable = false, length = 60)
	public String getClientId() {
		return this.clientId;
	}

	public void setClientId(String clientId) {
		this.clientId = clientId;
	}

	//  @Column(name = "SOURCE_SYSTEM_ID", nullable = false, length = 40)
	public String getSourceSystemId() {
		return this.sourceSystemId;
	}

	public void setSourceSystemId(String sourceSystemId) {
		this.sourceSystemId = sourceSystemId;
	}

	//  @Column(name = "DISABILITIES", length = 512)
	public String getDisabilities() {
		return this.disabilities;
	}

	public void setDisabilities(String disabilities) {
		this.disabilities = disabilities;
	}

	//  @Column(name = "SMOKER_STATUS", length = 256)
	public String getSmokerStatus() {
		return this.smokerStatus;
	}

	public void setSmokerStatus(String smokerStatus) {
		this.smokerStatus = smokerStatus;
	}

	//  @Column(name = "NUM_TOBAC_NIC_USE_PAST30D", length = 256)
	public String getNumTobacNicUsePast30d() {
		return this.numTobacNicUsePast30d;
	}

	public void setNumTobacNicUsePast30d(String numTobacNicUsePast30d) {
		this.numTobacNicUsePast30d = numTobacNicUsePast30d;
	}

	//  @Temporal(TemporalType.TIMESTAMP)
	//  @Column(name = "PROCESS_TS", length = 26)
	public Date getProcessTs() {
		return this.processTs;
	}

	public void setProcessTs(Date processTs) {
		this.processTs = processTs;
	}

	//  @Column(name = "DISABILITY_STATUS", length = 3)
	public String getDisabilityStatus() {
		return this.disabilityStatus;
	}

	public void setDisabilityStatus(String disabilityStatus) {
		this.disabilityStatus = disabilityStatus;
	}

	//  @Temporal(TemporalType.DATE)
	//  @Column(name = "ADMIT_DATE", length = 10)
	public Date getAdmitDate() {
		return this.admitDate;
	}

	public void setAdmitDate(Date admitDate) {
		this.admitDate = admitDate;
	}

	//  @Column(name = "CASE_WORKER", length = 40)
	public String getCaseWorker() {
		return this.caseWorker;
	}

	public void setCaseWorker(String caseWorker) {
		this.caseWorker = caseWorker;
	}

	//  @Column(name = "CW_PHONE_NUM", length = 14)
	public String getCwPhoneNum() {
		return this.cwPhoneNum;
	}

	public void setCwPhoneNum(String cwPhoneNum) {
		this.cwPhoneNum = cwPhoneNum;
	}

	//  @OneToMany(fetch = FetchType.LAZY, mappedBy = "clientProfileHlthSrc")
	public Set<CpHlthMedSrcVo> getCpHlthMedSrcs() {
		return this.cpHlthMedSrcs;
	}

	public void setCpHlthMedSrcs(Set<CpHlthMedSrcVo> cpHlthMedSrcs) {
		this.cpHlthMedSrcs = cpHlthMedSrcs;
	}

	//  @OneToMany(fetch = FetchType.LAZY, mappedBy = "clientProfileHlthSrc")
	public Set<CpHlthMedImmunSrc> getCpHlthMedImmunSrcs() {
		return this.cpHlthMedImmunSrcs;
	}

	public void setCpHlthMedImmunSrcs(Set<CpHlthMedImmunSrc> cpHlthMedImmunSrcs) {
		this.cpHlthMedImmunSrcs = cpHlthMedImmunSrcs;
	}

	//  @OneToMany(fetch = FetchType.LAZY, mappedBy = "clientProfileHlthSrc")
	public Set<CpHlthInstSrc> getCpHlthInstSrcs() {
		return this.cpHlthInstSrcs;
	}

	public void setCpHlthInstSrcs(Set<CpHlthInstSrc> cpHlthInstSrcs) {
		this.cpHlthInstSrcs = cpHlthInstSrcs;
	}

	//  @OneToMany(fetch = FetchType.LAZY, mappedBy = "clientProfileHlthSrc")
	public Set<CpHlthTestSrc> getCpHlthTestSrcs() {
		return this.cpHlthTestSrcs;
	}

	public void setCpHlthTestSrcs(Set<CpHlthTestSrc> cpHlthTestSrcs) {
		this.cpHlthTestSrcs = cpHlthTestSrcs;
	}

	//  @OneToMany(fetch = FetchType.LAZY, mappedBy = "clientProfileHlthSrc")
	public Set<CpHlthHospSrc> getCpHlthHospSrcs() {
		return this.cpHlthHospSrcs;
	}

	public void setCpHlthHospSrcs(Set<CpHlthHospSrc> cpHlthHospSrcs) {
		this.cpHlthHospSrcs = cpHlthHospSrcs;
	}

	//  @OneToMany(fetch = FetchType.LAZY, mappedBy = "clientProfileHlthSrc")
	public Set<CpHlthInsSrcVo> getCpHlthInsSrcs() {
		return this.cpHlthInsSrcs;
	}

	public void setCpHlthInsSrcs(Set<CpHlthInsSrcVo> cpHlthInsSrcs) {
		this.cpHlthInsSrcs = cpHlthInsSrcs;
	}

	//  @OneToMany(fetch = FetchType.LAZY, mappedBy = "clientProfileHlthSrc")
	public Set<CpHlthMedStatusSrcVo> getCpHlthMedStatusSrcs() {
		return this.cpHlthMedStatusSrcs;
	}

	public void setCpHlthMedStatusSrcs(Set<CpHlthMedStatusSrcVo> cpHlthMedStatusSrcs) {
		this.cpHlthMedStatusSrcs = cpHlthMedStatusSrcs;
	}

	//  @OneToMany(fetch = FetchType.LAZY, mappedBy = "clientProfileHlthSrc")
	public Set<CpHlthPrvdrSrc> getCpHlthPrvdrSrcs() {
		return this.cpHlthPrvdrSrcs;
	}

	public void setCpHlthPrvdrSrcs(Set<CpHlthPrvdrSrc> cpHlthPrvdrSrcs) {
		this.cpHlthPrvdrSrcs = cpHlthPrvdrSrcs;
	}

}
