package com.ibm.wcm.ods.vo;
// Generated May 31, 2018 4:53:55 PM by Hibernate Tools 5.2.6.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CpAdsTestResultSrc generated by hbm2java
 */
import com.ibm.gbs.util.Constant;
import com.ibm.wcm.ods.dto.ClientProfileAdsSrc; 
//  @Entity
//  @Table(schema = Constant.SCHEMANAME_ODS , name = "CP_ADS_TEST_RESULT_SRC")
public class CpAdsTestResultSrcVo  {   // implements  java.io.Serializable {

	private BigDecimal cpAdsTestResultSeqNum;
	private ClientProfileAdsSrc clientProfileAdsSrc;
	private String drugTest;
	private Date testResultDate;
	private String testResultType;
	private String specimenNum;
	private String testConfirmedPos;
	private String testUnconfirmedPos;

	public CpAdsTestResultSrcVo() {
	}

	public CpAdsTestResultSrcVo(BigDecimal cpAdsTestResultSeqNum, ClientProfileAdsSrc clientProfileAdsSrc) {
		this.cpAdsTestResultSeqNum = cpAdsTestResultSeqNum;
		this.clientProfileAdsSrc = clientProfileAdsSrc;
	}

	public CpAdsTestResultSrcVo(BigDecimal cpAdsTestResultSeqNum, ClientProfileAdsSrc clientProfileAdsSrc,
			String drugTest, Date testResultDate, String testResultType, String specimenNum, String testConfirmedPos,
			String testUnconfirmedPos) {
		this.cpAdsTestResultSeqNum = cpAdsTestResultSeqNum;
		this.clientProfileAdsSrc = clientProfileAdsSrc;
		this.drugTest = drugTest;
		this.testResultDate = testResultDate;
		this.testResultType = testResultType;
		this.specimenNum = specimenNum;
		this.testConfirmedPos = testConfirmedPos;
		this.testUnconfirmedPos = testUnconfirmedPos;
	}

	//  @Id

	//  @Column(name = "CP_ADS_TEST_RESULT_SEQ_NUM", unique = true, nullable = false, precision = 31, scale = 0)
	public BigDecimal getCpAdsTestResultSeqNum() {
		return this.cpAdsTestResultSeqNum;
	}

	public void setCpAdsTestResultSeqNum(BigDecimal cpAdsTestResultSeqNum) {
		this.cpAdsTestResultSeqNum = cpAdsTestResultSeqNum;
	}

	//  @ManyToOne(fetch = FetchType.LAZY)
	//  @JoinColumn(name = "CLIENT_PROFILE_ADS_SEQ_NUM", nullable = false)
	public ClientProfileAdsSrc getClientProfileAdsSrc() {
		return this.clientProfileAdsSrc;
	}

	public void setClientProfileAdsSrc(ClientProfileAdsSrc clientProfileAdsSrc) {
		this.clientProfileAdsSrc = clientProfileAdsSrc;
	}

	//  @Column(name = "DRUG_TEST", length = 256)
	public String getDrugTest() {
		return this.drugTest;
	}

	public void setDrugTest(String drugTest) {
		this.drugTest = drugTest;
	}

	//  @Temporal(TemporalType.DATE)
	//  @Column(name = "TEST_RESULT_DATE", length = 10)
	public Date getTestResultDate() {
		return this.testResultDate;
	}

	public void setTestResultDate(Date testResultDate) {
		this.testResultDate = testResultDate;
	}

	//  @Column(name = "TEST_RESULT_TYPE", length = 256)
	public String getTestResultType() {
		return this.testResultType;
	}

	public void setTestResultType(String testResultType) {
		this.testResultType = testResultType;
	}

	//  @Column(name = "SPECIMEN_NUM", length = 50)
	public String getSpecimenNum() {
		return this.specimenNum;
	}

	public void setSpecimenNum(String specimenNum) {
		this.specimenNum = specimenNum;
	}

	//  @Column(name = "TEST_CONFIRMED_POS", length = 3)
	public String getTestConfirmedPos() {
		return this.testConfirmedPos;
	}

	public void setTestConfirmedPos(String testConfirmedPos) {
		this.testConfirmedPos = testConfirmedPos;
	}

	//  @Column(name = "TEST_UNCONFIRMED_POS", length = 3)
	public String getTestUnconfirmedPos() {
		return this.testUnconfirmedPos;
	}

	public void setTestUnconfirmedPos(String testUnconfirmedPos) {
		this.testUnconfirmedPos = testUnconfirmedPos;
	}

}
