package com.ibm.wcm.ods.vo;
// Generated May 31, 2018 4:53:55 PM by Hibernate Tools 5.2.6.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CpDemoEmplSrc generated by hbm2java
 */
import com.ibm.gbs.util.Constant; 
//  @Entity
//  @Table(schema = Constant.SCHEMANAME_ODS , name = "CP_DEMO_EMPL_SRC")
public class CpDemoEmplSrc  {   // implements  java.io.Serializable {

	private BigDecimal cpDemoEmplSeqNum;
	private ClientProfileDemoSrc clientProfileDemoSrc;
	private String empStatus;
	private String jobTitle;
	private String supervisor;
	private String endReason;
	private String notes;
	private Date startDate;
	private Date endDate;
	private String empAddr;

	public CpDemoEmplSrc() {
	}

	public CpDemoEmplSrc(BigDecimal cpDemoEmplSeqNum, ClientProfileDemoSrc clientProfileDemoSrc) {
		this.cpDemoEmplSeqNum = cpDemoEmplSeqNum;
		this.clientProfileDemoSrc = clientProfileDemoSrc;
	}

	public CpDemoEmplSrc(BigDecimal cpDemoEmplSeqNum, ClientProfileDemoSrc clientProfileDemoSrc, String empStatus,
			String jobTitle, String supervisor, String endReason, String notes, Date startDate, Date endDate,
			String empAddr) {
		this.cpDemoEmplSeqNum = cpDemoEmplSeqNum;
		this.clientProfileDemoSrc = clientProfileDemoSrc;
		this.empStatus = empStatus;
		this.jobTitle = jobTitle;
		this.supervisor = supervisor;
		this.endReason = endReason;
		this.notes = notes;
		this.startDate = startDate;
		this.endDate = endDate;
		this.empAddr = empAddr;
	}

	//  @Id

	//  @Column(name = "CP_DEMO_EMPL_SEQ_NUM", unique = true, nullable = false, precision = 31, scale = 0)
	public BigDecimal getCpDemoEmplSeqNum() {
		return this.cpDemoEmplSeqNum;
	}

	public void setCpDemoEmplSeqNum(BigDecimal cpDemoEmplSeqNum) {
		this.cpDemoEmplSeqNum = cpDemoEmplSeqNum;
	}

	//  @ManyToOne(fetch = FetchType.LAZY)
	//  @JoinColumn(name = "CLIENT_PROFILE_DEMO_SEQ_NUM", nullable = false)
	public ClientProfileDemoSrc getClientProfileDemoSrc() {
		return this.clientProfileDemoSrc;
	}

	public void setClientProfileDemoSrc(ClientProfileDemoSrc clientProfileDemoSrc) {
		this.clientProfileDemoSrc = clientProfileDemoSrc;
	}

	//  @Column(name = "EMP_STATUS", length = 50)
	public String getEmpStatus() {
		return this.empStatus;
	}

	public void setEmpStatus(String empStatus) {
		this.empStatus = empStatus;
	}

	//  @Column(name = "JOB_TITLE", length = 200)
	public String getJobTitle() {
		return this.jobTitle;
	}

	public void setJobTitle(String jobTitle) {
		this.jobTitle = jobTitle;
	}

	//  @Column(name = "SUPERVISOR", length = 200)
	public String getSupervisor() {
		return this.supervisor;
	}

	public void setSupervisor(String supervisor) {
		this.supervisor = supervisor;
	}

	//  @Column(name = "END_REASON", length = 50)
	public String getEndReason() {
		return this.endReason;
	}

	public void setEndReason(String endReason) {
		this.endReason = endReason;
	}

	//  @Column(name = "NOTES", length = 3600)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	//  @Temporal(TemporalType.DATE)
	//  @Column(name = "START_DATE", length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	//  @Temporal(TemporalType.DATE)
	//  @Column(name = "END_DATE", length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	//  @Column(name = "EMP_ADDR", length = 200)
	public String getEmpAddr() {
		return this.empAddr;
	}

	public void setEmpAddr(String empAddr) {
		this.empAddr = empAddr;
	}

}
