package com.ibm.wcm.ods.vo;
// Generated May 31, 2018 4:53:55 PM by Hibernate Tools 5.2.6.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CpDemoPrvPhoneSrc generated by hbm2java
 */
import com.ibm.gbs.util.Constant; 
//  @Entity
//  @Table(schema = Constant.SCHEMANAME_ODS , name = "CP_DEMO_PRV_PHONE_SRC")
public class CpDemoPrvPhoneSrc  {   // implements  java.io.Serializable {

	private BigDecimal cpDemoPrvPhoneSeqNum;
	private ClientProfileDemoSrc clientProfileDemoSrc;
	private String lastPrevPhone;

	public CpDemoPrvPhoneSrc() {
	}

	public CpDemoPrvPhoneSrc(BigDecimal cpDemoPrvPhoneSeqNum, ClientProfileDemoSrc clientProfileDemoSrc) {
		this.cpDemoPrvPhoneSeqNum = cpDemoPrvPhoneSeqNum;
		this.clientProfileDemoSrc = clientProfileDemoSrc;
	}

	public CpDemoPrvPhoneSrc(BigDecimal cpDemoPrvPhoneSeqNum, ClientProfileDemoSrc clientProfileDemoSrc,
			String lastPrevPhone) {
		this.cpDemoPrvPhoneSeqNum = cpDemoPrvPhoneSeqNum;
		this.clientProfileDemoSrc = clientProfileDemoSrc;
		this.lastPrevPhone = lastPrevPhone;
	}

	//  @Id

	//  @Column(name = "CP_DEMO_PRV_PHONE_SEQ_NUM", unique = true, nullable = false, precision = 31, scale = 0)
	public BigDecimal getCpDemoPrvPhoneSeqNum() {
		return this.cpDemoPrvPhoneSeqNum;
	}

	public void setCpDemoPrvPhoneSeqNum(BigDecimal cpDemoPrvPhoneSeqNum) {
		this.cpDemoPrvPhoneSeqNum = cpDemoPrvPhoneSeqNum;
	}

	//  @ManyToOne(fetch = FetchType.LAZY)
	//  @JoinColumn(name = "CLIENT_PROFILE_DEMO_SEQ_NUM", nullable = false)
	public ClientProfileDemoSrc getClientProfileDemoSrc() {
		return this.clientProfileDemoSrc;
	}

	public void setClientProfileDemoSrc(ClientProfileDemoSrc clientProfileDemoSrc) {
		this.clientProfileDemoSrc = clientProfileDemoSrc;
	}

	//  @Column(name = "LAST_PREV_PHONE", length = 20)
	public String getLastPrevPhone() {
		return this.lastPrevPhone;
	}

	public void setLastPrevPhone(String lastPrevPhone) {
		this.lastPrevPhone = lastPrevPhone;
	}

}
