package com.ibm.wcm.ods.vo;
// Generated May 31, 2018 4:53:55 PM by Hibernate Tools 5.2.6.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CpDemoPrvAddrSrc generated by hbm2java
 */
import com.ibm.gbs.util.Constant; 
//  @Entity
//  @Table(schema = Constant.SCHEMANAME_ODS , name = "CP_DEMO_PRV_ADDR_SRC")
public class CpDemoPrvAddrSrc  {   // implements  java.io.Serializable {

	private BigDecimal cpDemoPrvAddrSeqNum;
	private ClientProfileDemoSrc clientProfileDemoSrc;
	private String lastPrevAddr;

	public CpDemoPrvAddrSrc() {
	}

	public CpDemoPrvAddrSrc(BigDecimal cpDemoPrvAddrSeqNum) {
		this.cpDemoPrvAddrSeqNum = cpDemoPrvAddrSeqNum;
	}

	public CpDemoPrvAddrSrc(BigDecimal cpDemoPrvAddrSeqNum, ClientProfileDemoSrc clientProfileDemoSrc,
			String lastPrevAddr) {
		this.cpDemoPrvAddrSeqNum = cpDemoPrvAddrSeqNum;
		this.clientProfileDemoSrc = clientProfileDemoSrc;
		this.lastPrevAddr = lastPrevAddr;
	}

	//  @Id

	//  @Column(name = "CP_DEMO_PRV_ADDR_SEQ_NUM", unique = true, nullable = false, precision = 31, scale = 0)
	public BigDecimal getCpDemoPrvAddrSeqNum() {
		return this.cpDemoPrvAddrSeqNum;
	}

	public void setCpDemoPrvAddrSeqNum(BigDecimal cpDemoPrvAddrSeqNum) {
		this.cpDemoPrvAddrSeqNum = cpDemoPrvAddrSeqNum;
	}

	//  @ManyToOne(fetch = FetchType.LAZY)
	//  @JoinColumn(name = "CLIENT_PROFILE_DEMO_SEQ_NUM")
	public ClientProfileDemoSrc getClientProfileDemoSrc() {
		return this.clientProfileDemoSrc;
	}

	public void setClientProfileDemoSrc(ClientProfileDemoSrc clientProfileDemoSrc) {
		this.clientProfileDemoSrc = clientProfileDemoSrc;
	}

	//  @Column(name = "LAST_PREV_ADDR", length = 128)
	public String getLastPrevAddr() {
		return this.lastPrevAddr;
	}

	public void setLastPrevAddr(String lastPrevAddr) {
		this.lastPrevAddr = lastPrevAddr;
	}

}
