package com.ibm.wcm.ods.vo;
// Generated May 31, 2018 4:53:55 PM by Hibernate Tools 5.2.6.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CpDemoAkaSrc generated by hbm2java
 */
import com.ibm.gbs.util.Constant; 
//  @Entity
//  @Table(schema = Constant.SCHEMANAME_ODS , name = "CP_DEMO_AKA_SRC")
public class CpDemoAkaSrc  {   // implements  java.io.Serializable {

	private BigDecimal cpDemoAkaSeqNum;
	private ClientProfileDemoSrc clientProfileDemoSrc;
	private String verifiedName;

	public CpDemoAkaSrc() {
	}

	public CpDemoAkaSrc(BigDecimal cpDemoAkaSeqNum, ClientProfileDemoSrc clientProfileDemoSrc) {
		this.cpDemoAkaSeqNum = cpDemoAkaSeqNum;
		this.clientProfileDemoSrc = clientProfileDemoSrc;
	}

	public CpDemoAkaSrc(BigDecimal cpDemoAkaSeqNum, ClientProfileDemoSrc clientProfileDemoSrc, String verifiedName) {
		this.cpDemoAkaSeqNum = cpDemoAkaSeqNum;
		this.clientProfileDemoSrc = clientProfileDemoSrc;
		this.verifiedName = verifiedName;
	}

	//  @Id

	//  @Column(name = "CP_DEMO_AKA_SEQ_NUM", unique = true, nullable = false, precision = 31, scale = 0)
	public BigDecimal getCpDemoAkaSeqNum() {
		return this.cpDemoAkaSeqNum;
	}

	public void setCpDemoAkaSeqNum(BigDecimal cpDemoAkaSeqNum) {
		this.cpDemoAkaSeqNum = cpDemoAkaSeqNum;
	}

	//  @ManyToOne(fetch = FetchType.LAZY)
	//  @JoinColumn(name = "CLIENT_PROFILE_DEMO_SEQ_NUM", nullable = false)
	public ClientProfileDemoSrc getClientProfileDemoSrc() {
		return this.clientProfileDemoSrc;
	}

	public void setClientProfileDemoSrc(ClientProfileDemoSrc clientProfileDemoSrc) {
		this.clientProfileDemoSrc = clientProfileDemoSrc;
	}

	//  @Column(name = "VERIFIED_NAME", length = 200)
	public String getVerifiedName() {
		return this.verifiedName;
	}

	public void setVerifiedName(String verifiedName) {
		this.verifiedName = verifiedName;
	}

}
