package com.ibm.wcm.ods.vo;
// Generated May 31, 2018 4:53:55 PM by Hibernate Tools 5.2.6.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CpDemoIdmarkSrc generated by hbm2java
 */
import com.ibm.gbs.util.Constant; 
//  @Entity
//  @Table(schema = Constant.SCHEMANAME_ODS , name = "CP_DEMO_IDMARK_SRC")
public class CpDemoIdmarkSrc  {   // implements  java.io.Serializable {

	private BigDecimal cpDemoIdmarkSeqNum;
	private ClientProfileDemoSrc clientProfileDemoSrc;
	private String idMarkDesc;
	private String idMarkType;
	private String idMarkLoc;

	public CpDemoIdmarkSrc() {
	}

	public CpDemoIdmarkSrc(BigDecimal cpDemoIdmarkSeqNum, ClientProfileDemoSrc clientProfileDemoSrc) {
		this.cpDemoIdmarkSeqNum = cpDemoIdmarkSeqNum;
		this.clientProfileDemoSrc = clientProfileDemoSrc;
	}

	public CpDemoIdmarkSrc(BigDecimal cpDemoIdmarkSeqNum, ClientProfileDemoSrc clientProfileDemoSrc, String idMarkDesc,
			String idMarkType, String idMarkLoc) {
		this.cpDemoIdmarkSeqNum = cpDemoIdmarkSeqNum;
		this.clientProfileDemoSrc = clientProfileDemoSrc;
		this.idMarkDesc = idMarkDesc;
		this.idMarkType = idMarkType;
		this.idMarkLoc = idMarkLoc;
	}

	//  @Id

	//  @Column(name = "CP_DEMO_IDMARK_SEQ_NUM", unique = true, nullable = false, precision = 31, scale = 0)
	public BigDecimal getCpDemoIdmarkSeqNum() {
		return this.cpDemoIdmarkSeqNum;
	}

	public void setCpDemoIdmarkSeqNum(BigDecimal cpDemoIdmarkSeqNum) {
		this.cpDemoIdmarkSeqNum = cpDemoIdmarkSeqNum;
	}

	//  @ManyToOne(fetch = FetchType.LAZY)
	//  @JoinColumn(name = "CLIENT_PROFILE_DEMO_SEQ_NUM", nullable = false)
	public ClientProfileDemoSrc getClientProfileDemoSrc() {
		return this.clientProfileDemoSrc;
	}

	public void setClientProfileDemoSrc(ClientProfileDemoSrc clientProfileDemoSrc) {
		this.clientProfileDemoSrc = clientProfileDemoSrc;
	}

	//  @Column(name = "ID_MARK_DESC", length = 3600)
	public String getIdMarkDesc() {
		return this.idMarkDesc;
	}

	public void setIdMarkDesc(String idMarkDesc) {
		this.idMarkDesc = idMarkDesc;
	}

	//  @Column(name = "ID_MARK_TYPE", length = 50)
	public String getIdMarkType() {
		return this.idMarkType;
	}

	public void setIdMarkType(String idMarkType) {
		this.idMarkType = idMarkType;
	}

	//  @Column(name = "ID_MARK_LOC", length = 3600)
	public String getIdMarkLoc() {
		return this.idMarkLoc;
	}

	public void setIdMarkLoc(String idMarkLoc) {
		this.idMarkLoc = idMarkLoc;
	}

}
