package com.ibm.wcm.ods.vo;
// Generated May 31, 2018 4:53:55 PM by Hibernate Tools 5.2.6.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CpHlthInsSrc generated by hbm2java
 */
import com.ibm.gbs.util.Constant; 
//  @Entity
//  @Table(schema = Constant.SCHEMANAME_ODS , name = "CP_HLTH_INS_SRC")
public class CpHlthInsSrcVo  {   // implements  java.io.Serializable {

	private BigDecimal cpHlthInsSeqNum;
	private ClientProfileHlthSrcVo clientProfileHlthSrc;
	private String guarantorInsPayor;
	private Date episCareDate;
	private String insProvider;
	private String insType;
	private String guarantor;

	public CpHlthInsSrcVo() {
	}

	public CpHlthInsSrcVo(BigDecimal cpHlthInsSeqNum, ClientProfileHlthSrcVo clientProfileHlthSrc) {
		this.cpHlthInsSeqNum = cpHlthInsSeqNum;
		this.clientProfileHlthSrc = clientProfileHlthSrc;
	}

	public CpHlthInsSrcVo(BigDecimal cpHlthInsSeqNum, ClientProfileHlthSrcVo clientProfileHlthSrc, String guarantorInsPayor,
			Date episCareDate, String insProvider, String insType, String guarantor) {
		this.cpHlthInsSeqNum = cpHlthInsSeqNum;
		this.clientProfileHlthSrc = clientProfileHlthSrc;
		this.guarantorInsPayor = guarantorInsPayor;
		this.episCareDate = episCareDate;
		this.insProvider = insProvider;
		this.insType = insType;
		this.guarantor = guarantor;
	}

	//  @Id

	//  @Column(name = "CP_HLTH_INS_SEQ_NUM", unique = true, nullable = false, precision = 31, scale = 0)
	public BigDecimal getCpHlthInsSeqNum() {
		return this.cpHlthInsSeqNum;
	}

	public void setCpHlthInsSeqNum(BigDecimal cpHlthInsSeqNum) {
		this.cpHlthInsSeqNum = cpHlthInsSeqNum;
	}

	//  @ManyToOne(fetch = FetchType.LAZY)
	//  @JoinColumn(name = "CLIENT_PROFILE_HLTH_SEQ_NUM", nullable = false)
	public ClientProfileHlthSrcVo getClientProfileHlthSrc() {
		return this.clientProfileHlthSrc;
	}

	public void setClientProfileHlthSrc(ClientProfileHlthSrcVo clientProfileHlthSrc) {
		this.clientProfileHlthSrc = clientProfileHlthSrc;
	}

	//  @Column(name = "GUARANTOR_INS_PAYOR", length = 512)
	public String getGuarantorInsPayor() {
		return this.guarantorInsPayor;
	}

	public void setGuarantorInsPayor(String guarantorInsPayor) {
		this.guarantorInsPayor = guarantorInsPayor;
	}

	//  @Temporal(TemporalType.DATE)
	//  @Column(name = "EPIS_CARE_DATE", length = 10)
	public Date getEpisCareDate() {
		return this.episCareDate;
	}

	public void setEpisCareDate(Date episCareDate) {
		this.episCareDate = episCareDate;
	}

	//  @Column(name = "INS_PROVIDER", length = 100)
	public String getInsProvider() {
		return this.insProvider;
	}

	public void setInsProvider(String insProvider) {
		this.insProvider = insProvider;
	}

	//  @Column(name = "INS_TYPE", length = 100)
	public String getInsType() {
		return this.insType;
	}

	public void setInsType(String insType) {
		this.insType = insType;
	}

	//  @Column(name = "GUARANTOR", length = 40)
	public String getGuarantor() {
		return this.guarantor;
	}

	public void setGuarantor(String guarantor) {
		this.guarantor = guarantor;
	}

}
