package com.ibm.wcm.ods.vo;
// Generated May 31, 2018 4:53:55 PM by Hibernate Tools 5.2.6.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CpHlthMedImmunSrc generated by hbm2java
 */
import com.ibm.gbs.util.Constant; 
//  @Entity
//  @Table(schema = Constant.SCHEMANAME_ODS , name = "CP_HLTH_MED_IMMUN_SRC")
public class CpHlthMedImmunSrc  {   // implements  java.io.Serializable {

	private BigDecimal cpHlthMedImmunSeqNum;
	private ClientProfileHlthSrcVo clientProfileHlthSrc;
	private String immunization;
	private Date serviceDate;

	public CpHlthMedImmunSrc() {
	}

	public CpHlthMedImmunSrc(BigDecimal cpHlthMedImmunSeqNum, ClientProfileHlthSrcVo clientProfileHlthSrc) {
		this.cpHlthMedImmunSeqNum = cpHlthMedImmunSeqNum;
		this.clientProfileHlthSrc = clientProfileHlthSrc;
	}

	public CpHlthMedImmunSrc(BigDecimal cpHlthMedImmunSeqNum, ClientProfileHlthSrcVo clientProfileHlthSrc,
			String immunization, Date serviceDate) {
		this.cpHlthMedImmunSeqNum = cpHlthMedImmunSeqNum;
		this.clientProfileHlthSrc = clientProfileHlthSrc;
		this.immunization = immunization;
		this.serviceDate = serviceDate;
	}

	//  @Id

	//  @Column(name = "CP_HLTH_MED_IMMUN_SEQ_NUM", unique = true, nullable = false, precision = 31, scale = 0)
	public BigDecimal getCpHlthMedImmunSeqNum() {
		return this.cpHlthMedImmunSeqNum;
	}

	public void setCpHlthMedImmunSeqNum(BigDecimal cpHlthMedImmunSeqNum) {
		this.cpHlthMedImmunSeqNum = cpHlthMedImmunSeqNum;
	}

	//  @ManyToOne(fetch = FetchType.LAZY)
	//  @JoinColumn(name = "CLIENT_PROFILE_HLTH_SEQ_NUM", nullable = false)
	public ClientProfileHlthSrcVo getClientProfileHlthSrc() {
		return this.clientProfileHlthSrc;
	}

	public void setClientProfileHlthSrc(ClientProfileHlthSrcVo clientProfileHlthSrc) {
		this.clientProfileHlthSrc = clientProfileHlthSrc;
	}

	//  @Column(name = "IMMUNIZATION", length = 65)
	public String getImmunization() {
		return this.immunization;
	}

	public void setImmunization(String immunization) {
		this.immunization = immunization;
	}

	//  @Temporal(TemporalType.DATE)
	//  @Column(name = "SERVICE_DATE", length = 10)
	public Date getServiceDate() {
		return this.serviceDate;
	}

	public void setServiceDate(Date serviceDate) {
		this.serviceDate = serviceDate;
	}

}
