package com.ibm.wcm.ods.vo;
// Generated May 31, 2018 4:53:55 PM by Hibernate Tools 5.2.6.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CpMhsInfoSrc generated by hbm2java
 */
import com.ibm.gbs.util.Constant; 
//  @Entity
//  @Table(schema = Constant.SCHEMANAME_ODS , name = "CP_MHS_INFO_SRC")
public class CpMhsInfoSrc  {   // implements  java.io.Serializable {

	private BigDecimal cpMhsInfoSeqNum;
	private ClientProfileMhsSrcVo clientProfileMhsSrc;
	private String mentalHealthConcern;

	public CpMhsInfoSrc() {
	}

	public CpMhsInfoSrc(BigDecimal cpMhsInfoSeqNum, ClientProfileMhsSrcVo clientProfileMhsSrc) {
		this.cpMhsInfoSeqNum = cpMhsInfoSeqNum;
		this.clientProfileMhsSrc = clientProfileMhsSrc;
	}

	public CpMhsInfoSrc(BigDecimal cpMhsInfoSeqNum, ClientProfileMhsSrcVo clientProfileMhsSrc,
			String mentalHealthConcern) {
		this.cpMhsInfoSeqNum = cpMhsInfoSeqNum;
		this.clientProfileMhsSrc = clientProfileMhsSrc;
		this.mentalHealthConcern = mentalHealthConcern;
	}

	//  @Id

	//  @Column(name = "CP_MHS_INFO_SEQ_NUM", unique = true, nullable = false, precision = 31, scale = 0)
	public BigDecimal getCpMhsInfoSeqNum() {
		return this.cpMhsInfoSeqNum;
	}

	public void setCpMhsInfoSeqNum(BigDecimal cpMhsInfoSeqNum) {
		this.cpMhsInfoSeqNum = cpMhsInfoSeqNum;
	}

	//  @ManyToOne(fetch = FetchType.LAZY)
	//  @JoinColumn(name = "CLIENT_PROFILE_MHS_SEQ_NUM", nullable = false)
	public ClientProfileMhsSrcVo getClientProfileMhsSrc() {
		return this.clientProfileMhsSrc;
	}

	public void setClientProfileMhsSrc(ClientProfileMhsSrcVo clientProfileMhsSrc) {
		this.clientProfileMhsSrc = clientProfileMhsSrc;
	}

	//  @Column(name = "MENTAL_HEALTH_CONCERN", length = 35)
	public String getMentalHealthConcern() {
		return this.mentalHealthConcern;
	}

	public void setMentalHealthConcern(String mentalHealthConcern) {
		this.mentalHealthConcern = mentalHealthConcern;
	}

}
