package com.ibm.wcm.ods.vo;
// Generated May 31, 2018 4:53:55 PM by Hibernate Tools 5.2.6.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CpMhsEncounterSrc generated by hbm2java
 */
import com.ibm.gbs.util.Constant; 
//  @Entity
//  @Table(schema = Constant.SCHEMANAME_ODS , name = "CP_MHS_ENCOUNTER_SRC")
public class CpMhsEncounterSrcVo  {   // implements  java.io.Serializable {

	private BigDecimal cpMhsEncounterSeqNum;
	private ClientProfileMhsSrcVo clientProfileMhsSrc;
	private Date serviceDate;
	private String serviceType;
	private String mhsProvider;
	private String providerContact;
	private String diagnosis;
	private Date diagnosisActiveDate;
	private Date diagnosisInactiveDate;

	public CpMhsEncounterSrcVo() {
	}

	public CpMhsEncounterSrcVo(BigDecimal cpMhsEncounterSeqNum, ClientProfileMhsSrcVo clientProfileMhsSrc) {
		this.cpMhsEncounterSeqNum = cpMhsEncounterSeqNum;
		this.clientProfileMhsSrc = clientProfileMhsSrc;
	}

	public CpMhsEncounterSrcVo(BigDecimal cpMhsEncounterSeqNum, ClientProfileMhsSrcVo clientProfileMhsSrc, Date serviceDate,
			String serviceType, String mhsProvider, String providerContact, String diagnosis, Date diagnosisActiveDate,
			Date diagnosisInactiveDate) {
		this.cpMhsEncounterSeqNum = cpMhsEncounterSeqNum;
		this.clientProfileMhsSrc = clientProfileMhsSrc;
		this.serviceDate = serviceDate;
		this.serviceType = serviceType;
		this.mhsProvider = mhsProvider;
		this.providerContact = providerContact;
		this.diagnosis = diagnosis;
		this.diagnosisActiveDate = diagnosisActiveDate;
		this.diagnosisInactiveDate = diagnosisInactiveDate;
	}

	//  @Id

	//  @Column(name = "CP_MHS_ENCOUNTER_SEQ_NUM", unique = true, nullable = false, precision = 31, scale = 0)
	public BigDecimal getCpMhsEncounterSeqNum() {
		return this.cpMhsEncounterSeqNum;
	}

	public void setCpMhsEncounterSeqNum(BigDecimal cpMhsEncounterSeqNum) {
		this.cpMhsEncounterSeqNum = cpMhsEncounterSeqNum;
	}

	//  @ManyToOne(fetch = FetchType.LAZY)
	//  @JoinColumn(name = "CLIENT_PROFILE_MHS_SEQ_NUM", nullable = false)
	public ClientProfileMhsSrcVo getClientProfileMhsSrc() {
		return this.clientProfileMhsSrc;
	}

	public void setClientProfileMhsSrc(ClientProfileMhsSrcVo clientProfileMhsSrc) {
		this.clientProfileMhsSrc = clientProfileMhsSrc;
	}

	//  @Temporal(TemporalType.DATE)
	//  @Column(name = "SERVICE_DATE", length = 10)
	public Date getServiceDate() {
		return this.serviceDate;
	}

	public void setServiceDate(Date serviceDate) {
		this.serviceDate = serviceDate;
	}

	//  @Column(name = "SERVICE_TYPE", length = 6)
	public String getServiceType() {
		return this.serviceType;
	}

	public void setServiceType(String serviceType) {
		this.serviceType = serviceType;
	}

	//  @Column(name = "MHS_PROVIDER", length = 60)
	public String getMhsProvider() {
		return this.mhsProvider;
	}

	public void setMhsProvider(String mhsProvider) {
		this.mhsProvider = mhsProvider;
	}

	//  @Column(name = "PROVIDER_CONTACT", length = 60)
	public String getProviderContact() {
		return this.providerContact;
	}

	public void setProviderContact(String providerContact) {
		this.providerContact = providerContact;
	}

	//  @Column(name = "DIAGNOSIS", length = 60)
	public String getDiagnosis() {
		return this.diagnosis;
	}

	public void setDiagnosis(String diagnosis) {
		this.diagnosis = diagnosis;
	}

	//  @Temporal(TemporalType.DATE)
	//  @Column(name = "DIAGNOSIS_ACTIVE_DATE", length = 10)
	public Date getDiagnosisActiveDate() {
		return this.diagnosisActiveDate;
	}

	public void setDiagnosisActiveDate(Date diagnosisActiveDate) {
		this.diagnosisActiveDate = diagnosisActiveDate;
	}

	//  @Temporal(TemporalType.DATE)
	//  @Column(name = "DIAGNOSIS_INACTIVE_DATE", length = 10)
	public Date getDiagnosisInactiveDate() {
		return this.diagnosisInactiveDate;
	}

	public void setDiagnosisInactiveDate(Date diagnosisInactiveDate) {
		this.diagnosisInactiveDate = diagnosisInactiveDate;
	}

}
