package com.ibm.wcm.ods.vo;
// Generated May 31, 2018 4:53:55 PM by Hibernate Tools 5.2.6.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InitloadClientProgramSrc generated by hbm2java
 */
import com.ibm.gbs.util.Constant; 
//  @Entity
//  @Table(schema = Constant.SCHEMANAME_ODS , name = "INITLOAD_CLIENT_PROGRAM_SRC")
public class InitloadClientProgramSrc  {   // implements  java.io.Serializable {

	private BigDecimal clientProgSeqNum;
	private InitloadClientSrc initloadClientSrc;
	private String programId;
	private Date progStartDate;
	private String programName;
	private String participationType;
	private String privilegedRecord;
	private Date progEndDate;
	private String programStatus;
	private String caseId;

	public InitloadClientProgramSrc() {
	}

	public InitloadClientProgramSrc(BigDecimal clientProgSeqNum, InitloadClientSrc initloadClientSrc, String programId,
			Date progStartDate, String programName, String participationType) {
		this.clientProgSeqNum = clientProgSeqNum;
		this.initloadClientSrc = initloadClientSrc;
		this.programId = programId;
		this.progStartDate = progStartDate;
		this.programName = programName;
		this.participationType = participationType;
	}

	public InitloadClientProgramSrc(BigDecimal clientProgSeqNum, InitloadClientSrc initloadClientSrc, String programId,
			Date progStartDate, String programName, String participationType, String privilegedRecord, Date progEndDate,
			String programStatus, String caseId) {
		this.clientProgSeqNum = clientProgSeqNum;
		this.initloadClientSrc = initloadClientSrc;
		this.programId = programId;
		this.progStartDate = progStartDate;
		this.programName = programName;
		this.participationType = participationType;
		this.privilegedRecord = privilegedRecord;
		this.progEndDate = progEndDate;
		this.programStatus = programStatus;
		this.caseId = caseId;
	}

	//  @Id

	//  @Column(name = "CLIENT_PROG_SEQ_NUM", unique = true, nullable = false, precision = 31, scale = 0)
	public BigDecimal getClientProgSeqNum() {
		return this.clientProgSeqNum;
	}

	public void setClientProgSeqNum(BigDecimal clientProgSeqNum) {
		this.clientProgSeqNum = clientProgSeqNum;
	}

	//  @ManyToOne(fetch = FetchType.LAZY)
	//  @JoinColumn(name = "CLIENT_TRANSACTION_SEQ_NUM", nullable = false)
	public InitloadClientSrc getInitloadClientSrc() {
		return this.initloadClientSrc;
	}

	public void setInitloadClientSrc(InitloadClientSrc initloadClientSrc) {
		this.initloadClientSrc = initloadClientSrc;
	}

	//  @Column(name = "PROGRAM_ID", nullable = false, length = 60)
	public String getProgramId() {
		return this.programId;
	}

	public void setProgramId(String programId) {
		this.programId = programId;
	}

	//  @Temporal(TemporalType.DATE)
	//  @Column(name = "PROG_START_DATE", nullable = false, length = 10)
	public Date getProgStartDate() {
		return this.progStartDate;
	}

	public void setProgStartDate(Date progStartDate) {
		this.progStartDate = progStartDate;
	}

	//  @Column(name = "PROGRAM_NAME", nullable = false, length = 256)
	public String getProgramName() {
		return this.programName;
	}

	public void setProgramName(String programName) {
		this.programName = programName;
	}

	//  @Column(name = "PARTICIPATION_TYPE", nullable = false, length = 60)
	public String getParticipationType() {
		return this.participationType;
	}

	public void setParticipationType(String participationType) {
		this.participationType = participationType;
	}

	//  @Column(name = "PRIVILEGED_RECORD", length = 20)
	public String getPrivilegedRecord() {
		return this.privilegedRecord;
	}

	public void setPrivilegedRecord(String privilegedRecord) {
		this.privilegedRecord = privilegedRecord;
	}

	//  @Temporal(TemporalType.DATE)
	//  @Column(name = "PROG_END_DATE", length = 10)
	public Date getProgEndDate() {
		return this.progEndDate;
	}

	public void setProgEndDate(Date progEndDate) {
		this.progEndDate = progEndDate;
	}

	//  @Column(name = "PROGRAM_STATUS", length = 256)
	public String getProgramStatus() {
		return this.programStatus;
	}

	public void setProgramStatus(String programStatus) {
		this.programStatus = programStatus;
	}

	//  @Column(name = "CASE_ID", length = 60)
	public String getCaseId() {
		return this.caseId;
	}

	public void setCaseId(String caseId) {
		this.caseId = caseId;
	}

}
