
package com.initiate.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
//http://client.initiate.com/
//http://client.esoa.mdm.ibm.com/
@WebService(name = "MasterDataWebService", targetNamespace = "http://client.esoa.mdm.ibm.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MasterDataWebService {


    /**
     * 
     * @param mode
     * @param createUpdateOptions
     * @param bean
     * @return
     *     returns com.initiate.client.Client
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "Client", targetNamespace = "")
    @RequestWrapper(localName = "updateClientWithOptions", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.UpdateClientWithOptions")
    @ResponseWrapper(localName = "updateClientWithOptionsResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.UpdateClientWithOptionsResponse")
    public Client updateClientWithOptions(
        @WebParam(name = "bean", targetNamespace = "")
        Client bean,
        @WebParam(name = "mode", targetNamespace = "")
        UpdateMode mode,
        @WebParam(name = "createUpdateOptions", targetNamespace = "")
        CreateUpdateOptions createUpdateOptions)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param beanId
     * @return
     *     returns boolean
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "dropProvider", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.DropProvider")
    @ResponseWrapper(localName = "dropProviderResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.DropProviderResponse")
    public boolean dropProvider(
        @WebParam(name = "beanId", targetNamespace = "")
        ProviderId beanId)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param updateEntityType
     * @param updateMode
     * @param createUpdateOptions
     * @param modifySource
     * @param bean
     * @return
     *     returns com.initiate.client.Client
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateIdEntityWithOptions", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.UpdateIdEntityWithOptions")
    @ResponseWrapper(localName = "updateIdEntityWithOptionsResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.UpdateIdEntityWithOptionsResponse")
    public Client updateIdEntityWithOptions(
        @WebParam(name = "bean", targetNamespace = "")
        IdEntity bean,
        @WebParam(name = "modifySource", targetNamespace = "")
        String modifySource,
        @WebParam(name = "updateEntityType", targetNamespace = "")
        UpdateEntityType updateEntityType,
        @WebParam(name = "updateMode", targetNamespace = "")
        UpdateMode updateMode,
        @WebParam(name = "createUpdateOptions", targetNamespace = "")
        CreateUpdateOptions createUpdateOptions)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param mode
     * @param updateMode
     * @param modifySource
     * @param bean
     * @return
     *     returns com.initiate.client.Provider
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateProvEntity", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.UpdateProvEntity")
    @ResponseWrapper(localName = "updateProvEntityResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.UpdateProvEntityResponse")
    public Provider updateProvEntity(
        @WebParam(name = "bean", targetNamespace = "")
        ProvEntity bean,
        @WebParam(name = "modifySource", targetNamespace = "")
        String modifySource,
        @WebParam(name = "mode", targetNamespace = "")
        UpdateEntityType mode,
        @WebParam(name = "updateMode", targetNamespace = "")
        UpdateMode updateMode)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param recordId
     * @return
     *     returns boolean
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "unmergeClient", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.UnmergeClient")
    @ResponseWrapper(localName = "unmergeClientResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.UnmergeClientResponse")
    public boolean unmergeClient(
        @WebParam(name = "recordId", targetNamespace = "")
        List<ClientId> recordId)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param mode
     * @param defaultWinner
     * @param bean
     * @return
     *     returns java.util.List<com.initiate.client.Provider>
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "Provider", targetNamespace = "")
    @RequestWrapper(localName = "updateQualifiedProv", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.UpdateQualifiedProv")
    @ResponseWrapper(localName = "updateQualifiedProvResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.UpdateQualifiedProvResponse")
    public List<Provider> updateQualifiedProv(
        @WebParam(name = "bean", targetNamespace = "")
        Provider bean,
        @WebParam(name = "mode", targetNamespace = "")
        UpdateMode mode,
        @WebParam(name = "defaultWinner", targetNamespace = "")
        boolean defaultWinner)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param beanId
     * @return
     *     returns boolean
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteProvider", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.DeleteProvider")
    @ResponseWrapper(localName = "deleteProviderResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.DeleteProviderResponse")
    public boolean deleteProvider(
        @WebParam(name = "beanId", targetNamespace = "")
        ProviderId beanId)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param brief
     * @param memStatFilter
     * @param maxResults
     * @param query
     * @param recStatFilter
     * @param cvwName
     * @param source
     * @param attribute
     * @return
     *     returns java.util.List<com.initiate.client.IdEntitySearchResult>
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "IdEntitySearchResult", targetNamespace = "")
    @RequestWrapper(localName = "textSearchForIdList", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.TextSearchForIdList")
    @ResponseWrapper(localName = "textSearchForIdListResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.TextSearchForIdListResponse")
    public List<IdEntitySearchResult> textSearchForIdList(
        @WebParam(name = "query", targetNamespace = "")
        String query,
        @WebParam(name = "maxResults", targetNamespace = "")
        int maxResults,
        @WebParam(name = "cvwName", targetNamespace = "")
        String cvwName,
        @WebParam(name = "source", targetNamespace = "")
        List<ClientSource> source,
        @WebParam(name = "attribute", targetNamespace = "")
        List<ClientAttribute> attribute,
        @WebParam(name = "memStatFilter", targetNamespace = "")
        String memStatFilter,
        @WebParam(name = "recStatFilter", targetNamespace = "")
        String recStatFilter,
        @WebParam(name = "brief", targetNamespace = "")
        boolean brief)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param recordId
     * @param entityIdId
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "linkClientToIdEntity", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.LinkClientToIdEntity")
    @ResponseWrapper(localName = "linkClientToIdEntityResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.LinkClientToIdEntityResponse")
    public void linkClientToIdEntity(
        @WebParam(name = "recordId", targetNamespace = "")
        ClientId recordId,
        @WebParam(name = "entityIdId", targetNamespace = "")
        IdEntityId entityIdId)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param record
     * @param target
     * @return
     *     returns java.util.List<java.lang.Short>
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "scoreProviderAsProv", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.ScoreProviderAsProv")
    @ResponseWrapper(localName = "scoreProviderAsProvResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.ScoreProviderAsProvResponse")
    public List<Short> scoreProviderAsProv(
        @WebParam(name = "target", targetNamespace = "")
        Provider target,
        @WebParam(name = "record", targetNamespace = "")
        List<Provider> record)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param recordId
     * @param entityIdId
     * @return
     *     returns com.initiate.client.ProviderTaskId
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "ProviderTaskId", targetNamespace = "")
    @RequestWrapper(localName = "markProvEntityLink", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.MarkProvEntityLink")
    @ResponseWrapper(localName = "markProvEntityLinkResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.MarkProvEntityLinkResponse")
    public ProviderTaskId markProvEntityLink(
        @WebParam(name = "recordId", targetNamespace = "")
        ProviderId recordId,
        @WebParam(name = "entityIdId", targetNamespace = "")
        ProvEntityId entityIdId)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param maxResults
     * @param credentialIds
     * @param attributes
     * @return
     *     returns java.util.List<com.initiate.client.ClientTask>
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "ClientTask", targetNamespace = "")
    @RequestWrapper(localName = "searchForClientTaskByCredentialIds", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.SearchForClientTaskByCredentialIds")
    @ResponseWrapper(localName = "searchForClientTaskByCredentialIdsResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.SearchForClientTaskByCredentialIdsResponse")
    public List<ClientTask> searchForClientTaskByCredentialIds(
        @WebParam(name = "credentialIds", targetNamespace = "")
        List<CredentialId> credentialIds,
        @WebParam(name = "maxResults", targetNamespace = "")
        int maxResults,
        @WebParam(name = "attributes", targetNamespace = "")
        List<ClientAttribute> attributes)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param cvwName
     * @param id
     * @param source
     * @param attribute
     * @return
     *     returns java.util.List<com.initiate.client.Provider>
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "Provider", targetNamespace = "")
    @RequestWrapper(localName = "getProviderList", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.GetProviderList")
    @ResponseWrapper(localName = "getProviderListResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.GetProviderListResponse")
    public List<Provider> getProviderList(
        @WebParam(name = "id", targetNamespace = "")
        List<ProviderId> id,
        @WebParam(name = "cvwName", targetNamespace = "")
        String cvwName,
        @WebParam(name = "source", targetNamespace = "")
        List<ProviderSource> source,
        @WebParam(name = "attribute", targetNamespace = "")
        List<ProviderAttribute> attribute)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param id2
     * @param id1
     * @return
     *     returns short
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "compareProviderAsProv", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.CompareProviderAsProv")
    @ResponseWrapper(localName = "compareProviderAsProvResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.CompareProviderAsProvResponse")
    public short compareProviderAsProv(
        @WebParam(name = "id1", targetNamespace = "")
        ProviderId id1,
        @WebParam(name = "id2", targetNamespace = "")
        ProviderId id2)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param mode
     * @param bean
     * @return
     *     returns com.initiate.client.Provider
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "Provider", targetNamespace = "")
    @RequestWrapper(localName = "createOrUpdateProvider", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.CreateOrUpdateProvider")
    @ResponseWrapper(localName = "createOrUpdateProviderResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.CreateOrUpdateProviderResponse")
    public Provider createOrUpdateProvider(
        @WebParam(name = "bean", targetNamespace = "")
        Provider bean,
        @WebParam(name = "mode", targetNamespace = "")
        UpdateMode mode)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param obsoleteId
     * @param survivorId
     * @return
     *     returns boolean
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "mergeClient", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.MergeClient")
    @ResponseWrapper(localName = "mergeClientResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.MergeClientResponse")
    public boolean mergeClient(
        @WebParam(name = "survivorId", targetNamespace = "")
        ClientId survivorId,
        @WebParam(name = "obsoleteId", targetNamespace = "")
        ClientId obsoleteId)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param beanId
     * @return
     *     returns boolean
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "undeleteClient", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.UndeleteClient")
    @ResponseWrapper(localName = "undeleteClientResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.UndeleteClientResponse")
    public boolean undeleteClient(
        @WebParam(name = "beanId", targetNamespace = "")
        ClientId beanId)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param minScore
     * @param maxResults
     * @param cvwName
     * @param source
     * @param attribute
     * @param bean
     * @return
     *     returns java.util.List<com.initiate.client.ProvEntitySearchResult>
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "ProvEntitySearchResult", targetNamespace = "")
    @RequestWrapper(localName = "searchForProvList", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.SearchForProvList")
    @ResponseWrapper(localName = "searchForProvListResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.SearchForProvListResponse")
    public List<ProvEntitySearchResult> searchForProvList(
        @WebParam(name = "bean", targetNamespace = "")
        Provider bean,
        @WebParam(name = "minScore", targetNamespace = "")
        short minScore,
        @WebParam(name = "maxResults", targetNamespace = "")
        int maxResults,
        @WebParam(name = "cvwName", targetNamespace = "")
        String cvwName,
        @WebParam(name = "source", targetNamespace = "")
        List<ProviderSource> source,
        @WebParam(name = "attribute", targetNamespace = "")
        List<ProviderAttribute> attribute)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param attributes
     * @param taskId
     * @return
     *     returns com.initiate.client.ClientTask
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "ClientTask", targetNamespace = "")
    @RequestWrapper(localName = "getClientTask", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.GetClientTask")
    @ResponseWrapper(localName = "getClientTaskResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.GetClientTaskResponse")
    public ClientTask getClientTask(
        @WebParam(name = "taskId", targetNamespace = "")
        ClientTaskId taskId,
        @WebParam(name = "attributes", targetNamespace = "")
        List<ClientAttribute> attributes)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param recordId
     * @param entityIdId
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "linkProviderToProvEntity", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.LinkProviderToProvEntity")
    @ResponseWrapper(localName = "linkProviderToProvEntityResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.LinkProviderToProvEntityResponse")
    public void linkProviderToProvEntity(
        @WebParam(name = "recordId", targetNamespace = "")
        ProviderId recordId,
        @WebParam(name = "entityIdId", targetNamespace = "")
        ProvEntityId entityIdId)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param mode
     * @param bean
     * @return
     *     returns com.initiate.client.Provider
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "Provider", targetNamespace = "")
    @RequestWrapper(localName = "createProvider", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.CreateProvider")
    @ResponseWrapper(localName = "createProviderResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.CreateProviderResponse")
    public Provider createProvider(
        @WebParam(name = "bean", targetNamespace = "")
        Provider bean,
        @WebParam(name = "mode", targetNamespace = "")
        UpdateMode mode)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param mode
     * @param createUpdateOptions
     * @param bean
     * @return
     *     returns com.initiate.client.Provider
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "Provider", targetNamespace = "")
    @RequestWrapper(localName = "createOrUpdateProviderWithOptions", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.CreateOrUpdateProviderWithOptions")
    @ResponseWrapper(localName = "createOrUpdateProviderWithOptionsResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.CreateOrUpdateProviderWithOptionsResponse")
    public Provider createOrUpdateProviderWithOptions(
        @WebParam(name = "bean", targetNamespace = "")
        Provider bean,
        @WebParam(name = "mode", targetNamespace = "")
        UpdateMode mode,
        @WebParam(name = "createUpdateOptions", targetNamespace = "")
        CreateUpdateOptions createUpdateOptions)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param record
     * @param target
     * @return
     *     returns java.util.List<java.lang.Short>
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "scoreClientAsId", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.ScoreClientAsId")
    @ResponseWrapper(localName = "scoreClientAsIdResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.ScoreClientAsIdResponse")
    public List<Short> scoreClientAsId(
        @WebParam(name = "target", targetNamespace = "")
        Client target,
        @WebParam(name = "record", targetNamespace = "")
        List<Client> record)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param mode
     * @param updateMode
     * @param modifySource
     * @param bean
     * @return
     *     returns com.initiate.client.Client
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateIdEntity", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.UpdateIdEntity")
    @ResponseWrapper(localName = "updateIdEntityResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.UpdateIdEntityResponse")
    public Client updateIdEntity(
        @WebParam(name = "bean", targetNamespace = "")
        IdEntity bean,
        @WebParam(name = "modifySource", targetNamespace = "")
        String modifySource,
        @WebParam(name = "mode", targetNamespace = "")
        UpdateEntityType mode,
        @WebParam(name = "updateMode", targetNamespace = "")
        UpdateMode updateMode)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param mode
     * @param bean
     * @return
     *     returns com.initiate.client.Client
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "Client", targetNamespace = "")
    @RequestWrapper(localName = "createOrUpdateClient", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.CreateOrUpdateClient")
    @ResponseWrapper(localName = "createOrUpdateClientResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.CreateOrUpdateClientResponse")
    public Client createOrUpdateClient(
        @WebParam(name = "bean", targetNamespace = "")
        Client bean,
        @WebParam(name = "mode", targetNamespace = "")
        UpdateMode mode)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param recordId
     * @param taskType
     * @param description
     * @return
     *     returns com.initiate.client.ProviderTaskId
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "ProviderTaskId", targetNamespace = "")
    @RequestWrapper(localName = "createCustomProviderTask", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.CreateCustomProviderTask")
    @ResponseWrapper(localName = "createCustomProviderTaskResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.CreateCustomProviderTaskResponse")
    public ProviderTaskId createCustomProviderTask(
        @WebParam(name = "recordId", targetNamespace = "")
        ProviderId recordId,
        @WebParam(name = "taskType", targetNamespace = "")
        String taskType,
        @WebParam(name = "description", targetNamespace = "")
        String description)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param credentialId
     * @param taskId
     * @param status
     * @return
     *     returns java.util.List<com.initiate.client.ClientTask>
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "ClientTask", targetNamespace = "")
    @RequestWrapper(localName = "updateClientTask", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.UpdateClientTask")
    @ResponseWrapper(localName = "updateClientTaskResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.UpdateClientTaskResponse")
    public List<ClientTask> updateClientTask(
        @WebParam(name = "taskId", targetNamespace = "")
        ClientTaskId taskId,
        @WebParam(name = "status", targetNamespace = "")
        String status,
        @WebParam(name = "credentialId", targetNamespace = "")
        CredentialId credentialId)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param minScore
     * @param maxResults
     * @param cvwName
     * @param source
     * @param attribute
     * @param bean
     * @return
     *     returns java.util.List<com.initiate.client.ProviderSearchResult>
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "ProviderSearchResult", targetNamespace = "")
    @RequestWrapper(localName = "searchProviderListAsProv", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.SearchProviderListAsProv")
    @ResponseWrapper(localName = "searchProviderListAsProvResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.SearchProviderListAsProvResponse")
    public List<ProviderSearchResult> searchProviderListAsProv(
        @WebParam(name = "bean", targetNamespace = "")
        Provider bean,
        @WebParam(name = "minScore", targetNamespace = "")
        short minScore,
        @WebParam(name = "maxResults", targetNamespace = "")
        int maxResults,
        @WebParam(name = "cvwName", targetNamespace = "")
        String cvwName,
        @WebParam(name = "source", targetNamespace = "")
        List<ProviderSource> source,
        @WebParam(name = "attribute", targetNamespace = "")
        List<ProviderAttribute> attribute)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param mode
     * @param createUpdateOptions
     * @param bean
     * @return
     *     returns com.initiate.client.Provider
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "Provider", targetNamespace = "")
    @RequestWrapper(localName = "updateProviderWithOptions", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.UpdateProviderWithOptions")
    @ResponseWrapper(localName = "updateProviderWithOptionsResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.UpdateProviderWithOptionsResponse")
    public Provider updateProviderWithOptions(
        @WebParam(name = "bean", targetNamespace = "")
        Provider bean,
        @WebParam(name = "mode", targetNamespace = "")
        UpdateMode mode,
        @WebParam(name = "createUpdateOptions", targetNamespace = "")
        CreateUpdateOptions createUpdateOptions)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param mode
     * @param bean
     * @return
     *     returns com.initiate.client.Provider
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "Provider", targetNamespace = "")
    @RequestWrapper(localName = "updateProvider", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.UpdateProvider")
    @ResponseWrapper(localName = "updateProviderResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.UpdateProviderResponse")
    public Provider updateProvider(
        @WebParam(name = "bean", targetNamespace = "")
        Provider bean,
        @WebParam(name = "mode", targetNamespace = "")
        UpdateMode mode)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param minScore
     * @param maxResults
     * @param cvwName
     * @param source
     * @param attribute
     * @param bean
     * @return
     *     returns java.util.List<com.initiate.client.IdEntitySearchResult>
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "IdEntitySearchResult", targetNamespace = "")
    @RequestWrapper(localName = "searchForIdList", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.SearchForIdList")
    @ResponseWrapper(localName = "searchForIdListResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.SearchForIdListResponse")
    public List<IdEntitySearchResult> searchForIdList(
        @WebParam(name = "bean", targetNamespace = "")
        Client bean,
        @WebParam(name = "minScore", targetNamespace = "")
        short minScore,
        @WebParam(name = "maxResults", targetNamespace = "")
        int maxResults,
        @WebParam(name = "cvwName", targetNamespace = "")
        String cvwName,
        @WebParam(name = "source", targetNamespace = "")
        List<ClientSource> source,
        @WebParam(name = "attribute", targetNamespace = "")
        List<ClientAttribute> attribute)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param brief
     * @param memStatFilter
     * @param maxResults
     * @param query
     * @param recStatFilter
     * @param cvwName
     * @param source
     * @param attribute
     * @return
     *     returns java.util.List<com.initiate.client.ProvEntitySearchResult>
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "ProvEntitySearchResult", targetNamespace = "")
    @RequestWrapper(localName = "textSearchForProvList", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.TextSearchForProvList")
    @ResponseWrapper(localName = "textSearchForProvListResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.TextSearchForProvListResponse")
    public List<ProvEntitySearchResult> textSearchForProvList(
        @WebParam(name = "query", targetNamespace = "")
        String query,
        @WebParam(name = "maxResults", targetNamespace = "")
        int maxResults,
        @WebParam(name = "cvwName", targetNamespace = "")
        String cvwName,
        @WebParam(name = "source", targetNamespace = "")
        List<ProviderSource> source,
        @WebParam(name = "attribute", targetNamespace = "")
        List<ProviderAttribute> attribute,
        @WebParam(name = "memStatFilter", targetNamespace = "")
        String memStatFilter,
        @WebParam(name = "recStatFilter", targetNamespace = "")
        String recStatFilter,
        @WebParam(name = "brief", targetNamespace = "")
        boolean brief)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param auditData
     * @return
     *     returns boolean
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "undoClientRecordOperation", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.UndoClientRecordOperation")
    @ResponseWrapper(localName = "undoClientRecordOperationResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.UndoClientRecordOperationResponse")
    public boolean undoClientRecordOperation(
        @WebParam(name = "auditData", targetNamespace = "")
        AuditData auditData)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param cvwName
     * @param id
     * @param source
     * @param attribute
     * @return
     *     returns java.util.List<com.initiate.client.ProvEntity>
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "ProvEntity", targetNamespace = "")
    @RequestWrapper(localName = "getProvEntityListByProvEntityIds", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.GetProvEntityListByProvEntityIds")
    @ResponseWrapper(localName = "getProvEntityListByProvEntityIdsResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.GetProvEntityListByProvEntityIdsResponse")
    public List<ProvEntity> getProvEntityListByProvEntityIds(
        @WebParam(name = "id", targetNamespace = "")
        List<ProvEntityId> id,
        @WebParam(name = "cvwName", targetNamespace = "")
        String cvwName,
        @WebParam(name = "source", targetNamespace = "")
        List<ProviderSource> source,
        @WebParam(name = "attribute", targetNamespace = "")
        List<ProviderAttribute> attribute)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param mode
     * @param defaultWinner
     * @param bean
     * @return
     *     returns java.util.List<com.initiate.client.Client>
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "Client", targetNamespace = "")
    @RequestWrapper(localName = "updateQualifiedId", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.UpdateQualifiedId")
    @ResponseWrapper(localName = "updateQualifiedIdResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.UpdateQualifiedIdResponse")
    public List<Client> updateQualifiedId(
        @WebParam(name = "bean", targetNamespace = "")
        Client bean,
        @WebParam(name = "mode", targetNamespace = "")
        UpdateMode mode,
        @WebParam(name = "defaultWinner", targetNamespace = "")
        boolean defaultWinner)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param brief
     * @param memStatFilter
     * @param maxResults
     * @param query
     * @param recStatFilter
     * @param cvwName
     * @param source
     * @param attribute
     * @return
     *     returns com.initiate.client.ClientTextSearchResult
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "ClientTextSearchResult", targetNamespace = "")
    @RequestWrapper(localName = "textSearchClientListAsId", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.TextSearchClientListAsId")
    @ResponseWrapper(localName = "textSearchClientListAsIdResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.TextSearchClientListAsIdResponse")
    public ClientTextSearchResult textSearchClientListAsId(
        @WebParam(name = "query", targetNamespace = "")
        String query,
        @WebParam(name = "maxResults", targetNamespace = "")
        int maxResults,
        @WebParam(name = "cvwName", targetNamespace = "")
        String cvwName,
        @WebParam(name = "source", targetNamespace = "")
        List<ClientSource> source,
        @WebParam(name = "attribute", targetNamespace = "")
        List<ClientAttribute> attribute,
        @WebParam(name = "memStatFilter", targetNamespace = "")
        String memStatFilter,
        @WebParam(name = "recStatFilter", targetNamespace = "")
        String recStatFilter,
        @WebParam(name = "brief", targetNamespace = "")
        boolean brief)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param mode
     * @param defaultWinner
     * @param createUpdateOptions
     * @param bean
     * @return
     *     returns java.util.List<com.initiate.client.Client>
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "Client", targetNamespace = "")
    @RequestWrapper(localName = "updateQualifiedIdWithOptions", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.UpdateQualifiedIdWithOptions")
    @ResponseWrapper(localName = "updateQualifiedIdWithOptionsResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.UpdateQualifiedIdWithOptionsResponse")
    public List<Client> updateQualifiedIdWithOptions(
        @WebParam(name = "bean", targetNamespace = "")
        Client bean,
        @WebParam(name = "mode", targetNamespace = "")
        UpdateMode mode,
        @WebParam(name = "defaultWinner", targetNamespace = "")
        boolean defaultWinner,
        @WebParam(name = "createUpdateOptions", targetNamespace = "")
        CreateUpdateOptions createUpdateOptions)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param mode
     * @param createUpdateOptions
     * @param bean
     * @return
     *     returns com.initiate.client.Provider
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "Provider", targetNamespace = "")
    @RequestWrapper(localName = "createProviderWithOptions", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.CreateProviderWithOptions")
    @ResponseWrapper(localName = "createProviderWithOptionsResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.CreateProviderWithOptionsResponse")
    public Provider createProviderWithOptions(
        @WebParam(name = "bean", targetNamespace = "")
        Provider bean,
        @WebParam(name = "mode", targetNamespace = "")
        UpdateMode mode,
        @WebParam(name = "createUpdateOptions", targetNamespace = "")
        CreateUpdateOptions createUpdateOptions)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param recordId
     * @return
     *     returns boolean
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "unmergeProvider", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.UnmergeProvider")
    @ResponseWrapper(localName = "unmergeProviderResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.UnmergeProviderResponse")
    public boolean unmergeProvider(
        @WebParam(name = "recordId", targetNamespace = "")
        List<ProviderId> recordId)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param cvwName
     * @param id
     * @param source
     * @param attribute
     * @return
     *     returns java.util.List<com.initiate.client.Client>
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "Client", targetNamespace = "")
    @RequestWrapper(localName = "getClientList", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.GetClientList")
    @ResponseWrapper(localName = "getClientListResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.GetClientListResponse")
    public List<Client> getClientList(
        @WebParam(name = "id", targetNamespace = "")
        List<ClientId> id,
        @WebParam(name = "cvwName", targetNamespace = "")
        String cvwName,
        @WebParam(name = "source", targetNamespace = "")
        List<ClientSource> source,
        @WebParam(name = "attribute", targetNamespace = "")
        List<ClientAttribute> attribute)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param fieldName
     * @param prefix
     * @param maxResults
     * @return
     *     returns java.util.List<com.initiate.client.TermSearchResult>
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "textSearchForTermList", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.TextSearchForTermList")
    @ResponseWrapper(localName = "textSearchForTermListResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.TextSearchForTermListResponse")
    public List<TermSearchResult> textSearchForTermList(
        @WebParam(name = "fieldName", targetNamespace = "")
        String fieldName,
        @WebParam(name = "prefix", targetNamespace = "")
        String prefix,
        @WebParam(name = "maxResults", targetNamespace = "")
        int maxResults)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param mode
     * @param createUpdateOptions
     * @param bean
     * @return
     *     returns com.initiate.client.Client
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "Client", targetNamespace = "")
    @RequestWrapper(localName = "createClientWithOptions", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.CreateClientWithOptions")
    @ResponseWrapper(localName = "createClientWithOptionsResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.CreateClientWithOptionsResponse")
    public Client createClientWithOptions(
        @WebParam(name = "bean", targetNamespace = "")
        Client bean,
        @WebParam(name = "mode", targetNamespace = "")
        UpdateMode mode,
        @WebParam(name = "createUpdateOptions", targetNamespace = "")
        CreateUpdateOptions createUpdateOptions)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param auditData
     * @return
     *     returns boolean
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "undoProviderRecordOperation", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.UndoProviderRecordOperation")
    @ResponseWrapper(localName = "undoProviderRecordOperationResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.UndoProviderRecordOperationResponse")
    public boolean undoProviderRecordOperation(
        @WebParam(name = "auditData", targetNamespace = "")
        AuditData auditData)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param attributes
     * @param taskId
     * @return
     *     returns com.initiate.client.IdEntityTask
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "IdEntityTask", targetNamespace = "")
    @RequestWrapper(localName = "getIdEntityTask", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.GetIdEntityTask")
    @ResponseWrapper(localName = "getIdEntityTaskResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.GetIdEntityTaskResponse")
    public IdEntityTask getIdEntityTask(
        @WebParam(name = "taskId", targetNamespace = "")
        ClientTaskId taskId,
        @WebParam(name = "attributes", targetNamespace = "")
        List<ClientAttribute> attributes)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param minScore
     * @param maxResults
     * @param cvwName
     * @param source
     * @param attribute
     * @param bean
     * @return
     *     returns java.util.List<com.initiate.client.ClientSearchResult>
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "ClientSearchResult", targetNamespace = "")
    @RequestWrapper(localName = "searchClientListAsId", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.SearchClientListAsId")
    @ResponseWrapper(localName = "searchClientListAsIdResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.SearchClientListAsIdResponse")
    public List<ClientSearchResult> searchClientListAsId(
        @WebParam(name = "bean", targetNamespace = "")
        Client bean,
        @WebParam(name = "minScore", targetNamespace = "")
        short minScore,
        @WebParam(name = "maxResults", targetNamespace = "")
        int maxResults,
        @WebParam(name = "cvwName", targetNamespace = "")
        String cvwName,
        @WebParam(name = "source", targetNamespace = "")
        List<ClientSource> source,
        @WebParam(name = "attribute", targetNamespace = "")
        List<ClientAttribute> attribute)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param attributes
     * @param recordIds
     * @return
     *     returns java.util.List<com.initiate.client.ProviderTask>
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "ProviderTask", targetNamespace = "")
    @RequestWrapper(localName = "searchForProviderTaskByProviderIds", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.SearchForProviderTaskByProviderIds")
    @ResponseWrapper(localName = "searchForProviderTaskByProviderIdsResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.SearchForProviderTaskByProviderIdsResponse")
    public List<ProviderTask> searchForProviderTaskByProviderIds(
        @WebParam(name = "recordIds", targetNamespace = "")
        List<ProviderId> recordIds,
        @WebParam(name = "attributes", targetNamespace = "")
        List<ProviderAttribute> attributes)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param beanId
     * @return
     *     returns boolean
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "dropClient", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.DropClient")
    @ResponseWrapper(localName = "dropClientResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.DropClientResponse")
    public boolean dropClient(
        @WebParam(name = "beanId", targetNamespace = "")
        ClientId beanId)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param maxResults
     * @param credentialIds
     * @param attributes
     * @return
     *     returns java.util.List<com.initiate.client.ProviderTask>
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "ProviderTask", targetNamespace = "")
    @RequestWrapper(localName = "searchForProviderTaskByCredentialIds", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.SearchForProviderTaskByCredentialIds")
    @ResponseWrapper(localName = "searchForProviderTaskByCredentialIdsResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.SearchForProviderTaskByCredentialIdsResponse")
    public List<ProviderTask> searchForProviderTaskByCredentialIds(
        @WebParam(name = "credentialIds", targetNamespace = "")
        List<CredentialId> credentialIds,
        @WebParam(name = "maxResults", targetNamespace = "")
        int maxResults,
        @WebParam(name = "attributes", targetNamespace = "")
        List<ProviderAttribute> attributes)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param cvwName
     * @param id
     * @param source
     * @param attribute
     * @return
     *     returns java.util.List<com.initiate.client.IdEntity>
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "IdEntity", targetNamespace = "")
    @RequestWrapper(localName = "getIdEntityList", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.GetIdEntityList")
    @ResponseWrapper(localName = "getIdEntityListResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.GetIdEntityListResponse")
    public List<IdEntity> getIdEntityList(
        @WebParam(name = "id", targetNamespace = "")
        List<ClientId> id,
        @WebParam(name = "cvwName", targetNamespace = "")
        String cvwName,
        @WebParam(name = "source", targetNamespace = "")
        List<ClientSource> source,
        @WebParam(name = "attribute", targetNamespace = "")
        List<ClientAttribute> attribute)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param recordId
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "unlinkProviderFromProvEntity", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.UnlinkProviderFromProvEntity")
    @ResponseWrapper(localName = "unlinkProviderFromProvEntityResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.UnlinkProviderFromProvEntityResponse")
    public void unlinkProviderFromProvEntity(
        @WebParam(name = "recordId", targetNamespace = "")
        ProviderId recordId)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param credentialId
     * @param taskId
     * @param status
     * @return
     *     returns java.util.List<com.initiate.client.ProviderTask>
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "ProviderTask", targetNamespace = "")
    @RequestWrapper(localName = "updateProviderTask", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.UpdateProviderTask")
    @ResponseWrapper(localName = "updateProviderTaskResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.UpdateProviderTaskResponse")
    public List<ProviderTask> updateProviderTask(
        @WebParam(name = "taskId", targetNamespace = "")
        ProviderTaskId taskId,
        @WebParam(name = "status", targetNamespace = "")
        String status,
        @WebParam(name = "credentialId", targetNamespace = "")
        CredentialId credentialId)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param mode
     * @param defaultWinner
     * @param createUpdateOptions
     * @param bean
     * @return
     *     returns java.util.List<com.initiate.client.Provider>
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "Provider", targetNamespace = "")
    @RequestWrapper(localName = "updateQualifiedProvWithOptions", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.UpdateQualifiedProvWithOptions")
    @ResponseWrapper(localName = "updateQualifiedProvWithOptionsResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.UpdateQualifiedProvWithOptionsResponse")
    public List<Provider> updateQualifiedProvWithOptions(
        @WebParam(name = "bean", targetNamespace = "")
        Provider bean,
        @WebParam(name = "mode", targetNamespace = "")
        UpdateMode mode,
        @WebParam(name = "defaultWinner", targetNamespace = "")
        boolean defaultWinner,
        @WebParam(name = "createUpdateOptions", targetNamespace = "")
        CreateUpdateOptions createUpdateOptions)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param mode
     * @param bean
     * @return
     *     returns com.initiate.client.Client
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "Client", targetNamespace = "")
    @RequestWrapper(localName = "createClient", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.CreateClient")
    @ResponseWrapper(localName = "createClientResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.CreateClientResponse")
    public Client createClient(
        @WebParam(name = "bean", targetNamespace = "")
        Client bean,
        @WebParam(name = "mode", targetNamespace = "")
        UpdateMode mode)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param cvwName
     * @param id
     * @param source
     * @param attribute
     * @return
     *     returns java.util.List<com.initiate.client.IdEntity>
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "IdEntity", targetNamespace = "")
    @RequestWrapper(localName = "getIdEntityListByIdEntityIds", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.GetIdEntityListByIdEntityIds")
    @ResponseWrapper(localName = "getIdEntityListByIdEntityIdsResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.GetIdEntityListByIdEntityIdsResponse")
    public List<IdEntity> getIdEntityListByIdEntityIds(
        @WebParam(name = "id", targetNamespace = "")
        List<IdEntityId> id,
        @WebParam(name = "cvwName", targetNamespace = "")
        String cvwName,
        @WebParam(name = "source", targetNamespace = "")
        List<ClientSource> source,
        @WebParam(name = "attribute", targetNamespace = "")
        List<ClientAttribute> attribute)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param recordId
     * @param taskType
     * @param description
     * @return
     *     returns com.initiate.client.ClientTaskId
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "ClientTaskId", targetNamespace = "")
    @RequestWrapper(localName = "createCustomClientTask", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.CreateCustomClientTask")
    @ResponseWrapper(localName = "createCustomClientTaskResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.CreateCustomClientTaskResponse")
    public ClientTaskId createCustomClientTask(
        @WebParam(name = "recordId", targetNamespace = "")
        ClientId recordId,
        @WebParam(name = "taskType", targetNamespace = "")
        String taskType,
        @WebParam(name = "description", targetNamespace = "")
        String description)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param mode
     * @param bean
     * @return
     *     returns com.initiate.client.Client
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "Client", targetNamespace = "")
    @RequestWrapper(localName = "updateClient", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.UpdateClient")
    @ResponseWrapper(localName = "updateClientResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.UpdateClientResponse")
    public Client updateClient(
        @WebParam(name = "bean", targetNamespace = "")
        Client bean,
        @WebParam(name = "mode", targetNamespace = "")
        UpdateMode mode)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param attributes
     * @param taskId
     * @return
     *     returns com.initiate.client.ProvEntityTask
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "ProvEntityTask", targetNamespace = "")
    @RequestWrapper(localName = "getProvEntityTask", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.GetProvEntityTask")
    @ResponseWrapper(localName = "getProvEntityTaskResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.GetProvEntityTaskResponse")
    public ProvEntityTask getProvEntityTask(
        @WebParam(name = "taskId", targetNamespace = "")
        ProviderTaskId taskId,
        @WebParam(name = "attributes", targetNamespace = "")
        List<ProviderAttribute> attributes)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param id2
     * @param id1
     * @return
     *     returns short
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "compareClientAsId", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.CompareClientAsId")
    @ResponseWrapper(localName = "compareClientAsIdResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.CompareClientAsIdResponse")
    public short compareClientAsId(
        @WebParam(name = "id1", targetNamespace = "")
        ClientId id1,
        @WebParam(name = "id2", targetNamespace = "")
        ClientId id2)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param attributes
     * @param recordIds
     * @return
     *     returns java.util.List<com.initiate.client.ClientTask>
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "ClientTask", targetNamespace = "")
    @RequestWrapper(localName = "searchForClientTaskByClientIds", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.SearchForClientTaskByClientIds")
    @ResponseWrapper(localName = "searchForClientTaskByClientIdsResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.SearchForClientTaskByClientIdsResponse")
    public List<ClientTask> searchForClientTaskByClientIds(
        @WebParam(name = "recordIds", targetNamespace = "")
        List<ClientId> recordIds,
        @WebParam(name = "attributes", targetNamespace = "")
        List<ClientAttribute> attributes)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param recordId
     * @param entityIdId
     * @return
     *     returns com.initiate.client.ClientTaskId
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "ClientTaskId", targetNamespace = "")
    @RequestWrapper(localName = "markIdEntityLink", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.MarkIdEntityLink")
    @ResponseWrapper(localName = "markIdEntityLinkResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.MarkIdEntityLinkResponse")
    public ClientTaskId markIdEntityLink(
        @WebParam(name = "recordId", targetNamespace = "")
        ClientId recordId,
        @WebParam(name = "entityIdId", targetNamespace = "")
        IdEntityId entityIdId)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param attributes
     * @param taskId
     * @return
     *     returns com.initiate.client.ProviderTask
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "ProviderTask", targetNamespace = "")
    @RequestWrapper(localName = "getProviderTask", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.GetProviderTask")
    @ResponseWrapper(localName = "getProviderTaskResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.GetProviderTaskResponse")
    public ProviderTask getProviderTask(
        @WebParam(name = "taskId", targetNamespace = "")
        ProviderTaskId taskId,
        @WebParam(name = "attributes", targetNamespace = "")
        List<ProviderAttribute> attributes)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param updateEntityType
     * @param updateMode
     * @param createUpdateOptions
     * @param modifySource
     * @param bean
     * @return
     *     returns com.initiate.client.Provider
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateProvEntityWithOptions", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.UpdateProvEntityWithOptions")
    @ResponseWrapper(localName = "updateProvEntityWithOptionsResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.UpdateProvEntityWithOptionsResponse")
    public Provider updateProvEntityWithOptions(
        @WebParam(name = "bean", targetNamespace = "")
        ProvEntity bean,
        @WebParam(name = "modifySource", targetNamespace = "")
        String modifySource,
        @WebParam(name = "updateEntityType", targetNamespace = "")
        UpdateEntityType updateEntityType,
        @WebParam(name = "updateMode", targetNamespace = "")
        UpdateMode updateMode,
        @WebParam(name = "createUpdateOptions", targetNamespace = "")
        CreateUpdateOptions createUpdateOptions)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param mode
     * @param createUpdateOptions
     * @param bean
     * @return
     *     returns com.initiate.client.Client
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "Client", targetNamespace = "")
    @RequestWrapper(localName = "createOrUpdateClientWithOptions", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.CreateOrUpdateClientWithOptions")
    @ResponseWrapper(localName = "createOrUpdateClientWithOptionsResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.CreateOrUpdateClientWithOptionsResponse")
    public Client createOrUpdateClientWithOptions(
        @WebParam(name = "bean", targetNamespace = "")
        Client bean,
        @WebParam(name = "mode", targetNamespace = "")
        UpdateMode mode,
        @WebParam(name = "createUpdateOptions", targetNamespace = "")
        CreateUpdateOptions createUpdateOptions)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param beanId
     * @return
     *     returns boolean
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteClient", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.DeleteClient")
    @ResponseWrapper(localName = "deleteClientResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.DeleteClientResponse")
    public boolean deleteClient(
        @WebParam(name = "beanId", targetNamespace = "")
        ClientId beanId)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param recordId
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "unlinkClientFromIdEntity", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.UnlinkClientFromIdEntity")
    @ResponseWrapper(localName = "unlinkClientFromIdEntityResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.UnlinkClientFromIdEntityResponse")
    public void unlinkClientFromIdEntity(
        @WebParam(name = "recordId", targetNamespace = "")
        ClientId recordId)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param brief
     * @param memStatFilter
     * @param maxResults
     * @param query
     * @param recStatFilter
     * @param cvwName
     * @param source
     * @param attribute
     * @return
     *     returns com.initiate.client.ProviderTextSearchResult
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "ProviderTextSearchResult", targetNamespace = "")
    @RequestWrapper(localName = "textSearchProviderListAsProv", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.TextSearchProviderListAsProv")
    @ResponseWrapper(localName = "textSearchProviderListAsProvResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.TextSearchProviderListAsProvResponse")
    public ProviderTextSearchResult textSearchProviderListAsProv(
        @WebParam(name = "query", targetNamespace = "")
        String query,
        @WebParam(name = "maxResults", targetNamespace = "")
        int maxResults,
        @WebParam(name = "cvwName", targetNamespace = "")
        String cvwName,
        @WebParam(name = "source", targetNamespace = "")
        List<ProviderSource> source,
        @WebParam(name = "attribute", targetNamespace = "")
        List<ProviderAttribute> attribute,
        @WebParam(name = "memStatFilter", targetNamespace = "")
        String memStatFilter,
        @WebParam(name = "recStatFilter", targetNamespace = "")
        String recStatFilter,
        @WebParam(name = "brief", targetNamespace = "")
        boolean brief)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param beanId
     * @return
     *     returns boolean
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "undeleteProvider", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.UndeleteProvider")
    @ResponseWrapper(localName = "undeleteProviderResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.UndeleteProviderResponse")
    public boolean undeleteProvider(
        @WebParam(name = "beanId", targetNamespace = "")
        ProviderId beanId)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param cvwName
     * @param id
     * @param source
     * @param attribute
     * @return
     *     returns java.util.List<com.initiate.client.ProvEntity>
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "ProvEntity", targetNamespace = "")
    @RequestWrapper(localName = "getProvEntityList", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.GetProvEntityList")
    @ResponseWrapper(localName = "getProvEntityListResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.GetProvEntityListResponse")
    public List<ProvEntity> getProvEntityList(
        @WebParam(name = "id", targetNamespace = "")
        List<ProviderId> id,
        @WebParam(name = "cvwName", targetNamespace = "")
        String cvwName,
        @WebParam(name = "source", targetNamespace = "")
        List<ProviderSource> source,
        @WebParam(name = "attribute", targetNamespace = "")
        List<ProviderAttribute> attribute)
        throws MasterDataServiceException_Exception
    ;

    /**
     * 
     * @param obsoleteId
     * @param survivorId
     * @return
     *     returns boolean
     * @throws MasterDataServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "mergeProvider", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.MergeProvider")
    @ResponseWrapper(localName = "mergeProviderResponse", targetNamespace = "http://client.esoa.mdm.ibm.com/", className = "com.initiate.client.MergeProviderResponse")
    public boolean mergeProvider(
        @WebParam(name = "survivorId", targetNamespace = "")
        ProviderId survivorId,
        @WebParam(name = "obsoleteId", targetNamespace = "")
        ProviderId obsoleteId)
        throws MasterDataServiceException_Exception
    ;

}
