package com.ibm.wcm.ods.dto;
// Generated May 31, 2018 4:53:55 PM by Hibernate Tools 5.2.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CalwinClientDemoId generated by hbm2java
 */
@Embeddable
public class CalwinClientDemoId implements java.io.Serializable {

	private String sourceSystemId;
	private String clientId;
	private String maritalStatus;
	private String militaryStatus;
	private String immigrationStatus;
	private String alienRegNum;
	private String foreignAddr;
	private Date dateOfDeath;
	private String educationLevel;
	private String isHsGrad;
	private String enrolledSchool;
	private String isLiterate;
	private String employmentStatus;
	private String numPaidWorkDaysPast30d;
	private String enrolledJobTrain;
	private String emgncyCntctFirstName;
	private String emgncyCntctLastName;
	private String emgncyCntctPhone;
	private String emgncyCntctPhoneExt;
	private String emgncyCntctPhone2;
	private String emgncyCntctPhone2Ext;
	private String emgncyCntctRelation;
	private String livesAtPrimaryAddr;
	private String residenceType;
	private String rentOrOwn;
	private String livesWithRelative;
	private String curLivingArrangement;
	private String numChldU18;
	private String numChldU5;
	private String curWorkExp;
	private Date dateLastWorked;
	private String deathCircumstance;
	private String spokenLang;
	private String pregStatus;
	private Date dueDate;
	private String histOfViolence;
	private String histOfSelfInj;
	private String interpreter;
	private String citizenship;
	private String citizenshipStatus;
	private String veteranStatus;
	private String tribe;
	private String visaType;
	private String schoolName;

	public CalwinClientDemoId() {
	}

	public CalwinClientDemoId(String sourceSystemId, String clientId) {
		this.sourceSystemId = sourceSystemId;
		this.clientId = clientId;
	}

	public CalwinClientDemoId(String sourceSystemId, String clientId, String maritalStatus, String militaryStatus,
			String immigrationStatus, String alienRegNum, String foreignAddr, Date dateOfDeath, String educationLevel,
			String isHsGrad, String enrolledSchool, String isLiterate, String employmentStatus,
			String numPaidWorkDaysPast30d, String enrolledJobTrain, String emgncyCntctFirstName,
			String emgncyCntctLastName, String emgncyCntctPhone, String emgncyCntctPhoneExt, String emgncyCntctPhone2,
			String emgncyCntctPhone2Ext, String emgncyCntctRelation, String livesAtPrimaryAddr, String residenceType,
			String rentOrOwn, String livesWithRelative, String curLivingArrangement, String numChldU18,
			String numChldU5, String curWorkExp, Date dateLastWorked, String deathCircumstance, String spokenLang,
			String pregStatus, Date dueDate, String histOfViolence, String histOfSelfInj, String interpreter,
			String citizenship, String citizenshipStatus, String veteranStatus, String tribe, String visaType,
			String schoolName) {
		this.sourceSystemId = sourceSystemId;
		this.clientId = clientId;
		this.maritalStatus = maritalStatus;
		this.militaryStatus = militaryStatus;
		this.immigrationStatus = immigrationStatus;
		this.alienRegNum = alienRegNum;
		this.foreignAddr = foreignAddr;
		this.dateOfDeath = dateOfDeath;
		this.educationLevel = educationLevel;
		this.isHsGrad = isHsGrad;
		this.enrolledSchool = enrolledSchool;
		this.isLiterate = isLiterate;
		this.employmentStatus = employmentStatus;
		this.numPaidWorkDaysPast30d = numPaidWorkDaysPast30d;
		this.enrolledJobTrain = enrolledJobTrain;
		this.emgncyCntctFirstName = emgncyCntctFirstName;
		this.emgncyCntctLastName = emgncyCntctLastName;
		this.emgncyCntctPhone = emgncyCntctPhone;
		this.emgncyCntctPhoneExt = emgncyCntctPhoneExt;
		this.emgncyCntctPhone2 = emgncyCntctPhone2;
		this.emgncyCntctPhone2Ext = emgncyCntctPhone2Ext;
		this.emgncyCntctRelation = emgncyCntctRelation;
		this.livesAtPrimaryAddr = livesAtPrimaryAddr;
		this.residenceType = residenceType;
		this.rentOrOwn = rentOrOwn;
		this.livesWithRelative = livesWithRelative;
		this.curLivingArrangement = curLivingArrangement;
		this.numChldU18 = numChldU18;
		this.numChldU5 = numChldU5;
		this.curWorkExp = curWorkExp;
		this.dateLastWorked = dateLastWorked;
		this.deathCircumstance = deathCircumstance;
		this.spokenLang = spokenLang;
		this.pregStatus = pregStatus;
		this.dueDate = dueDate;
		this.histOfViolence = histOfViolence;
		this.histOfSelfInj = histOfSelfInj;
		this.interpreter = interpreter;
		this.citizenship = citizenship;
		this.citizenshipStatus = citizenshipStatus;
		this.veteranStatus = veteranStatus;
		this.tribe = tribe;
		this.visaType = visaType;
		this.schoolName = schoolName;
	}

	@Column(name = "SOURCE_SYSTEM_ID", nullable = false, length = 18)
	public String getSourceSystemId() {
		return this.sourceSystemId;
	}

	public void setSourceSystemId(String sourceSystemId) {
		this.sourceSystemId = sourceSystemId;
	}

	@Column(name = "CLIENT_ID", nullable = false, length = 60)
	public String getClientId() {
		return this.clientId;
	}

	public void setClientId(String clientId) {
		this.clientId = clientId;
	}

	@Column(name = "MARITAL_STATUS", length = 30)
	public String getMaritalStatus() {
		return this.maritalStatus;
	}

	public void setMaritalStatus(String maritalStatus) {
		this.maritalStatus = maritalStatus;
	}

	@Column(name = "MILITARY_STATUS", length = 256)
	public String getMilitaryStatus() {
		return this.militaryStatus;
	}

	public void setMilitaryStatus(String militaryStatus) {
		this.militaryStatus = militaryStatus;
	}

	@Column(name = "IMMIGRATION_STATUS", length = 30)
	public String getImmigrationStatus() {
		return this.immigrationStatus;
	}

	public void setImmigrationStatus(String immigrationStatus) {
		this.immigrationStatus = immigrationStatus;
	}

	@Column(name = "ALIEN_REG_NUM", length = 30)
	public String getAlienRegNum() {
		return this.alienRegNum;
	}

	public void setAlienRegNum(String alienRegNum) {
		this.alienRegNum = alienRegNum;
	}

	@Column(name = "FOREIGN_ADDR", length = 512)
	public String getForeignAddr() {
		return this.foreignAddr;
	}

	public void setForeignAddr(String foreignAddr) {
		this.foreignAddr = foreignAddr;
	}

	@Column(name = "DATE_OF_DEATH", length = 10)
	public Date getDateOfDeath() {
		return this.dateOfDeath;
	}

	public void setDateOfDeath(Date dateOfDeath) {
		this.dateOfDeath = dateOfDeath;
	}

	@Column(name = "EDUCATION_LEVEL", length = 30)
	public String getEducationLevel() {
		return this.educationLevel;
	}

	public void setEducationLevel(String educationLevel) {
		this.educationLevel = educationLevel;
	}

	@Column(name = "IS_HS_GRAD", length = 30)
	public String getIsHsGrad() {
		return this.isHsGrad;
	}

	public void setIsHsGrad(String isHsGrad) {
		this.isHsGrad = isHsGrad;
	}

	@Column(name = "ENROLLED_SCHOOL", length = 30)
	public String getEnrolledSchool() {
		return this.enrolledSchool;
	}

	public void setEnrolledSchool(String enrolledSchool) {
		this.enrolledSchool = enrolledSchool;
	}

	@Column(name = "IS_LITERATE", length = 50)
	public String getIsLiterate() {
		return this.isLiterate;
	}

	public void setIsLiterate(String isLiterate) {
		this.isLiterate = isLiterate;
	}

	@Column(name = "EMPLOYMENT_STATUS", length = 256)
	public String getEmploymentStatus() {
		return this.employmentStatus;
	}

	public void setEmploymentStatus(String employmentStatus) {
		this.employmentStatus = employmentStatus;
	}

	@Column(name = "NUM_PAID_WORK_DAYS_PAST30D", length = 256)
	public String getNumPaidWorkDaysPast30d() {
		return this.numPaidWorkDaysPast30d;
	}

	public void setNumPaidWorkDaysPast30d(String numPaidWorkDaysPast30d) {
		this.numPaidWorkDaysPast30d = numPaidWorkDaysPast30d;
	}

	@Column(name = "ENROLLED_JOB_TRAIN", length = 30)
	public String getEnrolledJobTrain() {
		return this.enrolledJobTrain;
	}

	public void setEnrolledJobTrain(String enrolledJobTrain) {
		this.enrolledJobTrain = enrolledJobTrain;
	}

	@Column(name = "EMGNCY_CNTCT_FIRST_NAME", length = 35)
	public String getEmgncyCntctFirstName() {
		return this.emgncyCntctFirstName;
	}

	public void setEmgncyCntctFirstName(String emgncyCntctFirstName) {
		this.emgncyCntctFirstName = emgncyCntctFirstName;
	}

	@Column(name = "EMGNCY_CNTCT_LAST_NAME", length = 50)
	public String getEmgncyCntctLastName() {
		return this.emgncyCntctLastName;
	}

	public void setEmgncyCntctLastName(String emgncyCntctLastName) {
		this.emgncyCntctLastName = emgncyCntctLastName;
	}

	@Column(name = "EMGNCY_CNTCT_PHONE", length = 40)
	public String getEmgncyCntctPhone() {
		return this.emgncyCntctPhone;
	}

	public void setEmgncyCntctPhone(String emgncyCntctPhone) {
		this.emgncyCntctPhone = emgncyCntctPhone;
	}

	@Column(name = "EMGNCY_CNTCT_PHONE_EXT", length = 100)
	public String getEmgncyCntctPhoneExt() {
		return this.emgncyCntctPhoneExt;
	}

	public void setEmgncyCntctPhoneExt(String emgncyCntctPhoneExt) {
		this.emgncyCntctPhoneExt = emgncyCntctPhoneExt;
	}

	@Column(name = "EMGNCY_CNTCT_PHONE2", length = 40)
	public String getEmgncyCntctPhone2() {
		return this.emgncyCntctPhone2;
	}

	public void setEmgncyCntctPhone2(String emgncyCntctPhone2) {
		this.emgncyCntctPhone2 = emgncyCntctPhone2;
	}

	@Column(name = "EMGNCY_CNTCT_PHONE2_EXT", length = 100)
	public String getEmgncyCntctPhone2Ext() {
		return this.emgncyCntctPhone2Ext;
	}

	public void setEmgncyCntctPhone2Ext(String emgncyCntctPhone2Ext) {
		this.emgncyCntctPhone2Ext = emgncyCntctPhone2Ext;
	}

	@Column(name = "EMGNCY_CNTCT_RELATION", length = 50)
	public String getEmgncyCntctRelation() {
		return this.emgncyCntctRelation;
	}

	public void setEmgncyCntctRelation(String emgncyCntctRelation) {
		this.emgncyCntctRelation = emgncyCntctRelation;
	}

	@Column(name = "LIVES_AT_PRIMARY_ADDR", length = 30)
	public String getLivesAtPrimaryAddr() {
		return this.livesAtPrimaryAddr;
	}

	public void setLivesAtPrimaryAddr(String livesAtPrimaryAddr) {
		this.livesAtPrimaryAddr = livesAtPrimaryAddr;
	}

	@Column(name = "RESIDENCE_TYPE", length = 30)
	public String getResidenceType() {
		return this.residenceType;
	}

	public void setResidenceType(String residenceType) {
		this.residenceType = residenceType;
	}

	@Column(name = "RENT_OR_OWN", length = 30)
	public String getRentOrOwn() {
		return this.rentOrOwn;
	}

	public void setRentOrOwn(String rentOrOwn) {
		this.rentOrOwn = rentOrOwn;
	}

	@Column(name = "LIVES_WITH_RELATIVE", length = 50)
	public String getLivesWithRelative() {
		return this.livesWithRelative;
	}

	public void setLivesWithRelative(String livesWithRelative) {
		this.livesWithRelative = livesWithRelative;
	}

	@Column(name = "CUR_LIVING_ARRANGEMENT", length = 256)
	public String getCurLivingArrangement() {
		return this.curLivingArrangement;
	}

	public void setCurLivingArrangement(String curLivingArrangement) {
		this.curLivingArrangement = curLivingArrangement;
	}

	@Column(name = "NUM_CHLD_U18", length = 256)
	public String getNumChldU18() {
		return this.numChldU18;
	}

	public void setNumChldU18(String numChldU18) {
		this.numChldU18 = numChldU18;
	}

	@Column(name = "NUM_CHLD_U5", length = 256)
	public String getNumChldU5() {
		return this.numChldU5;
	}

	public void setNumChldU5(String numChldU5) {
		this.numChldU5 = numChldU5;
	}

	@Column(name = "CUR_WORK_EXP", length = 60)
	public String getCurWorkExp() {
		return this.curWorkExp;
	}

	public void setCurWorkExp(String curWorkExp) {
		this.curWorkExp = curWorkExp;
	}

	@Column(name = "DATE_LAST_WORKED", length = 10)
	public Date getDateLastWorked() {
		return this.dateLastWorked;
	}

	public void setDateLastWorked(Date dateLastWorked) {
		this.dateLastWorked = dateLastWorked;
	}

	@Column(name = "DEATH_CIRCUMSTANCE", length = 20)
	public String getDeathCircumstance() {
		return this.deathCircumstance;
	}

	public void setDeathCircumstance(String deathCircumstance) {
		this.deathCircumstance = deathCircumstance;
	}

	@Column(name = "SPOKEN_LANG", length = 50)
	public String getSpokenLang() {
		return this.spokenLang;
	}

	public void setSpokenLang(String spokenLang) {
		this.spokenLang = spokenLang;
	}

	@Column(name = "PREG_STATUS", length = 60)
	public String getPregStatus() {
		return this.pregStatus;
	}

	public void setPregStatus(String pregStatus) {
		this.pregStatus = pregStatus;
	}

	@Column(name = "DUE_DATE", length = 10)
	public Date getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
	}

	@Column(name = "HIST_OF_VIOLENCE", length = 3)
	public String getHistOfViolence() {
		return this.histOfViolence;
	}

	public void setHistOfViolence(String histOfViolence) {
		this.histOfViolence = histOfViolence;
	}

	@Column(name = "HIST_OF_SELF_INJ", length = 60)
	public String getHistOfSelfInj() {
		return this.histOfSelfInj;
	}

	public void setHistOfSelfInj(String histOfSelfInj) {
		this.histOfSelfInj = histOfSelfInj;
	}

	@Column(name = "INTERPRETER", length = 50)
	public String getInterpreter() {
		return this.interpreter;
	}

	public void setInterpreter(String interpreter) {
		this.interpreter = interpreter;
	}

	@Column(name = "CITIZENSHIP", length = 50)
	public String getCitizenship() {
		return this.citizenship;
	}

	public void setCitizenship(String citizenship) {
		this.citizenship = citizenship;
	}

	@Column(name = "CITIZENSHIP_STATUS", length = 50)
	public String getCitizenshipStatus() {
		return this.citizenshipStatus;
	}

	public void setCitizenshipStatus(String citizenshipStatus) {
		this.citizenshipStatus = citizenshipStatus;
	}

	@Column(name = "VETERAN_STATUS", length = 50)
	public String getVeteranStatus() {
		return this.veteranStatus;
	}

	public void setVeteranStatus(String veteranStatus) {
		this.veteranStatus = veteranStatus;
	}

	@Column(name = "TRIBE", length = 20)
	public String getTribe() {
		return this.tribe;
	}

	public void setTribe(String tribe) {
		this.tribe = tribe;
	}

	@Column(name = "VISA_TYPE", length = 30)
	public String getVisaType() {
		return this.visaType;
	}

	public void setVisaType(String visaType) {
		this.visaType = visaType;
	}

	@Column(name = "SCHOOL_NAME", length = 40)
	public String getSchoolName() {
		return this.schoolName;
	}

	public void setSchoolName(String schoolName) {
		this.schoolName = schoolName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CalwinClientDemoId))
			return false;
		CalwinClientDemoId castOther = (CalwinClientDemoId) other;

		return ((this.getSourceSystemId() == castOther.getSourceSystemId())
				|| (this.getSourceSystemId() != null && castOther.getSourceSystemId() != null
						&& this.getSourceSystemId().equals(castOther.getSourceSystemId())))
				&& ((this.getClientId() == castOther.getClientId()) || (this.getClientId() != null
						&& castOther.getClientId() != null && this.getClientId().equals(castOther.getClientId())))
				&& ((this.getMaritalStatus() == castOther.getMaritalStatus())
						|| (this.getMaritalStatus() != null && castOther.getMaritalStatus() != null
								&& this.getMaritalStatus().equals(castOther.getMaritalStatus())))
				&& ((this.getMilitaryStatus() == castOther.getMilitaryStatus())
						|| (this.getMilitaryStatus() != null && castOther.getMilitaryStatus() != null
								&& this.getMilitaryStatus().equals(castOther.getMilitaryStatus())))
				&& ((this.getImmigrationStatus() == castOther.getImmigrationStatus())
						|| (this.getImmigrationStatus() != null && castOther.getImmigrationStatus() != null
								&& this.getImmigrationStatus().equals(castOther.getImmigrationStatus())))
				&& ((this.getAlienRegNum() == castOther.getAlienRegNum())
						|| (this.getAlienRegNum() != null && castOther.getAlienRegNum() != null
								&& this.getAlienRegNum().equals(castOther.getAlienRegNum())))
				&& ((this.getForeignAddr() == castOther.getForeignAddr())
						|| (this.getForeignAddr() != null && castOther.getForeignAddr() != null
								&& this.getForeignAddr().equals(castOther.getForeignAddr())))
				&& ((this.getDateOfDeath() == castOther.getDateOfDeath())
						|| (this.getDateOfDeath() != null && castOther.getDateOfDeath() != null
								&& this.getDateOfDeath().equals(castOther.getDateOfDeath())))
				&& ((this.getEducationLevel() == castOther.getEducationLevel())
						|| (this.getEducationLevel() != null && castOther.getEducationLevel() != null
								&& this.getEducationLevel().equals(castOther.getEducationLevel())))
				&& ((this.getIsHsGrad() == castOther.getIsHsGrad()) || (this.getIsHsGrad() != null
						&& castOther.getIsHsGrad() != null && this.getIsHsGrad().equals(castOther.getIsHsGrad())))
				&& ((this.getEnrolledSchool() == castOther.getEnrolledSchool())
						|| (this.getEnrolledSchool() != null && castOther.getEnrolledSchool() != null
								&& this.getEnrolledSchool().equals(castOther.getEnrolledSchool())))
				&& ((this.getIsLiterate() == castOther.getIsLiterate()) || (this.getIsLiterate() != null
						&& castOther.getIsLiterate() != null && this.getIsLiterate().equals(castOther.getIsLiterate())))
				&& ((this.getEmploymentStatus() == castOther.getEmploymentStatus())
						|| (this.getEmploymentStatus() != null && castOther.getEmploymentStatus() != null
								&& this.getEmploymentStatus().equals(castOther.getEmploymentStatus())))
				&& ((this.getNumPaidWorkDaysPast30d() == castOther.getNumPaidWorkDaysPast30d())
						|| (this.getNumPaidWorkDaysPast30d() != null && castOther.getNumPaidWorkDaysPast30d() != null
								&& this.getNumPaidWorkDaysPast30d().equals(castOther.getNumPaidWorkDaysPast30d())))
				&& ((this.getEnrolledJobTrain() == castOther.getEnrolledJobTrain())
						|| (this.getEnrolledJobTrain() != null && castOther.getEnrolledJobTrain() != null
								&& this.getEnrolledJobTrain().equals(castOther.getEnrolledJobTrain())))
				&& ((this.getEmgncyCntctFirstName() == castOther.getEmgncyCntctFirstName())
						|| (this.getEmgncyCntctFirstName() != null && castOther.getEmgncyCntctFirstName() != null
								&& this.getEmgncyCntctFirstName().equals(castOther.getEmgncyCntctFirstName())))
				&& ((this.getEmgncyCntctLastName() == castOther.getEmgncyCntctLastName())
						|| (this.getEmgncyCntctLastName() != null && castOther.getEmgncyCntctLastName() != null
								&& this.getEmgncyCntctLastName().equals(castOther.getEmgncyCntctLastName())))
				&& ((this.getEmgncyCntctPhone() == castOther.getEmgncyCntctPhone())
						|| (this.getEmgncyCntctPhone() != null && castOther.getEmgncyCntctPhone() != null
								&& this.getEmgncyCntctPhone().equals(castOther.getEmgncyCntctPhone())))
				&& ((this.getEmgncyCntctPhoneExt() == castOther.getEmgncyCntctPhoneExt())
						|| (this.getEmgncyCntctPhoneExt() != null && castOther.getEmgncyCntctPhoneExt() != null
								&& this.getEmgncyCntctPhoneExt().equals(castOther.getEmgncyCntctPhoneExt())))
				&& ((this.getEmgncyCntctPhone2() == castOther.getEmgncyCntctPhone2())
						|| (this.getEmgncyCntctPhone2() != null && castOther.getEmgncyCntctPhone2() != null
								&& this.getEmgncyCntctPhone2().equals(castOther.getEmgncyCntctPhone2())))
				&& ((this.getEmgncyCntctPhone2Ext() == castOther.getEmgncyCntctPhone2Ext())
						|| (this.getEmgncyCntctPhone2Ext() != null && castOther.getEmgncyCntctPhone2Ext() != null
								&& this.getEmgncyCntctPhone2Ext().equals(castOther.getEmgncyCntctPhone2Ext())))
				&& ((this.getEmgncyCntctRelation() == castOther.getEmgncyCntctRelation())
						|| (this.getEmgncyCntctRelation() != null && castOther.getEmgncyCntctRelation() != null
								&& this.getEmgncyCntctRelation().equals(castOther.getEmgncyCntctRelation())))
				&& ((this.getLivesAtPrimaryAddr() == castOther.getLivesAtPrimaryAddr())
						|| (this.getLivesAtPrimaryAddr() != null && castOther.getLivesAtPrimaryAddr() != null
								&& this.getLivesAtPrimaryAddr().equals(castOther.getLivesAtPrimaryAddr())))
				&& ((this.getResidenceType() == castOther.getResidenceType())
						|| (this.getResidenceType() != null && castOther.getResidenceType() != null
								&& this.getResidenceType().equals(castOther.getResidenceType())))
				&& ((this.getRentOrOwn() == castOther.getRentOrOwn()) || (this.getRentOrOwn() != null
						&& castOther.getRentOrOwn() != null && this.getRentOrOwn().equals(castOther.getRentOrOwn())))
				&& ((this.getLivesWithRelative() == castOther.getLivesWithRelative())
						|| (this.getLivesWithRelative() != null && castOther.getLivesWithRelative() != null
								&& this.getLivesWithRelative().equals(castOther.getLivesWithRelative())))
				&& ((this.getCurLivingArrangement() == castOther.getCurLivingArrangement())
						|| (this.getCurLivingArrangement() != null && castOther.getCurLivingArrangement() != null
								&& this.getCurLivingArrangement().equals(castOther.getCurLivingArrangement())))
				&& ((this.getNumChldU18() == castOther.getNumChldU18()) || (this.getNumChldU18() != null
						&& castOther.getNumChldU18() != null && this.getNumChldU18().equals(castOther.getNumChldU18())))
				&& ((this.getNumChldU5() == castOther.getNumChldU5()) || (this.getNumChldU5() != null
						&& castOther.getNumChldU5() != null && this.getNumChldU5().equals(castOther.getNumChldU5())))
				&& ((this.getCurWorkExp() == castOther.getCurWorkExp()) || (this.getCurWorkExp() != null
						&& castOther.getCurWorkExp() != null && this.getCurWorkExp().equals(castOther.getCurWorkExp())))
				&& ((this.getDateLastWorked() == castOther.getDateLastWorked())
						|| (this.getDateLastWorked() != null && castOther.getDateLastWorked() != null
								&& this.getDateLastWorked().equals(castOther.getDateLastWorked())))
				&& ((this.getDeathCircumstance() == castOther.getDeathCircumstance())
						|| (this.getDeathCircumstance() != null && castOther.getDeathCircumstance() != null
								&& this.getDeathCircumstance().equals(castOther.getDeathCircumstance())))
				&& ((this.getSpokenLang() == castOther.getSpokenLang()) || (this.getSpokenLang() != null
						&& castOther.getSpokenLang() != null && this.getSpokenLang().equals(castOther.getSpokenLang())))
				&& ((this.getPregStatus() == castOther.getPregStatus()) || (this.getPregStatus() != null
						&& castOther.getPregStatus() != null && this.getPregStatus().equals(castOther.getPregStatus())))
				&& ((this.getDueDate() == castOther.getDueDate()) || (this.getDueDate() != null
						&& castOther.getDueDate() != null && this.getDueDate().equals(castOther.getDueDate())))
				&& ((this.getHistOfViolence() == castOther.getHistOfViolence())
						|| (this.getHistOfViolence() != null && castOther.getHistOfViolence() != null
								&& this.getHistOfViolence().equals(castOther.getHistOfViolence())))
				&& ((this.getHistOfSelfInj() == castOther.getHistOfSelfInj())
						|| (this.getHistOfSelfInj() != null && castOther.getHistOfSelfInj() != null
								&& this.getHistOfSelfInj().equals(castOther.getHistOfSelfInj())))
				&& ((this.getInterpreter() == castOther.getInterpreter())
						|| (this.getInterpreter() != null && castOther.getInterpreter() != null
								&& this.getInterpreter().equals(castOther.getInterpreter())))
				&& ((this.getCitizenship() == castOther.getCitizenship())
						|| (this.getCitizenship() != null && castOther.getCitizenship() != null
								&& this.getCitizenship().equals(castOther.getCitizenship())))
				&& ((this.getCitizenshipStatus() == castOther.getCitizenshipStatus())
						|| (this.getCitizenshipStatus() != null && castOther.getCitizenshipStatus() != null
								&& this.getCitizenshipStatus().equals(castOther.getCitizenshipStatus())))
				&& ((this.getVeteranStatus() == castOther.getVeteranStatus())
						|| (this.getVeteranStatus() != null && castOther.getVeteranStatus() != null
								&& this.getVeteranStatus().equals(castOther.getVeteranStatus())))
				&& ((this.getTribe() == castOther.getTribe()) || (this.getTribe() != null
						&& castOther.getTribe() != null && this.getTribe().equals(castOther.getTribe())))
				&& ((this.getVisaType() == castOther.getVisaType()) || (this.getVisaType() != null
						&& castOther.getVisaType() != null && this.getVisaType().equals(castOther.getVisaType())))
				&& ((this.getSchoolName() == castOther.getSchoolName())
						|| (this.getSchoolName() != null && castOther.getSchoolName() != null
								&& this.getSchoolName().equals(castOther.getSchoolName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSourceSystemId() == null ? 0 : this.getSourceSystemId().hashCode());
		result = 37 * result + (getClientId() == null ? 0 : this.getClientId().hashCode());
		result = 37 * result + (getMaritalStatus() == null ? 0 : this.getMaritalStatus().hashCode());
		result = 37 * result + (getMilitaryStatus() == null ? 0 : this.getMilitaryStatus().hashCode());
		result = 37 * result + (getImmigrationStatus() == null ? 0 : this.getImmigrationStatus().hashCode());
		result = 37 * result + (getAlienRegNum() == null ? 0 : this.getAlienRegNum().hashCode());
		result = 37 * result + (getForeignAddr() == null ? 0 : this.getForeignAddr().hashCode());
		result = 37 * result + (getDateOfDeath() == null ? 0 : this.getDateOfDeath().hashCode());
		result = 37 * result + (getEducationLevel() == null ? 0 : this.getEducationLevel().hashCode());
		result = 37 * result + (getIsHsGrad() == null ? 0 : this.getIsHsGrad().hashCode());
		result = 37 * result + (getEnrolledSchool() == null ? 0 : this.getEnrolledSchool().hashCode());
		result = 37 * result + (getIsLiterate() == null ? 0 : this.getIsLiterate().hashCode());
		result = 37 * result + (getEmploymentStatus() == null ? 0 : this.getEmploymentStatus().hashCode());
		result = 37 * result + (getNumPaidWorkDaysPast30d() == null ? 0 : this.getNumPaidWorkDaysPast30d().hashCode());
		result = 37 * result + (getEnrolledJobTrain() == null ? 0 : this.getEnrolledJobTrain().hashCode());
		result = 37 * result + (getEmgncyCntctFirstName() == null ? 0 : this.getEmgncyCntctFirstName().hashCode());
		result = 37 * result + (getEmgncyCntctLastName() == null ? 0 : this.getEmgncyCntctLastName().hashCode());
		result = 37 * result + (getEmgncyCntctPhone() == null ? 0 : this.getEmgncyCntctPhone().hashCode());
		result = 37 * result + (getEmgncyCntctPhoneExt() == null ? 0 : this.getEmgncyCntctPhoneExt().hashCode());
		result = 37 * result + (getEmgncyCntctPhone2() == null ? 0 : this.getEmgncyCntctPhone2().hashCode());
		result = 37 * result + (getEmgncyCntctPhone2Ext() == null ? 0 : this.getEmgncyCntctPhone2Ext().hashCode());
		result = 37 * result + (getEmgncyCntctRelation() == null ? 0 : this.getEmgncyCntctRelation().hashCode());
		result = 37 * result + (getLivesAtPrimaryAddr() == null ? 0 : this.getLivesAtPrimaryAddr().hashCode());
		result = 37 * result + (getResidenceType() == null ? 0 : this.getResidenceType().hashCode());
		result = 37 * result + (getRentOrOwn() == null ? 0 : this.getRentOrOwn().hashCode());
		result = 37 * result + (getLivesWithRelative() == null ? 0 : this.getLivesWithRelative().hashCode());
		result = 37 * result + (getCurLivingArrangement() == null ? 0 : this.getCurLivingArrangement().hashCode());
		result = 37 * result + (getNumChldU18() == null ? 0 : this.getNumChldU18().hashCode());
		result = 37 * result + (getNumChldU5() == null ? 0 : this.getNumChldU5().hashCode());
		result = 37 * result + (getCurWorkExp() == null ? 0 : this.getCurWorkExp().hashCode());
		result = 37 * result + (getDateLastWorked() == null ? 0 : this.getDateLastWorked().hashCode());
		result = 37 * result + (getDeathCircumstance() == null ? 0 : this.getDeathCircumstance().hashCode());
		result = 37 * result + (getSpokenLang() == null ? 0 : this.getSpokenLang().hashCode());
		result = 37 * result + (getPregStatus() == null ? 0 : this.getPregStatus().hashCode());
		result = 37 * result + (getDueDate() == null ? 0 : this.getDueDate().hashCode());
		result = 37 * result + (getHistOfViolence() == null ? 0 : this.getHistOfViolence().hashCode());
		result = 37 * result + (getHistOfSelfInj() == null ? 0 : this.getHistOfSelfInj().hashCode());
		result = 37 * result + (getInterpreter() == null ? 0 : this.getInterpreter().hashCode());
		result = 37 * result + (getCitizenship() == null ? 0 : this.getCitizenship().hashCode());
		result = 37 * result + (getCitizenshipStatus() == null ? 0 : this.getCitizenshipStatus().hashCode());
		result = 37 * result + (getVeteranStatus() == null ? 0 : this.getVeteranStatus().hashCode());
		result = 37 * result + (getTribe() == null ? 0 : this.getTribe().hashCode());
		result = 37 * result + (getVisaType() == null ? 0 : this.getVisaType().hashCode());
		result = 37 * result + (getSchoolName() == null ? 0 : this.getSchoolName().hashCode());
		return result;
	}

}
