package com.ibm.wcm.ods.dto;
// Generated May 31, 2018 4:53:55 PM by Hibernate Tools 5.2.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import com.ibm.gbs.util.Constant;
/**
 * CalwinClientDemo generated by hbm2java
 */
import com.ibm.gbs.util.Constant; 
@Entity
@Table(schema = Constant.SCHEMANAME_ODS , name = "CALWIN_CLIENT_DEMO")
public class CalwinClientDemo implements java.io.Serializable {

	private CalwinClientDemoId id;

	public CalwinClientDemo() {
	}

	public CalwinClientDemo(CalwinClientDemoId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "sourceSystemId", column = @Column(name = "SOURCE_SYSTEM_ID", nullable = false, length = 18)),
			@AttributeOverride(name = "clientId", column = @Column(name = "CLIENT_ID", nullable = false, length = 60)),
			@AttributeOverride(name = "maritalStatus", column = @Column(name = "MARITAL_STATUS", length = 30)),
			@AttributeOverride(name = "militaryStatus", column = @Column(name = "MILITARY_STATUS", length = 256)),
			@AttributeOverride(name = "immigrationStatus", column = @Column(name = "IMMIGRATION_STATUS", length = 30)),
			@AttributeOverride(name = "alienRegNum", column = @Column(name = "ALIEN_REG_NUM", length = 30)),
			@AttributeOverride(name = "foreignAddr", column = @Column(name = "FOREIGN_ADDR", length = 512)),
			@AttributeOverride(name = "dateOfDeath", column = @Column(name = "DATE_OF_DEATH", length = 10)),
			@AttributeOverride(name = "educationLevel", column = @Column(name = "EDUCATION_LEVEL", length = 30)),
			@AttributeOverride(name = "isHsGrad", column = @Column(name = "IS_HS_GRAD", length = 30)),
			@AttributeOverride(name = "enrolledSchool", column = @Column(name = "ENROLLED_SCHOOL", length = 30)),
			@AttributeOverride(name = "isLiterate", column = @Column(name = "IS_LITERATE", length = 50)),
			@AttributeOverride(name = "employmentStatus", column = @Column(name = "EMPLOYMENT_STATUS", length = 256)),
			@AttributeOverride(name = "numPaidWorkDaysPast30d", column = @Column(name = "NUM_PAID_WORK_DAYS_PAST30D", length = 256)),
			@AttributeOverride(name = "enrolledJobTrain", column = @Column(name = "ENROLLED_JOB_TRAIN", length = 30)),
			@AttributeOverride(name = "emgncyCntctFirstName", column = @Column(name = "EMGNCY_CNTCT_FIRST_NAME", length = 35)),
			@AttributeOverride(name = "emgncyCntctLastName", column = @Column(name = "EMGNCY_CNTCT_LAST_NAME", length = 50)),
			@AttributeOverride(name = "emgncyCntctPhone", column = @Column(name = "EMGNCY_CNTCT_PHONE", length = 40)),
			@AttributeOverride(name = "emgncyCntctPhoneExt", column = @Column(name = "EMGNCY_CNTCT_PHONE_EXT", length = 100)),
			@AttributeOverride(name = "emgncyCntctPhone2", column = @Column(name = "EMGNCY_CNTCT_PHONE2", length = 40)),
			@AttributeOverride(name = "emgncyCntctPhone2Ext", column = @Column(name = "EMGNCY_CNTCT_PHONE2_EXT", length = 100)),
			@AttributeOverride(name = "emgncyCntctRelation", column = @Column(name = "EMGNCY_CNTCT_RELATION", length = 50)),
			@AttributeOverride(name = "livesAtPrimaryAddr", column = @Column(name = "LIVES_AT_PRIMARY_ADDR", length = 30)),
			@AttributeOverride(name = "residenceType", column = @Column(name = "RESIDENCE_TYPE", length = 30)),
			@AttributeOverride(name = "rentOrOwn", column = @Column(name = "RENT_OR_OWN", length = 30)),
			@AttributeOverride(name = "livesWithRelative", column = @Column(name = "LIVES_WITH_RELATIVE", length = 50)),
			@AttributeOverride(name = "curLivingArrangement", column = @Column(name = "CUR_LIVING_ARRANGEMENT", length = 256)),
			@AttributeOverride(name = "numChldU18", column = @Column(name = "NUM_CHLD_U18", length = 256)),
			@AttributeOverride(name = "numChldU5", column = @Column(name = "NUM_CHLD_U5", length = 256)),
			@AttributeOverride(name = "curWorkExp", column = @Column(name = "CUR_WORK_EXP", length = 60)),
			@AttributeOverride(name = "dateLastWorked", column = @Column(name = "DATE_LAST_WORKED", length = 10)),
			@AttributeOverride(name = "deathCircumstance", column = @Column(name = "DEATH_CIRCUMSTANCE", length = 20)),
			@AttributeOverride(name = "spokenLang", column = @Column(name = "SPOKEN_LANG", length = 50)),
			@AttributeOverride(name = "pregStatus", column = @Column(name = "PREG_STATUS", length = 60)),
			@AttributeOverride(name = "dueDate", column = @Column(name = "DUE_DATE", length = 10)),
			@AttributeOverride(name = "histOfViolence", column = @Column(name = "HIST_OF_VIOLENCE", length = 3)),
			@AttributeOverride(name = "histOfSelfInj", column = @Column(name = "HIST_OF_SELF_INJ", length = 60)),
			@AttributeOverride(name = "interpreter", column = @Column(name = "INTERPRETER", length = 50)),
			@AttributeOverride(name = "citizenship", column = @Column(name = "CITIZENSHIP", length = 50)),
			@AttributeOverride(name = "citizenshipStatus", column = @Column(name = "CITIZENSHIP_STATUS", length = 50)),
			@AttributeOverride(name = "veteranStatus", column = @Column(name = "VETERAN_STATUS", length = 50)),
			@AttributeOverride(name = "tribe", column = @Column(name = "TRIBE", length = 20)),
			@AttributeOverride(name = "visaType", column = @Column(name = "VISA_TYPE", length = 30)),
			@AttributeOverride(name = "schoolName", column = @Column(name = "SCHOOL_NAME", length = 40)) })
	public CalwinClientDemoId getId() {
		return this.id;
	}

	public void setId(CalwinClientDemoId id) {
		this.id = id;
	}

}
