package com.ibm.wcm.ods.dto;
// Generated May 31, 2018 4:53:55 PM by Hibernate Tools 5.2.6.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClientProfileCwSrc generated by hbm2java
 */
import com.ibm.gbs.util.Constant; 
@Entity
@Table(schema = Constant.SCHEMANAME_ODS , name = "CLIENT_PROFILE_CW_SRC")
public class ClientProfileCwSrc implements java.io.Serializable {

	private BigDecimal clientProfileCwSeqNum;
	private String clientId;
	private String sourceSystemId;
	private String caseWorkerName;
	private String caseWorkerPhone;
	private Date processTs;

	public ClientProfileCwSrc() {
	}

	public ClientProfileCwSrc(BigDecimal clientProfileCwSeqNum) {
		this.clientProfileCwSeqNum = clientProfileCwSeqNum;
	}

	public ClientProfileCwSrc(BigDecimal clientProfileCwSeqNum, String clientId, String sourceSystemId,
			String caseWorkerName, String caseWorkerPhone, Date processTs) {
		this.clientProfileCwSeqNum = clientProfileCwSeqNum;
		this.clientId = clientId;
		this.sourceSystemId = sourceSystemId;
		this.caseWorkerName = caseWorkerName;
		this.caseWorkerPhone = caseWorkerPhone;
		this.processTs = processTs;
	}

	@Id

	@Column(name = "CLIENT_PROFILE_CW_SEQ_NUM", unique = true, nullable = false, precision = 31, scale = 0)
	public BigDecimal getClientProfileCwSeqNum() {
		return this.clientProfileCwSeqNum;
	}

	public void setClientProfileCwSeqNum(BigDecimal clientProfileCwSeqNum) {
		this.clientProfileCwSeqNum = clientProfileCwSeqNum;
	}

	@Column(name = "CLIENT_ID", length = 60)
	public String getClientId() {
		return this.clientId;
	}

	public void setClientId(String clientId) {
		this.clientId = clientId;
	}

	@Column(name = "SOURCE_SYSTEM_ID", length = 40)
	public String getSourceSystemId() {
		return this.sourceSystemId;
	}

	public void setSourceSystemId(String sourceSystemId) {
		this.sourceSystemId = sourceSystemId;
	}

	@Column(name = "CASE_WORKER_NAME", length = 60)
	public String getCaseWorkerName() {
		return this.caseWorkerName;
	}

	public void setCaseWorkerName(String caseWorkerName) {
		this.caseWorkerName = caseWorkerName;
	}

	@Column(name = "CASE_WORKER_PHONE", length = 20)
	public String getCaseWorkerPhone() {
		return this.caseWorkerPhone;
	}

	public void setCaseWorkerPhone(String caseWorkerPhone) {
		this.caseWorkerPhone = caseWorkerPhone;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PROCESS_TS", length = 26)
	public Date getProcessTs() {
		return this.processTs;
	}

	public void setProcessTs(Date processTs) {
		this.processTs = processTs;
	}

}
