package com.ibm.wcm.ods.dto;
// Generated May 31, 2018 4:53:55 PM by Hibernate Tools 5.2.6.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClientProfilePntySrc generated by hbm2java
 */
import com.ibm.gbs.util.Constant; 
@Entity
@Table(schema = Constant.SCHEMANAME_ODS , name = "CLIENT_PROFILE_PNTY_SRC")
public class ClientProfilePntySrc implements java.io.Serializable {

	private BigDecimal clientProfilePntySeqNum;
	private String clientId;
	private String sourceSystemId;
	private Date processTs;
	private Set<CpPntyFindingSrc> cpPntyFindingSrcs = new HashSet<CpPntyFindingSrc>(0);

	public ClientProfilePntySrc() {
	}

	public ClientProfilePntySrc(BigDecimal clientProfilePntySeqNum, String clientId, String sourceSystemId) {
		this.clientProfilePntySeqNum = clientProfilePntySeqNum;
		this.clientId = clientId;
		this.sourceSystemId = sourceSystemId;
	}

	public ClientProfilePntySrc(BigDecimal clientProfilePntySeqNum, String clientId, String sourceSystemId,
			Date processTs, Set<CpPntyFindingSrc> cpPntyFindingSrcs) {
		this.clientProfilePntySeqNum = clientProfilePntySeqNum;
		this.clientId = clientId;
		this.sourceSystemId = sourceSystemId;
		this.processTs = processTs;
		this.cpPntyFindingSrcs = cpPntyFindingSrcs;
	}

	@Id

	@Column(name = "CLIENT_PROFILE_PNTY_SEQ_NUM", unique = true, nullable = false, precision = 31, scale = 0)
	public BigDecimal getClientProfilePntySeqNum() {
		return this.clientProfilePntySeqNum;
	}

	public void setClientProfilePntySeqNum(BigDecimal clientProfilePntySeqNum) {
		this.clientProfilePntySeqNum = clientProfilePntySeqNum;
	}

	@Column(name = "CLIENT_ID", nullable = false, length = 60)
	public String getClientId() {
		return this.clientId;
	}

	public void setClientId(String clientId) {
		this.clientId = clientId;
	}

	@Column(name = "SOURCE_SYSTEM_ID", nullable = false, length = 40)
	public String getSourceSystemId() {
		return this.sourceSystemId;
	}

	public void setSourceSystemId(String sourceSystemId) {
		this.sourceSystemId = sourceSystemId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PROCESS_TS", length = 26)
	public Date getProcessTs() {
		return this.processTs;
	}

	public void setProcessTs(Date processTs) {
		this.processTs = processTs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clientProfilePntySrc")
	public Set<CpPntyFindingSrc> getCpPntyFindingSrcs() {
		return this.cpPntyFindingSrcs;
	}

	public void setCpPntyFindingSrcs(Set<CpPntyFindingSrc> cpPntyFindingSrcs) {
		this.cpPntyFindingSrcs = cpPntyFindingSrcs;
	}

}
