package com.ibm.wcm.ods.dto;
// Generated May 31, 2018 4:53:55 PM by Hibernate Tools 5.2.6.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClientProfileAsscSrc generated by hbm2java
 */
import com.ibm.gbs.util.Constant; 
@Entity
@Table(schema = Constant.SCHEMANAME_ODS , name = "CLIENT_PROFILE_ASSC_SRC")
public class ClientProfileAsscSrc implements java.io.Serializable {

	private BigDecimal clientProfileAsscSeqNum;
	private String clientId;
	private String sourceSystemId;
	private Date processTs;
	private Set<CpAsscContactSrc> cpAsscContactSrcs = new HashSet<CpAsscContactSrc>(0);

	public ClientProfileAsscSrc() {
	}

	public ClientProfileAsscSrc(BigDecimal clientProfileAsscSeqNum) {
		this.clientProfileAsscSeqNum = clientProfileAsscSeqNum;
	}

	public ClientProfileAsscSrc(BigDecimal clientProfileAsscSeqNum, String clientId, String sourceSystemId,
			Date processTs, Set<CpAsscContactSrc> cpAsscContactSrcs) {
		this.clientProfileAsscSeqNum = clientProfileAsscSeqNum;
		this.clientId = clientId;
		this.sourceSystemId = sourceSystemId;
		this.processTs = processTs;
		this.cpAsscContactSrcs = cpAsscContactSrcs;
	}

	@Id

	@Column(name = "CLIENT_PROFILE_ASSC_SEQ_NUM", unique = true, nullable = false, precision = 31, scale = 0)
	public BigDecimal getClientProfileAsscSeqNum() {
		return this.clientProfileAsscSeqNum;
	}

	public void setClientProfileAsscSeqNum(BigDecimal clientProfileAsscSeqNum) {
		this.clientProfileAsscSeqNum = clientProfileAsscSeqNum;
	}

	@Column(name = "CLIENT_ID", length = 60)
	public String getClientId() {
		return this.clientId;
	}

	public void setClientId(String clientId) {
		this.clientId = clientId;
	}

	@Column(name = "SOURCE_SYSTEM_ID", length = 40)
	public String getSourceSystemId() {
		return this.sourceSystemId;
	}

	public void setSourceSystemId(String sourceSystemId) {
		this.sourceSystemId = sourceSystemId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PROCESS_TS", length = 26)
	public Date getProcessTs() {
		return this.processTs;
	}

	public void setProcessTs(Date processTs) {
		this.processTs = processTs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clientProfileAsscSrc")
	public Set<CpAsscContactSrc> getCpAsscContactSrcs() {
		return this.cpAsscContactSrcs;
	}

	public void setCpAsscContactSrcs(Set<CpAsscContactSrc> cpAsscContactSrcs) {
		this.cpAsscContactSrcs = cpAsscContactSrcs;
	}

}
