package com.ibm.wcm.ods.dto;
// Generated May 31, 2018 4:53:55 PM by Hibernate Tools 5.2.6.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CpAdsEncounterSrc generated by hbm2java
 */
import com.ibm.gbs.util.Constant; 
@Entity
@Table(schema = Constant.SCHEMANAME_ODS , name = "CP_ADS_ENCOUNTER_SRC")
public class CpAdsEncounterSrc implements java.io.Serializable {

	private BigDecimal cpAdsEncounterSeqNum;
	private ClientProfileAdsSrc clientProfileAdsSrc;
	private String serviceAds;
	private String diagnosisForService;

	public CpAdsEncounterSrc() {
	}

	public CpAdsEncounterSrc(BigDecimal cpAdsEncounterSeqNum, ClientProfileAdsSrc clientProfileAdsSrc) {
		this.cpAdsEncounterSeqNum = cpAdsEncounterSeqNum;
		this.clientProfileAdsSrc = clientProfileAdsSrc;
	}

	public CpAdsEncounterSrc(BigDecimal cpAdsEncounterSeqNum, ClientProfileAdsSrc clientProfileAdsSrc,
			String serviceAds, String diagnosisForService) {
		this.cpAdsEncounterSeqNum = cpAdsEncounterSeqNum;
		this.clientProfileAdsSrc = clientProfileAdsSrc;
		this.serviceAds = serviceAds;
		this.diagnosisForService = diagnosisForService;
	}

	@Id

	@Column(name = "CP_ADS_ENCOUNTER_SEQ_NUM", unique = true, nullable = false, precision = 31, scale = 0)
	public BigDecimal getCpAdsEncounterSeqNum() {
		return this.cpAdsEncounterSeqNum;
	}

	public void setCpAdsEncounterSeqNum(BigDecimal cpAdsEncounterSeqNum) {
		this.cpAdsEncounterSeqNum = cpAdsEncounterSeqNum;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CLIENT_PROFILE_ADS_SEQ_NUM", nullable = false)
	public ClientProfileAdsSrc getClientProfileAdsSrc() {
		return this.clientProfileAdsSrc;
	}

	public void setClientProfileAdsSrc(ClientProfileAdsSrc clientProfileAdsSrc) {
		this.clientProfileAdsSrc = clientProfileAdsSrc;
	}

	@Column(name = "SERVICE_ADS", length = 256)
	public String getServiceAds() {
		return this.serviceAds;
	}

	public void setServiceAds(String serviceAds) {
		this.serviceAds = serviceAds;
	}

	@Column(name = "DIAGNOSIS_FOR_SERVICE", length = 512)
	public String getDiagnosisForService() {
		return this.diagnosisForService;
	}

	public void setDiagnosisForService(String diagnosisForService) {
		this.diagnosisForService = diagnosisForService;
	}

}
