package com.ibm.wcm.ods.dto;
// Generated May 31, 2018 4:53:55 PM by Hibernate Tools 5.2.6.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CpDemoPhyAddrSrc generated by hbm2java
 */
import com.ibm.gbs.util.Constant; 
@Entity
@Table(schema = Constant.SCHEMANAME_ODS , name = "CP_DEMO_PHY_ADDR_SRC")
public class CpDemoPhyAddrSrc implements java.io.Serializable {

	private BigDecimal cpDemoPhyAddrSeqNum;
	private ClientProfileDemoSrc clientProfileDemoSrc;
	private String physicalAddr;

	public CpDemoPhyAddrSrc() {
	}

	public CpDemoPhyAddrSrc(BigDecimal cpDemoPhyAddrSeqNum, ClientProfileDemoSrc clientProfileDemoSrc) {
		this.cpDemoPhyAddrSeqNum = cpDemoPhyAddrSeqNum;
		this.clientProfileDemoSrc = clientProfileDemoSrc;
	}

	public CpDemoPhyAddrSrc(BigDecimal cpDemoPhyAddrSeqNum, ClientProfileDemoSrc clientProfileDemoSrc,
			String physicalAddr) {
		this.cpDemoPhyAddrSeqNum = cpDemoPhyAddrSeqNum;
		this.clientProfileDemoSrc = clientProfileDemoSrc;
		this.physicalAddr = physicalAddr;
	}

	@Id

	@Column(name = "CP_DEMO_PHY_ADDR_SEQ_NUM", unique = true, nullable = false, precision = 31, scale = 0)
	public BigDecimal getCpDemoPhyAddrSeqNum() {
		return this.cpDemoPhyAddrSeqNum;
	}

	public void setCpDemoPhyAddrSeqNum(BigDecimal cpDemoPhyAddrSeqNum) {
		this.cpDemoPhyAddrSeqNum = cpDemoPhyAddrSeqNum;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CLIENT_PROFILE_DEMO_SEQ_NUM", nullable = false)
	public ClientProfileDemoSrc getClientProfileDemoSrc() {
		return this.clientProfileDemoSrc;
	}

	public void setClientProfileDemoSrc(ClientProfileDemoSrc clientProfileDemoSrc) {
		this.clientProfileDemoSrc = clientProfileDemoSrc;
	}

	@Column(name = "PHYSICAL_ADDR", length = 128)
	public String getPhysicalAddr() {
		return this.physicalAddr;
	}

	public void setPhysicalAddr(String physicalAddr) {
		this.physicalAddr = physicalAddr;
	}

}
