package com.ibm.wcm.ods.dto;
// Generated May 31, 2018 4:53:55 PM by Hibernate Tools 5.2.6.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CpHlthPrvdrSrc generated by hbm2java
 */
import com.ibm.gbs.util.Constant; 
@Entity
@Table(schema = Constant.SCHEMANAME_ODS , name = "CP_HLTH_PRVDR_SRC")
public class CpHlthPrvdrSrc implements java.io.Serializable {

	private BigDecimal cpHlthPrvdrSeqNum;
	private ClientProfileHlthSrc clientProfileHlthSrc;
	private String medPrvName;
	private String medPrvType;
	private String medPrvPhone;
	private Date medPrvEndDate;
	private String medPrvComments;

	public CpHlthPrvdrSrc() {
	}

	public CpHlthPrvdrSrc(BigDecimal cpHlthPrvdrSeqNum, ClientProfileHlthSrc clientProfileHlthSrc) {
		this.cpHlthPrvdrSeqNum = cpHlthPrvdrSeqNum;
		this.clientProfileHlthSrc = clientProfileHlthSrc;
	}

	public CpHlthPrvdrSrc(BigDecimal cpHlthPrvdrSeqNum, ClientProfileHlthSrc clientProfileHlthSrc, String medPrvName,
			String medPrvType, String medPrvPhone, Date medPrvEndDate, String medPrvComments) {
		this.cpHlthPrvdrSeqNum = cpHlthPrvdrSeqNum;
		this.clientProfileHlthSrc = clientProfileHlthSrc;
		this.medPrvName = medPrvName;
		this.medPrvType = medPrvType;
		this.medPrvPhone = medPrvPhone;
		this.medPrvEndDate = medPrvEndDate;
		this.medPrvComments = medPrvComments;
	}

	@Id

	@Column(name = "CP_HLTH_PRVDR_SEQ_NUM", unique = true, nullable = false, precision = 31, scale = 0)
	public BigDecimal getCpHlthPrvdrSeqNum() {
		return this.cpHlthPrvdrSeqNum;
	}

	public void setCpHlthPrvdrSeqNum(BigDecimal cpHlthPrvdrSeqNum) {
		this.cpHlthPrvdrSeqNum = cpHlthPrvdrSeqNum;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CLIENT_PROFILE_HLTH_SEQ_NUM", nullable = false)
	public ClientProfileHlthSrc getClientProfileHlthSrc() {
		return this.clientProfileHlthSrc;
	}

	public void setClientProfileHlthSrc(ClientProfileHlthSrc clientProfileHlthSrc) {
		this.clientProfileHlthSrc = clientProfileHlthSrc;
	}

	@Column(name = "MED_PRV_NAME", length = 60)
	public String getMedPrvName() {
		return this.medPrvName;
	}

	public void setMedPrvName(String medPrvName) {
		this.medPrvName = medPrvName;
	}

	@Column(name = "MED_PRV_TYPE", length = 60)
	public String getMedPrvType() {
		return this.medPrvType;
	}

	public void setMedPrvType(String medPrvType) {
		this.medPrvType = medPrvType;
	}

	@Column(name = "MED_PRV_PHONE", length = 20)
	public String getMedPrvPhone() {
		return this.medPrvPhone;
	}

	public void setMedPrvPhone(String medPrvPhone) {
		this.medPrvPhone = medPrvPhone;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MED_PRV_END_DATE", length = 10)
	public Date getMedPrvEndDate() {
		return this.medPrvEndDate;
	}

	public void setMedPrvEndDate(Date medPrvEndDate) {
		this.medPrvEndDate = medPrvEndDate;
	}

	@Column(name = "MED_PRV_COMMENTS", length = 2000)
	public String getMedPrvComments() {
		return this.medPrvComments;
	}

	public void setMedPrvComments(String medPrvComments) {
		this.medPrvComments = medPrvComments;
	}

}
