package com.ibm.wcm.ods.dto;
// Generated May 31, 2018 4:53:55 PM by Hibernate Tools 5.2.6.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CpHlthMedStatusSrc generated by hbm2java
 */
import com.ibm.gbs.util.Constant; 
@Entity
@Table(schema = Constant.SCHEMANAME_ODS , name = "CP_HLTH_MED_STATUS_SRC")
public class CpHlthMedStatusSrc implements java.io.Serializable {

	private BigDecimal cpHlthMedStatusSeqNum;
	private ClientProfileHlthSrc clientProfileHlthSrc;
	private String medCondition;
	private String immunization;

	public CpHlthMedStatusSrc() {
	}

	public CpHlthMedStatusSrc(BigDecimal cpHlthMedStatusSeqNum, ClientProfileHlthSrc clientProfileHlthSrc) {
		this.cpHlthMedStatusSeqNum = cpHlthMedStatusSeqNum;
		this.clientProfileHlthSrc = clientProfileHlthSrc;
	}

	public CpHlthMedStatusSrc(BigDecimal cpHlthMedStatusSeqNum, ClientProfileHlthSrc clientProfileHlthSrc,
			String medCondition, String immunization) {
		this.cpHlthMedStatusSeqNum = cpHlthMedStatusSeqNum;
		this.clientProfileHlthSrc = clientProfileHlthSrc;
		this.medCondition = medCondition;
		this.immunization = immunization;
	}

	@Id

	@Column(name = "CP_HLTH_MED_STATUS_SEQ_NUM", unique = true, nullable = false, precision = 31, scale = 0)
	public BigDecimal getCpHlthMedStatusSeqNum() {
		return this.cpHlthMedStatusSeqNum;
	}

	public void setCpHlthMedStatusSeqNum(BigDecimal cpHlthMedStatusSeqNum) {
		this.cpHlthMedStatusSeqNum = cpHlthMedStatusSeqNum;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CLIENT_PROFILE_HLTH_SEQ_NUM", nullable = false)
	public ClientProfileHlthSrc getClientProfileHlthSrc() {
		return this.clientProfileHlthSrc;
	}

	public void setClientProfileHlthSrc(ClientProfileHlthSrc clientProfileHlthSrc) {
		this.clientProfileHlthSrc = clientProfileHlthSrc;
	}

	@Column(name = "MED_CONDITION", length = 65)
	public String getMedCondition() {
		return this.medCondition;
	}

	public void setMedCondition(String medCondition) {
		this.medCondition = medCondition;
	}

	@Column(name = "IMMUNIZATION", length = 65)
	public String getImmunization() {
		return this.immunization;
	}

	public void setImmunization(String immunization) {
		this.immunization = immunization;
	}

}
