package com.ibm.wcm.ods.dto;
// Generated May 31, 2018 4:53:55 PM by Hibernate Tools 5.2.6.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CpHlthHospSrc generated by hbm2java
 */
import com.ibm.gbs.util.Constant; 
@Entity
@Table(schema = Constant.SCHEMANAME_ODS , name = "CP_HLTH_HOSP_SRC")
public class CpHlthHospSrc implements java.io.Serializable {

	private BigDecimal cpHlthHospSeqNum;
	private ClientProfileHlthSrc clientProfileHlthSrc;
	private String hospDates;
	private String hospName;
	private String hospNotes;
	private Date lastHospDate;

	public CpHlthHospSrc() {
	}

	public CpHlthHospSrc(BigDecimal cpHlthHospSeqNum, ClientProfileHlthSrc clientProfileHlthSrc) {
		this.cpHlthHospSeqNum = cpHlthHospSeqNum;
		this.clientProfileHlthSrc = clientProfileHlthSrc;
	}

	public CpHlthHospSrc(BigDecimal cpHlthHospSeqNum, ClientProfileHlthSrc clientProfileHlthSrc, String hospDates,
			String hospName, String hospNotes, Date lastHospDate) {
		this.cpHlthHospSeqNum = cpHlthHospSeqNum;
		this.clientProfileHlthSrc = clientProfileHlthSrc;
		this.hospDates = hospDates;
		this.hospName = hospName;
		this.hospNotes = hospNotes;
		this.lastHospDate = lastHospDate;
	}

	@Id

	@Column(name = "CP_HLTH_HOSP_SEQ_NUM", unique = true, nullable = false, precision = 31, scale = 0)
	public BigDecimal getCpHlthHospSeqNum() {
		return this.cpHlthHospSeqNum;
	}

	public void setCpHlthHospSeqNum(BigDecimal cpHlthHospSeqNum) {
		this.cpHlthHospSeqNum = cpHlthHospSeqNum;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CLIENT_PROFILE_HLTH_SEQ_NUM", nullable = false)
	public ClientProfileHlthSrc getClientProfileHlthSrc() {
		return this.clientProfileHlthSrc;
	}

	public void setClientProfileHlthSrc(ClientProfileHlthSrc clientProfileHlthSrc) {
		this.clientProfileHlthSrc = clientProfileHlthSrc;
	}

	@Column(name = "HOSP_DATES", length = 60)
	public String getHospDates() {
		return this.hospDates;
	}

	public void setHospDates(String hospDates) {
		this.hospDates = hospDates;
	}

	@Column(name = "HOSP_NAME", length = 100)
	public String getHospName() {
		return this.hospName;
	}

	public void setHospName(String hospName) {
		this.hospName = hospName;
	}

	@Column(name = "HOSP_NOTES", length = 2000)
	public String getHospNotes() {
		return this.hospNotes;
	}

	public void setHospNotes(String hospNotes) {
		this.hospNotes = hospNotes;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_HOSP_DATE", length = 10)
	public Date getLastHospDate() {
		return this.lastHospDate;
	}

	public void setLastHospDate(Date lastHospDate) {
		this.lastHospDate = lastHospDate;
	}

}
