package com.ibm.wcm.ods.dto;
// Generated May 31, 2018 4:53:55 PM by Hibernate Tools 5.2.6.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CpHlthTestSrc generated by hbm2java
 */
import com.ibm.gbs.util.Constant; 
@Entity
@Table(schema = Constant.SCHEMANAME_ODS , name = "CP_HLTH_TEST_SRC")
public class CpHlthTestSrc implements java.io.Serializable {

	private BigDecimal cpHlthTestSeqNum;
	private ClientProfileHlthSrc clientProfileHlthSrc;
	private Date tbSkinTestDate;
	private String tbSkinTestResult;
	private String tbBloodTest;
	private Date tbBloodTestDate;
	private String tbBloodTestResult;
	private String tbXrayResult;
	private String tbProg;
	private String testProgram;
	private String testType;
	private Date testDate;
	private String testResults;
	private String testInterpretation;
	private String testName;

	public CpHlthTestSrc() {
	}

	public CpHlthTestSrc(BigDecimal cpHlthTestSeqNum, ClientProfileHlthSrc clientProfileHlthSrc) {
		this.cpHlthTestSeqNum = cpHlthTestSeqNum;
		this.clientProfileHlthSrc = clientProfileHlthSrc;
	}

	public CpHlthTestSrc(BigDecimal cpHlthTestSeqNum, ClientProfileHlthSrc clientProfileHlthSrc, Date tbSkinTestDate,
			String tbSkinTestResult, String tbBloodTest, Date tbBloodTestDate, String tbBloodTestResult,
			String tbXrayResult, String tbProg, String testProgram, String testType, Date testDate, String testResults,
			String testInterpretation, String testName) {
		this.cpHlthTestSeqNum = cpHlthTestSeqNum;
		this.clientProfileHlthSrc = clientProfileHlthSrc;
		this.tbSkinTestDate = tbSkinTestDate;
		this.tbSkinTestResult = tbSkinTestResult;
		this.tbBloodTest = tbBloodTest;
		this.tbBloodTestDate = tbBloodTestDate;
		this.tbBloodTestResult = tbBloodTestResult;
		this.tbXrayResult = tbXrayResult;
		this.tbProg = tbProg;
		this.testProgram = testProgram;
		this.testType = testType;
		this.testDate = testDate;
		this.testResults = testResults;
		this.testInterpretation = testInterpretation;
		this.testName = testName;
	}

	@Id

	@Column(name = "CP_HLTH_TEST_SEQ_NUM", unique = true, nullable = false, precision = 31, scale = 0)
	public BigDecimal getCpHlthTestSeqNum() {
		return this.cpHlthTestSeqNum;
	}

	public void setCpHlthTestSeqNum(BigDecimal cpHlthTestSeqNum) {
		this.cpHlthTestSeqNum = cpHlthTestSeqNum;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CLIENT_PROFILE_HLTH_SEQ_NUM", nullable = false)
	public ClientProfileHlthSrc getClientProfileHlthSrc() {
		return this.clientProfileHlthSrc;
	}

	public void setClientProfileHlthSrc(ClientProfileHlthSrc clientProfileHlthSrc) {
		this.clientProfileHlthSrc = clientProfileHlthSrc;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TB_SKIN_TEST_DATE", length = 10)
	public Date getTbSkinTestDate() {
		return this.tbSkinTestDate;
	}

	public void setTbSkinTestDate(Date tbSkinTestDate) {
		this.tbSkinTestDate = tbSkinTestDate;
	}

	@Column(name = "TB_SKIN_TEST_RESULT", length = 40)
	public String getTbSkinTestResult() {
		return this.tbSkinTestResult;
	}

	public void setTbSkinTestResult(String tbSkinTestResult) {
		this.tbSkinTestResult = tbSkinTestResult;
	}

	@Column(name = "TB_BLOOD_TEST", length = 40)
	public String getTbBloodTest() {
		return this.tbBloodTest;
	}

	public void setTbBloodTest(String tbBloodTest) {
		this.tbBloodTest = tbBloodTest;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TB_BLOOD_TEST_DATE", length = 10)
	public Date getTbBloodTestDate() {
		return this.tbBloodTestDate;
	}

	public void setTbBloodTestDate(Date tbBloodTestDate) {
		this.tbBloodTestDate = tbBloodTestDate;
	}

	@Column(name = "TB_BLOOD_TEST_RESULT", length = 6)
	public String getTbBloodTestResult() {
		return this.tbBloodTestResult;
	}

	public void setTbBloodTestResult(String tbBloodTestResult) {
		this.tbBloodTestResult = tbBloodTestResult;
	}

	@Column(name = "TB_XRAY_RESULT", length = 40)
	public String getTbXrayResult() {
		return this.tbXrayResult;
	}

	public void setTbXrayResult(String tbXrayResult) {
		this.tbXrayResult = tbXrayResult;
	}

	@Column(name = "TB_PROG", length = 40)
	public String getTbProg() {
		return this.tbProg;
	}

	public void setTbProg(String tbProg) {
		this.tbProg = tbProg;
	}

	@Column(name = "TEST_PROGRAM", length = 256)
	public String getTestProgram() {
		return this.testProgram;
	}

	public void setTestProgram(String testProgram) {
		this.testProgram = testProgram;
	}

	@Column(name = "TEST_TYPE", length = 40)
	public String getTestType() {
		return this.testType;
	}

	public void setTestType(String testType) {
		this.testType = testType;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TEST_DATE", length = 10)
	public Date getTestDate() {
		return this.testDate;
	}

	public void setTestDate(Date testDate) {
		this.testDate = testDate;
	}

	@Column(name = "TEST_RESULTS", length = 40)
	public String getTestResults() {
		return this.testResults;
	}

	public void setTestResults(String testResults) {
		this.testResults = testResults;
	}

	@Column(name = "TEST_INTERPRETATION", length = 40)
	public String getTestInterpretation() {
		return this.testInterpretation;
	}

	public void setTestInterpretation(String testInterpretation) {
		this.testInterpretation = testInterpretation;
	}

	@Column(name = "TEST_NAME", length = 100)
	public String getTestName() {
		return this.testName;
	}

	public void setTestName(String testName) {
		this.testName = testName;
	}

}
