package com.ibm.wcm.ods.dto;
// Generated May 31, 2018 4:53:55 PM by Hibernate Tools 5.2.6.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CpHlthInstSrc generated by hbm2java
 */
import com.ibm.gbs.util.Constant; 
@Entity
@Table(schema = Constant.SCHEMANAME_ODS , name = "CP_HLTH_INST_SRC")
public class CpHlthInstSrc implements java.io.Serializable {

	private BigDecimal cpHlthInstSeqNum;
	private ClientProfileHlthSrc clientProfileHlthSrc;
	private String instCare;
	private Date admitDate;
	private Date dischargeDate;
	private String instName;

	public CpHlthInstSrc() {
	}

	public CpHlthInstSrc(BigDecimal cpHlthInstSeqNum, ClientProfileHlthSrc clientProfileHlthSrc) {
		this.cpHlthInstSeqNum = cpHlthInstSeqNum;
		this.clientProfileHlthSrc = clientProfileHlthSrc;
	}

	public CpHlthInstSrc(BigDecimal cpHlthInstSeqNum, ClientProfileHlthSrc clientProfileHlthSrc, String instCare,
			Date admitDate, Date dischargeDate, String instName) {
		this.cpHlthInstSeqNum = cpHlthInstSeqNum;
		this.clientProfileHlthSrc = clientProfileHlthSrc;
		this.instCare = instCare;
		this.admitDate = admitDate;
		this.dischargeDate = dischargeDate;
		this.instName = instName;
	}

	@Id

	@Column(name = "CP_HLTH_INST_SEQ_NUM", unique = true, nullable = false, precision = 31, scale = 0)
	public BigDecimal getCpHlthInstSeqNum() {
		return this.cpHlthInstSeqNum;
	}

	public void setCpHlthInstSeqNum(BigDecimal cpHlthInstSeqNum) {
		this.cpHlthInstSeqNum = cpHlthInstSeqNum;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CLIENT_PROFILE_HLTH_SEQ_NUM", nullable = false)
	public ClientProfileHlthSrc getClientProfileHlthSrc() {
		return this.clientProfileHlthSrc;
	}

	public void setClientProfileHlthSrc(ClientProfileHlthSrc clientProfileHlthSrc) {
		this.clientProfileHlthSrc = clientProfileHlthSrc;
	}

	@Column(name = "INST_CARE", length = 30)
	public String getInstCare() {
		return this.instCare;
	}

	public void setInstCare(String instCare) {
		this.instCare = instCare;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ADMIT_DATE", length = 10)
	public Date getAdmitDate() {
		return this.admitDate;
	}

	public void setAdmitDate(Date admitDate) {
		this.admitDate = admitDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DISCHARGE_DATE", length = 10)
	public Date getDischargeDate() {
		return this.dischargeDate;
	}

	public void setDischargeDate(Date dischargeDate) {
		this.dischargeDate = dischargeDate;
	}

	@Column(name = "INST_NAME", length = 40)
	public String getInstName() {
		return this.instName;
	}

	public void setInstName(String instName) {
		this.instName = instName;
	}

}
