package com.ibm.wcm.ods.dto;
// Generated May 31, 2018 4:53:55 PM by Hibernate Tools 5.2.6.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CpPntyFindingSrc generated by hbm2java
 */
import com.ibm.gbs.util.Constant; 
@Entity
@Table(schema = Constant.SCHEMANAME_ODS , name = "CP_PNTY_FINDING_SRC")
public class CpPntyFindingSrc implements java.io.Serializable {

	private BigDecimal cpPntyFindingSeqNum;
	private ClientProfilePntySrc clientProfilePntySrc;
	private String fatherFirstName;
	private String fatherLastName;
	private String lglDesigPnty;
	private Date testDate;
	private String finding;
	private Date findingDate;
	private String comments;

	public CpPntyFindingSrc() {
	}

	public CpPntyFindingSrc(BigDecimal cpPntyFindingSeqNum, ClientProfilePntySrc clientProfilePntySrc) {
		this.cpPntyFindingSeqNum = cpPntyFindingSeqNum;
		this.clientProfilePntySrc = clientProfilePntySrc;
	}

	public CpPntyFindingSrc(BigDecimal cpPntyFindingSeqNum, ClientProfilePntySrc clientProfilePntySrc,
			String fatherFirstName, String fatherLastName, String lglDesigPnty, Date testDate, String finding,
			Date findingDate, String comments) {
		this.cpPntyFindingSeqNum = cpPntyFindingSeqNum;
		this.clientProfilePntySrc = clientProfilePntySrc;
		this.fatherFirstName = fatherFirstName;
		this.fatherLastName = fatherLastName;
		this.lglDesigPnty = lglDesigPnty;
		this.testDate = testDate;
		this.finding = finding;
		this.findingDate = findingDate;
		this.comments = comments;
	}

	@Id

	@Column(name = "CP_PNTY_FINDING_SEQ_NUM", unique = true, nullable = false, precision = 31, scale = 0)
	public BigDecimal getCpPntyFindingSeqNum() {
		return this.cpPntyFindingSeqNum;
	}

	public void setCpPntyFindingSeqNum(BigDecimal cpPntyFindingSeqNum) {
		this.cpPntyFindingSeqNum = cpPntyFindingSeqNum;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CLIENT_PROFILE_PNTY_SEQ_NUM", nullable = false)
	public ClientProfilePntySrc getClientProfilePntySrc() {
		return this.clientProfilePntySrc;
	}

	public void setClientProfilePntySrc(ClientProfilePntySrc clientProfilePntySrc) {
		this.clientProfilePntySrc = clientProfilePntySrc;
	}

	@Column(name = "FATHER_FIRST_NAME", length = 30)
	public String getFatherFirstName() {
		return this.fatherFirstName;
	}

	public void setFatherFirstName(String fatherFirstName) {
		this.fatherFirstName = fatherFirstName;
	}

	@Column(name = "FATHER_LAST_NAME", length = 30)
	public String getFatherLastName() {
		return this.fatherLastName;
	}

	public void setFatherLastName(String fatherLastName) {
		this.fatherLastName = fatherLastName;
	}

	@Column(name = "LGL_DESIG_PNTY", length = 30)
	public String getLglDesigPnty() {
		return this.lglDesigPnty;
	}

	public void setLglDesigPnty(String lglDesigPnty) {
		this.lglDesigPnty = lglDesigPnty;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TEST_DATE", length = 10)
	public Date getTestDate() {
		return this.testDate;
	}

	public void setTestDate(Date testDate) {
		this.testDate = testDate;
	}

	@Column(name = "FINDING", length = 60)
	public String getFinding() {
		return this.finding;
	}

	public void setFinding(String finding) {
		this.finding = finding;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FINDING_DATE", length = 10)
	public Date getFindingDate() {
		return this.findingDate;
	}

	public void setFindingDate(Date findingDate) {
		this.findingDate = findingDate;
	}

	@Column(name = "COMMENTS", length = 512)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

}
