package com.ibm.wcm.ods.dto;
// Generated May 31, 2018 4:53:55 PM by Hibernate Tools 5.2.6.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CpPsaEncounterSrc generated by hbm2java
 */
import com.ibm.gbs.util.Constant; 
@Entity
@Table(schema = Constant.SCHEMANAME_ODS , name = "CP_PSA_ENCOUNTER_SRC")
public class CpPsaEncounterSrc implements java.io.Serializable {

	private BigDecimal cpPsaEncounterSeqNum;
	private ClientProfilePsaSrc clientProfilePsaSrc;
	private String protectiveIssueConcerns;
	private String service;
	private Date serviceDate;

	public CpPsaEncounterSrc() {
	}

	public CpPsaEncounterSrc(BigDecimal cpPsaEncounterSeqNum, ClientProfilePsaSrc clientProfilePsaSrc) {
		this.cpPsaEncounterSeqNum = cpPsaEncounterSeqNum;
		this.clientProfilePsaSrc = clientProfilePsaSrc;
	}

	public CpPsaEncounterSrc(BigDecimal cpPsaEncounterSeqNum, ClientProfilePsaSrc clientProfilePsaSrc,
			String protectiveIssueConcerns, String service, Date serviceDate) {
		this.cpPsaEncounterSeqNum = cpPsaEncounterSeqNum;
		this.clientProfilePsaSrc = clientProfilePsaSrc;
		this.protectiveIssueConcerns = protectiveIssueConcerns;
		this.service = service;
		this.serviceDate = serviceDate;
	}

	@Id

	@Column(name = "CP_PSA_ENCOUNTER_SEQ_NUM", unique = true, nullable = false, precision = 31, scale = 0)
	public BigDecimal getCpPsaEncounterSeqNum() {
		return this.cpPsaEncounterSeqNum;
	}

	public void setCpPsaEncounterSeqNum(BigDecimal cpPsaEncounterSeqNum) {
		this.cpPsaEncounterSeqNum = cpPsaEncounterSeqNum;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CLIENT_PROFILE_PSA_SEQ_NUM", nullable = false)
	public ClientProfilePsaSrc getClientProfilePsaSrc() {
		return this.clientProfilePsaSrc;
	}

	public void setClientProfilePsaSrc(ClientProfilePsaSrc clientProfilePsaSrc) {
		this.clientProfilePsaSrc = clientProfilePsaSrc;
	}

	@Column(name = "PROTECTIVE_ISSUE_CONCERNS", length = 2000)
	public String getProtectiveIssueConcerns() {
		return this.protectiveIssueConcerns;
	}

	public void setProtectiveIssueConcerns(String protectiveIssueConcerns) {
		this.protectiveIssueConcerns = protectiveIssueConcerns;
	}

	@Column(name = "SERVICE", length = 2000)
	public String getService() {
		return this.service;
	}

	public void setService(String service) {
		this.service = service;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SERVICE_DATE", length = 10)
	public Date getServiceDate() {
		return this.serviceDate;
	}

	public void setServiceDate(Date serviceDate) {
		this.serviceDate = serviceDate;
	}

}
