package com.ibm.wcm.ods.dto;
// Generated May 31, 2018 4:53:55 PM by Hibernate Tools 5.2.6.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * InitloadClientPhoneTgt generated by hbm2java
 */
import com.ibm.gbs.util.Constant; 
@Entity
@Table(schema = Constant.SCHEMANAME_ODS , name = "INITLOAD_CLIENT_PHONE_TGT")
public class InitloadClientPhoneTgt implements java.io.Serializable {

	private BigDecimal clientPhoneSeqNum;
	private InitloadClientTgt initloadClientTgt;
	private String phoneType;
	private String phoneNum;

	public InitloadClientPhoneTgt() {
	}

	public InitloadClientPhoneTgt(BigDecimal clientPhoneSeqNum, InitloadClientTgt initloadClientTgt, String phoneType,
			String phoneNum) {
		this.clientPhoneSeqNum = clientPhoneSeqNum;
		this.initloadClientTgt = initloadClientTgt;
		this.phoneType = phoneType;
		this.phoneNum = phoneNum;
	}

	@Id

	@Column(name = "CLIENT_PHONE_SEQ_NUM", unique = true, nullable = false, precision = 31, scale = 0)
	public BigDecimal getClientPhoneSeqNum() {
		return this.clientPhoneSeqNum;
	}

	public void setClientPhoneSeqNum(BigDecimal clientPhoneSeqNum) {
		this.clientPhoneSeqNum = clientPhoneSeqNum;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CLIENT_TRANSACTION_SEQ_NUM", nullable = false)
	public InitloadClientTgt getInitloadClientTgt() {
		return this.initloadClientTgt;
	}

	public void setInitloadClientTgt(InitloadClientTgt initloadClientTgt) {
		this.initloadClientTgt = initloadClientTgt;
	}

	@Column(name = "PHONE_TYPE", nullable = false, length = 20)
	public String getPhoneType() {
		return this.phoneType;
	}

	public void setPhoneType(String phoneType) {
		this.phoneType = phoneType;
	}

	@Column(name = "PHONE_NUM", nullable = false, length = 60)
	public String getPhoneNum() {
		return this.phoneNum;
	}

	public void setPhoneNum(String phoneNum) {
		this.phoneNum = phoneNum;
	}

}
