package com.ibm.wcm.ods.dto;
// Generated May 31, 2018 4:53:55 PM by Hibernate Tools 5.2.6.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MvVwcosdieClientId generated by hbm2java
 */
@Embeddable
public class MvVwcosdieClientId implements java.io.Serializable {

	private BigDecimal soaProcessingSeq;
	private String sourceSysId;
	private Integer clientId;
	private String privRec;
	private String firstNm;
	private String lastNm;
	private String middleNm;
	private Date dob;
	private String ssn;
	private String priEmailAdr;
	private String altEmailAdr;
	private String ethnicity;
	private String gender;
	private String resStatus;
	private String priLang;
	private String priLangAbil;
	private String secLang;
	private String secLangAbil;
	private String popType;
	private String aliasNm;
	private Date lastUpdDtm;

	public MvVwcosdieClientId() {
	}

	public MvVwcosdieClientId(String firstNm, String lastNm, Date dob, String gender) {
		this.firstNm = firstNm;
		this.lastNm = lastNm;
		this.dob = dob;
		this.gender = gender;
	}

	public MvVwcosdieClientId(BigDecimal soaProcessingSeq, String sourceSysId, Integer clientId, String privRec,
			String firstNm, String lastNm, String middleNm, Date dob, String ssn, String priEmailAdr,
			String altEmailAdr, String ethnicity, String gender, String resStatus, String priLang, String priLangAbil,
			String secLang, String secLangAbil, String popType, String aliasNm, Date lastUpdDtm) {
		this.soaProcessingSeq = soaProcessingSeq;
		this.sourceSysId = sourceSysId;
		this.clientId = clientId;
		this.privRec = privRec;
		this.firstNm = firstNm;
		this.lastNm = lastNm;
		this.middleNm = middleNm;
		this.dob = dob;
		this.ssn = ssn;
		this.priEmailAdr = priEmailAdr;
		this.altEmailAdr = altEmailAdr;
		this.ethnicity = ethnicity;
		this.gender = gender;
		this.resStatus = resStatus;
		this.priLang = priLang;
		this.priLangAbil = priLangAbil;
		this.secLang = secLang;
		this.secLangAbil = secLangAbil;
		this.popType = popType;
		this.aliasNm = aliasNm;
		this.lastUpdDtm = lastUpdDtm;
	}

	@Column(name = "SOA_PROCESSING_SEQ", precision = 31, scale = 0)
	public BigDecimal getSoaProcessingSeq() {
		return this.soaProcessingSeq;
	}

	public void setSoaProcessingSeq(BigDecimal soaProcessingSeq) {
		this.soaProcessingSeq = soaProcessingSeq;
	}

	@Column(name = "SOURCE_SYS_ID", length = 18)
	public String getSourceSysId() {
		return this.sourceSysId;
	}

	public void setSourceSysId(String sourceSysId) {
		this.sourceSysId = sourceSysId;
	}

	@Column(name = "CLIENT_ID", precision = 9, scale = 0)
	public Integer getClientId() {
		return this.clientId;
	}

	public void setClientId(Integer clientId) {
		this.clientId = clientId;
	}

	@Column(name = "PRIV_REC", length = 3)
	public String getPrivRec() {
		return this.privRec;
	}

	public void setPrivRec(String privRec) {
		this.privRec = privRec;
	}

	@Column(name = "FIRST_NM", nullable = false, length = 75)
	public String getFirstNm() {
		return this.firstNm;
	}

	public void setFirstNm(String firstNm) {
		this.firstNm = firstNm;
	}

	@Column(name = "LAST_NM", nullable = false, length = 75)
	public String getLastNm() {
		return this.lastNm;
	}

	public void setLastNm(String lastNm) {
		this.lastNm = lastNm;
	}

	@Column(name = "MIDDLE_NM", length = 3)
	public String getMiddleNm() {
		return this.middleNm;
	}

	public void setMiddleNm(String middleNm) {
		this.middleNm = middleNm;
	}

	@Column(name = "DOB", nullable = false, length = 10)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Column(name = "SSN", length = 33)
	public String getSsn() {
		return this.ssn;
	}

	public void setSsn(String ssn) {
		this.ssn = ssn;
	}

	@Column(name = "PRI_EMAIL_ADR", length = 225)
	public String getPriEmailAdr() {
		return this.priEmailAdr;
	}

	public void setPriEmailAdr(String priEmailAdr) {
		this.priEmailAdr = priEmailAdr;
	}

	@Column(name = "ALT_EMAIL_ADR", length = 75)
	public String getAltEmailAdr() {
		return this.altEmailAdr;
	}

	public void setAltEmailAdr(String altEmailAdr) {
		this.altEmailAdr = altEmailAdr;
	}

	@Column(name = "ETHNICITY", length = 177)
	public String getEthnicity() {
		return this.ethnicity;
	}

	public void setEthnicity(String ethnicity) {
		this.ethnicity = ethnicity;
	}

	@Column(name = "GENDER", nullable = false, length = 3)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "RES_STATUS", length = 3)
	public String getResStatus() {
		return this.resStatus;
	}

	public void setResStatus(String resStatus) {
		this.resStatus = resStatus;
	}

	@Column(name = "PRI_LANG", length = 6)
	public String getPriLang() {
		return this.priLang;
	}

	public void setPriLang(String priLang) {
		this.priLang = priLang;
	}

	@Column(name = "PRI_LANG_ABIL", length = 50)
	public String getPriLangAbil() {
		return this.priLangAbil;
	}

	public void setPriLangAbil(String priLangAbil) {
		this.priLangAbil = priLangAbil;
	}

	@Column(name = "SEC_LANG", length = 50)
	public String getSecLang() {
		return this.secLang;
	}

	public void setSecLang(String secLang) {
		this.secLang = secLang;
	}

	@Column(name = "SEC_LANG_ABIL", length = 50)
	public String getSecLangAbil() {
		return this.secLangAbil;
	}

	public void setSecLangAbil(String secLangAbil) {
		this.secLangAbil = secLangAbil;
	}

	@Column(name = "POP_TYPE", length = 50)
	public String getPopType() {
		return this.popType;
	}

	public void setPopType(String popType) {
		this.popType = popType;
	}

	@Column(name = "ALIAS_NM", length = 25)
	public String getAliasNm() {
		return this.aliasNm;
	}

	public void setAliasNm(String aliasNm) {
		this.aliasNm = aliasNm;
	}

	@Column(name = "LAST_UPD_DTM", length = 10)
	public Date getLastUpdDtm() {
		return this.lastUpdDtm;
	}

	public void setLastUpdDtm(Date lastUpdDtm) {
		this.lastUpdDtm = lastUpdDtm;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MvVwcosdieClientId))
			return false;
		MvVwcosdieClientId castOther = (MvVwcosdieClientId) other;

		return ((this.getSoaProcessingSeq() == castOther.getSoaProcessingSeq())
				|| (this.getSoaProcessingSeq() != null && castOther.getSoaProcessingSeq() != null
						&& this.getSoaProcessingSeq().equals(castOther.getSoaProcessingSeq())))
				&& ((this.getSourceSysId() == castOther.getSourceSysId())
						|| (this.getSourceSysId() != null && castOther.getSourceSysId() != null
								&& this.getSourceSysId().equals(castOther.getSourceSysId())))
				&& ((this.getClientId() == castOther.getClientId()) || (this.getClientId() != null
						&& castOther.getClientId() != null && this.getClientId().equals(castOther.getClientId())))
				&& ((this.getPrivRec() == castOther.getPrivRec()) || (this.getPrivRec() != null
						&& castOther.getPrivRec() != null && this.getPrivRec().equals(castOther.getPrivRec())))
				&& ((this.getFirstNm() == castOther.getFirstNm()) || (this.getFirstNm() != null
						&& castOther.getFirstNm() != null && this.getFirstNm().equals(castOther.getFirstNm())))
				&& ((this.getLastNm() == castOther.getLastNm()) || (this.getLastNm() != null
						&& castOther.getLastNm() != null && this.getLastNm().equals(castOther.getLastNm())))
				&& ((this.getMiddleNm() == castOther.getMiddleNm()) || (this.getMiddleNm() != null
						&& castOther.getMiddleNm() != null && this.getMiddleNm().equals(castOther.getMiddleNm())))
				&& ((this.getDob() == castOther.getDob()) || (this.getDob() != null && castOther.getDob() != null
						&& this.getDob().equals(castOther.getDob())))
				&& ((this.getSsn() == castOther.getSsn()) || (this.getSsn() != null && castOther.getSsn() != null
						&& this.getSsn().equals(castOther.getSsn())))
				&& ((this.getPriEmailAdr() == castOther.getPriEmailAdr())
						|| (this.getPriEmailAdr() != null && castOther.getPriEmailAdr() != null
								&& this.getPriEmailAdr().equals(castOther.getPriEmailAdr())))
				&& ((this.getAltEmailAdr() == castOther.getAltEmailAdr())
						|| (this.getAltEmailAdr() != null && castOther.getAltEmailAdr() != null
								&& this.getAltEmailAdr().equals(castOther.getAltEmailAdr())))
				&& ((this.getEthnicity() == castOther.getEthnicity()) || (this.getEthnicity() != null
						&& castOther.getEthnicity() != null && this.getEthnicity().equals(castOther.getEthnicity())))
				&& ((this.getGender() == castOther.getGender()) || (this.getGender() != null
						&& castOther.getGender() != null && this.getGender().equals(castOther.getGender())))
				&& ((this.getResStatus() == castOther.getResStatus()) || (this.getResStatus() != null
						&& castOther.getResStatus() != null && this.getResStatus().equals(castOther.getResStatus())))
				&& ((this.getPriLang() == castOther.getPriLang()) || (this.getPriLang() != null
						&& castOther.getPriLang() != null && this.getPriLang().equals(castOther.getPriLang())))
				&& ((this.getPriLangAbil() == castOther.getPriLangAbil())
						|| (this.getPriLangAbil() != null && castOther.getPriLangAbil() != null
								&& this.getPriLangAbil().equals(castOther.getPriLangAbil())))
				&& ((this.getSecLang() == castOther.getSecLang()) || (this.getSecLang() != null
						&& castOther.getSecLang() != null && this.getSecLang().equals(castOther.getSecLang())))
				&& ((this.getSecLangAbil() == castOther.getSecLangAbil())
						|| (this.getSecLangAbil() != null && castOther.getSecLangAbil() != null
								&& this.getSecLangAbil().equals(castOther.getSecLangAbil())))
				&& ((this.getPopType() == castOther.getPopType()) || (this.getPopType() != null
						&& castOther.getPopType() != null && this.getPopType().equals(castOther.getPopType())))
				&& ((this.getAliasNm() == castOther.getAliasNm()) || (this.getAliasNm() != null
						&& castOther.getAliasNm() != null && this.getAliasNm().equals(castOther.getAliasNm())))
				&& ((this.getLastUpdDtm() == castOther.getLastUpdDtm())
						|| (this.getLastUpdDtm() != null && castOther.getLastUpdDtm() != null
								&& this.getLastUpdDtm().equals(castOther.getLastUpdDtm())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSoaProcessingSeq() == null ? 0 : this.getSoaProcessingSeq().hashCode());
		result = 37 * result + (getSourceSysId() == null ? 0 : this.getSourceSysId().hashCode());
		result = 37 * result + (getClientId() == null ? 0 : this.getClientId().hashCode());
		result = 37 * result + (getPrivRec() == null ? 0 : this.getPrivRec().hashCode());
		result = 37 * result + (getFirstNm() == null ? 0 : this.getFirstNm().hashCode());
		result = 37 * result + (getLastNm() == null ? 0 : this.getLastNm().hashCode());
		result = 37 * result + (getMiddleNm() == null ? 0 : this.getMiddleNm().hashCode());
		result = 37 * result + (getDob() == null ? 0 : this.getDob().hashCode());
		result = 37 * result + (getSsn() == null ? 0 : this.getSsn().hashCode());
		result = 37 * result + (getPriEmailAdr() == null ? 0 : this.getPriEmailAdr().hashCode());
		result = 37 * result + (getAltEmailAdr() == null ? 0 : this.getAltEmailAdr().hashCode());
		result = 37 * result + (getEthnicity() == null ? 0 : this.getEthnicity().hashCode());
		result = 37 * result + (getGender() == null ? 0 : this.getGender().hashCode());
		result = 37 * result + (getResStatus() == null ? 0 : this.getResStatus().hashCode());
		result = 37 * result + (getPriLang() == null ? 0 : this.getPriLang().hashCode());
		result = 37 * result + (getPriLangAbil() == null ? 0 : this.getPriLangAbil().hashCode());
		result = 37 * result + (getSecLang() == null ? 0 : this.getSecLang().hashCode());
		result = 37 * result + (getSecLangAbil() == null ? 0 : this.getSecLangAbil().hashCode());
		result = 37 * result + (getPopType() == null ? 0 : this.getPopType().hashCode());
		result = 37 * result + (getAliasNm() == null ? 0 : this.getAliasNm().hashCode());
		result = 37 * result + (getLastUpdDtm() == null ? 0 : this.getLastUpdDtm().hashCode());
		return result;
	}

}
