/* Licensed Materials - 
 Property of IBM 6949 - 67L 
 Copyright IBM Corp. 2017, 2018 All Rights Reserved */
package  com.ibm.gbs.auth.model;
// Generated Sep 21, 2017 1:52:20 PM by Hibernate Tools 5.1.0.Beta1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.ibm.gbs.util.Constant;

/**
 * Cosdconsentexception generated by hbm2java
 */
@Entity
@Table(name = "cosdconsentexception", schema = Constant.SCHEMANAME )
public class Cosdconsentexception implements java.io.Serializable {

	private BigDecimal consentexceptionid;
	private Cosdconsentgroup cosdconsentgroup;
	private Cosdpersonconsent cosdpersonconsent;
	private String createdby;
	private Date createdon;
	private String lastupdatedby;
	private Date lastupdatedo;

	public Cosdconsentexception() {
	}

	public Cosdconsentexception(BigDecimal consentexceptionid) {
		this.consentexceptionid = consentexceptionid;
	}

	public Cosdconsentexception(BigDecimal consentexceptionid, Cosdconsentgroup cosdconsentgroup,
			Cosdpersonconsent cosdpersonconsent, String createdby, Date createdon, String lastupdatedby,
			Date lastupdatedo) {
		this.consentexceptionid = consentexceptionid;
		this.cosdconsentgroup = cosdconsentgroup;
		this.cosdpersonconsent = cosdpersonconsent;
		this.createdby = createdby;
		this.createdon = createdon;
		this.lastupdatedby = lastupdatedby;
		this.lastupdatedo = lastupdatedo;
	}

	@Id
	@SequenceGenerator(name = "consentexcptSeq", sequenceName = "consentexcptSeq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="consentexcptSeq")	
	@Column(name = "consentexceptionid", unique = true, nullable = false, scale = 0)
	public BigDecimal getConsentexceptionid() {
		return this.consentexceptionid;
	}

	public void setConsentexceptionid(BigDecimal consentexceptionid) {
		this.consentexceptionid = consentexceptionid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "consentgroupid")
	public Cosdconsentgroup getCosdconsentgroup() {
		return this.cosdconsentgroup;
	}

	public void setCosdconsentgroup(Cosdconsentgroup cosdconsentgroup) {
		this.cosdconsentgroup = cosdconsentgroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "personconsentid")
	public Cosdpersonconsent getCosdpersonconsent() {
		return this.cosdpersonconsent;
	}

	public void setCosdpersonconsent(Cosdpersonconsent cosdpersonconsent) {
		this.cosdpersonconsent = cosdpersonconsent;
	}

	@Column(name = "createdby", length = 64)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdon", length = 13)
	public Date getCreatedon() {
		return this.createdon;
	}

	public void setCreatedon(Date createdon) {
		this.createdon = createdon;
	}

	@Column(name = "lastupdatedby", length = 64)
	public String getLastupdatedby() {
		return this.lastupdatedby;
	}

	public void setLastupdatedby(String lastupdatedby) {
		this.lastupdatedby = lastupdatedby;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "lastupdatedo", length = 13)
	public Date getLastupdatedo() {
		return this.lastupdatedo;
	}

	public void setLastupdatedo(Date lastupdatedo) {
		this.lastupdatedo = lastupdatedo;
	}

}
