/* Licensed Materials - 
 Property of IBM 6949 - 67L 
 Copyright IBM Corp. 2017, 2018 All Rights Reserved */
package  com.ibm.gbs.auth.model;
// Generated Sep 21, 2017 1:52:20 PM by Hibernate Tools 5.1.0.Beta1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.ibm.gbs.util.Constant;

/**
 * Cosdabaccontrolobject generated by hbm2java
 */
@Entity
@Table(name = "cosdabaccontrolobject", schema = Constant.SCHEMANAME)
public class Cosdabaccontrolobject implements java.io.Serializable {
	         
	private BigDecimal controlobjectid;
	private Cosdabacconstraint cosdabacconstraint;
	private Cosdabaccontrolgroup cosdabaccontrolgroup;
	private Cosdabactransaction cosdabactransaction;
	private String createdby;
	private Date createdon;
	private String lastupdatedby;
	private Date lastupdatedon;

	public Cosdabaccontrolobject() {
	}

	public Cosdabaccontrolobject(BigDecimal controlobjectid) {
		this.controlobjectid = controlobjectid;
	}

	public Cosdabaccontrolobject(BigDecimal controlobjectid, Cosdabacconstraint cosdabacconstraint,
			Cosdabaccontrolgroup cosdabaccontrolgroup, Cosdabactransaction cosdabactransaction, String createdby,
			Date createdon, String lastupdatedby, Date lastupdatedon) {
		this.controlobjectid = controlobjectid;
		this.cosdabacconstraint = cosdabacconstraint;
		this.cosdabaccontrolgroup = cosdabaccontrolgroup;
		this.cosdabactransaction = cosdabactransaction;
		this.createdby = createdby;
		this.createdon = createdon;
		this.lastupdatedby = lastupdatedby;
		this.lastupdatedon = lastupdatedon;
	}

	@Id
	@SequenceGenerator(name = "controlObjectSeq", sequenceName = "controlObjectSeq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="controlObjectSeq")
	@Column(name = "controlobjectid", unique = true, nullable = false, scale = 0)
	public BigDecimal getControlobjectid() {
		return this.controlobjectid;
	}

	public void setControlobjectid(BigDecimal controlobjectid) {
		this.controlobjectid = controlobjectid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "attributeconstraintid")
	public Cosdabacconstraint getCosdabacconstraint() {
		return this.cosdabacconstraint;
	}

	public void setCosdabacconstraint(Cosdabacconstraint cosdabacconstraint) {
		this.cosdabacconstraint = cosdabacconstraint;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "controlgroupid")
	public Cosdabaccontrolgroup getCosdabaccontrolgroup() {
		return this.cosdabaccontrolgroup;
	}

	public void setCosdabaccontrolgroup(Cosdabaccontrolgroup cosdabaccontrolgroup) {
		this.cosdabaccontrolgroup = cosdabaccontrolgroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "transactionid")
	public Cosdabactransaction getCosdabactransaction() {
		return this.cosdabactransaction;
	}

	public void setCosdabactransaction(Cosdabactransaction cosdabactransaction) {
		this.cosdabactransaction = cosdabactransaction;
	}

	@Column(name = "createdby", length = 64)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdon", length = 13)
	public Date getCreatedon() {
		return this.createdon;
	}

	public void setCreatedon(Date createdon) {
		this.createdon = createdon;
	}

	@Column(name = "lastupdatedby", length = 64)
	public String getLastupdatedby() {
		return this.lastupdatedby;
	}

	public void setLastupdatedby(String lastupdatedby) {
		this.lastupdatedby = lastupdatedby;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "lastupdatedon", length = 13)
	public Date getLastupdatedon() {
		return this.lastupdatedon;
	}

	public void setLastupdatedon(Date lastupdatedon) {
		this.lastupdatedon = lastupdatedon;
	}

}
