/* Licensed Materials - 
 Property of IBM 6949 - 67L 
 Copyright IBM Corp. 2017, 2018 All Rights Reserved */
package  com.ibm.gbs.auth.model;
// Generated Sep 21, 2017 1:52:20 PM by Hibernate Tools 5.1.0.Beta1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.ibm.gbs.util.Constant;

/**
 * Cosdconsentgrouptxn generated by hbm2java
 */
@Entity
@Table(name = "cosdconsentgrouptxn", schema = Constant.SCHEMANAME )
public class Cosdconsentgrouptxn implements java.io.Serializable {

	private BigDecimal consentgrouptxnid;
	private Cosdabactransaction cosdabactransaction;
	private Cosdconsentgroup cosdconsentgroup;
	private String createdby;
	private Date createdon;
	private String lastupdatedby;
	private Date lastupdatedon;

	public Cosdconsentgrouptxn() {
	}

	public Cosdconsentgrouptxn(BigDecimal consentgrouptxnid, Cosdabactransaction cosdabactransaction,
			Cosdconsentgroup cosdconsentgroup) {
		this.consentgrouptxnid = consentgrouptxnid;
		this.cosdabactransaction = cosdabactransaction;
		this.cosdconsentgroup = cosdconsentgroup;
	}

	public Cosdconsentgrouptxn(BigDecimal consentgrouptxnid, Cosdabactransaction cosdabactransaction,
			Cosdconsentgroup cosdconsentgroup, String createdby, Date createdon, String lastupdatedby,
			Date lastupdatedon) {
		this.consentgrouptxnid = consentgrouptxnid;
		this.cosdabactransaction = cosdabactransaction;
		this.cosdconsentgroup = cosdconsentgroup;
		this.createdby = createdby;
		this.createdon = createdon;
		this.lastupdatedby = lastupdatedby;
		this.lastupdatedon = lastupdatedon;
	}

	@Id
	@SequenceGenerator(name = "consentGrpTxnSeq", sequenceName = "consentGrpTxnSeq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="consentGrpTxnSeq")	
	@Column(name = "consentgrouptxnid", unique = true, nullable = false, scale = 0)
	public BigDecimal getConsentgrouptxnid() {
		return this.consentgrouptxnid;
	}

	public void setConsentgrouptxnid(BigDecimal consentgrouptxnid) {
		this.consentgrouptxnid = consentgrouptxnid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "transactionid", nullable = false)
	public Cosdabactransaction getCosdabactransaction() {
		return this.cosdabactransaction;
	}

	public void setCosdabactransaction(Cosdabactransaction cosdabactransaction) {
		this.cosdabactransaction = cosdabactransaction;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "consentgroupid", nullable = false)
	public Cosdconsentgroup getCosdconsentgroup() {
		return this.cosdconsentgroup;
	}

	public void setCosdconsentgroup(Cosdconsentgroup cosdconsentgroup) {
		this.cosdconsentgroup = cosdconsentgroup;
	}

	@Column(name = "createdby", length = 64)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdon", length = 13)
	public Date getCreatedon() {
		return this.createdon;
	}

	public void setCreatedon(Date createdon) {
		this.createdon = createdon;
	}

	@Column(name = "lastupdatedby", length = 64)
	public String getLastupdatedby() {
		return this.lastupdatedby;
	}

	public void setLastupdatedby(String lastupdatedby) {
		this.lastupdatedby = lastupdatedby;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "lastupdatedon", length = 13)
	public Date getLastupdatedon() {
		return this.lastupdatedon;
	}

	public void setLastupdatedon(Date lastupdatedon) {
		this.lastupdatedon = lastupdatedon;
	}

}
