/* Licensed Materials - 
 Property of IBM 6949 - 67L 
 Copyright IBM Corp. 2017, 2018 All Rights Reserved */
package  com.ibm.gbs.auth.model;
// Generated Sep 21, 2017 1:52:20 PM by Hibernate Tools 5.1.0.Beta1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.ibm.gbs.util.Constant;

/**
 * Cosdabacorganisation generated by hbm2java
 */
@Entity
@Table(name = "cosdabacorganisation", schema = Constant.SCHEMANAME)
public class Cosdabacorganisation implements java.io.Serializable {

	private BigDecimal organisationid;
	private BigDecimal organisationunitid;
	private BigDecimal parentorganisationunitid;
	private String createdby;
	private Date createdon;
	private String lastupdatedby;
	private Date lastupdatedon;

	public Cosdabacorganisation() {
	}

	public Cosdabacorganisation(BigDecimal organisationid) {
		this.organisationid = organisationid;
	}

	public Cosdabacorganisation(BigDecimal organisationid, BigDecimal organisationunitid,
			BigDecimal parentorganisationunitid, String createdby, Date createdon, String lastupdatedby,
			Date lastupdatedon) {
		this.organisationid = organisationid;
		this.organisationunitid = organisationunitid;
		this.parentorganisationunitid = parentorganisationunitid;
		this.createdby = createdby;
		this.createdon = createdon;
		this.lastupdatedby = lastupdatedby;
		this.lastupdatedon = lastupdatedon;
	}

	@Id

	@Column(name = "organisationid", unique = true, nullable = false, scale = 0)
	public BigDecimal getOrganisationid() {
		return this.organisationid;
	}

	public void setOrganisationid(BigDecimal organisationid) {
		this.organisationid = organisationid;
	}

	@Column(name = "organisationunitid", scale = 0)
	public BigDecimal getOrganisationunitid() {
		return this.organisationunitid;
	}

	public void setOrganisationunitid(BigDecimal organisationunitid) {
		this.organisationunitid = organisationunitid;
	}

	@Column(name = "parentorganisationunitid", scale = 0)
	public BigDecimal getParentorganisationunitid() {
		return this.parentorganisationunitid;
	}

	public void setParentorganisationunitid(BigDecimal parentorganisationunitid) {
		this.parentorganisationunitid = parentorganisationunitid;
	}

	@Column(name = "createdby", length = 64)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdon", length = 13)
	public Date getCreatedon() {
		return this.createdon;
	}

	public void setCreatedon(Date createdon) {
		this.createdon = createdon;
	}

	@Column(name = "lastupdatedby", length = 64)
	public String getLastupdatedby() {
		return this.lastupdatedby;
	}

	public void setLastupdatedby(String lastupdatedby) {
		this.lastupdatedby = lastupdatedby;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "lastupdatedon", length = 13)
	public Date getLastupdatedon() {
		return this.lastupdatedon;
	}

	public void setLastupdatedon(Date lastupdatedon) {
		this.lastupdatedon = lastupdatedon;
	}

}
