/* Licensed Materials - 
 Property of IBM 6949 - 67L 
 Copyright IBM Corp. 2017, 2018 All Rights Reserved */
package  com.ibm.gbs.auth.model;
// Generated Sep 21, 2017 1:52:20 PM by Hibernate Tools 5.1.0.Beta1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.ibm.gbs.util.Constant;

/**
 * Organisationunit generated by hbm2java
 */
@Entity
@Table(name = "organisationunit", schema = Constant.SCHEMANAME )
public class Organisationunit implements java.io.Serializable {

	private BigDecimal organisationunitid;
	private String businesstypecode;
	private String comments;
	private Date creationdate;
	private BigDecimal defaultprinterid;
	private String name;
	private String recordstatus;
	private String statuscode;
	private String webaddress;
	private String readsid;
	private String maintainsid;
	private String createunitsid;
	private BigDecimal locationid;
	private String uppername;
	private String createdby;
	private Date createdon;
	private String lastupdatedby;
	private Date lastupdatedon;
	private Date lastwritten;
	private Set<Cosdauthorizationgroup> cosdauthorizationgroups = new HashSet<Cosdauthorizationgroup>(0);

	public Organisationunit() {
	}

	public Organisationunit(BigDecimal organisationunitid) {
		this.organisationunitid = organisationunitid;
	}

	public Organisationunit(BigDecimal organisationunitid, String businesstypecode, String comments, Date creationdate,
			BigDecimal defaultprinterid, String name, String recordstatus, String statuscode, String webaddress,
			String readsid, String maintainsid, String createunitsid, BigDecimal locationid, String uppername,
			String createdby, Date createdon, String lastupdatedby, Date lastupdatedon, Date lastwritten,
			Set<Cosdauthorizationgroup> cosdauthorizationgroups) {
		this.organisationunitid = organisationunitid;
		this.businesstypecode = businesstypecode;
		this.comments = comments;
		this.creationdate = creationdate;
		this.defaultprinterid = defaultprinterid;
		this.name = name;
		this.recordstatus = recordstatus;
		this.statuscode = statuscode;
		this.webaddress = webaddress;
		this.readsid = readsid;
		this.maintainsid = maintainsid;
		this.createunitsid = createunitsid;
		this.locationid = locationid;
		this.uppername = uppername;
		this.createdby = createdby;
		this.createdon = createdon;
		this.lastupdatedby = lastupdatedby;
		this.lastupdatedon = lastupdatedon;
		this.lastwritten = lastwritten;
		this.cosdauthorizationgroups = cosdauthorizationgroups;
	}

	@Id
	@SequenceGenerator(name = "organisationunitSeq", sequenceName = "organisationunitSeq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="organisationunitSeq")
	@Column(name = "organisationunitid", unique = true, nullable = false, scale = 0)
	public BigDecimal getOrganisationunitid() {
		return this.organisationunitid;
	}

	public void setOrganisationunitid(BigDecimal organisationunitid) {
		this.organisationunitid = organisationunitid;
	}

	@Column(name = "businesstypecode", length = 10)
	public String getBusinesstypecode() {
		return this.businesstypecode;
	}

	public void setBusinesstypecode(String businesstypecode) {
		this.businesstypecode = businesstypecode;
	}

	@Column(name = "comments", length = 300)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "creationdate", length = 13)
	public Date getCreationdate() {
		return this.creationdate;
	}

	public void setCreationdate(Date creationdate) {
		this.creationdate = creationdate;
	}

	@Column(name = "defaultprinterid", scale = 0)
	public BigDecimal getDefaultprinterid() {
		return this.defaultprinterid;
	}

	public void setDefaultprinterid(BigDecimal defaultprinterid) {
		this.defaultprinterid = defaultprinterid;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "recordstatus", length = 10)
	public String getRecordstatus() {
		return this.recordstatus;
	}

	public void setRecordstatus(String recordstatus) {
		this.recordstatus = recordstatus;
	}

	@Column(name = "statuscode", length = 10)
	public String getStatuscode() {
		return this.statuscode;
	}

	public void setStatuscode(String statuscode) {
		this.statuscode = statuscode;
	}

	@Column(name = "webaddress", length = 50)
	public String getWebaddress() {
		return this.webaddress;
	}

	public void setWebaddress(String webaddress) {
		this.webaddress = webaddress;
	}

	@Column(name = "readsid", length = 100)
	public String getReadsid() {
		return this.readsid;
	}

	public void setReadsid(String readsid) {
		this.readsid = readsid;
	}

	@Column(name = "maintainsid", length = 100)
	public String getMaintainsid() {
		return this.maintainsid;
	}

	public void setMaintainsid(String maintainsid) {
		this.maintainsid = maintainsid;
	}

	@Column(name = "createunitsid", length = 100)
	public String getCreateunitsid() {
		return this.createunitsid;
	}

	public void setCreateunitsid(String createunitsid) {
		this.createunitsid = createunitsid;
	}

	@Column(name = "locationid", scale = 0)
	public BigDecimal getLocationid() {
		return this.locationid;
	}

	public void setLocationid(BigDecimal locationid) {
		this.locationid = locationid;
	}

	@Column(name = "uppername", length = 100)
	public String getUppername() {
		return this.uppername;
	}

	public void setUppername(String uppername) {
		this.uppername = uppername;
	}

	@Column(name = "createdby", length = 64)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdon", length = 13)
	public Date getCreatedon() {
		return this.createdon;
	}

	public void setCreatedon(Date createdon) {
		this.createdon = createdon;
	}

	@Column(name = "lastupdatedby", length = 64)
	public String getLastupdatedby() {
		return this.lastupdatedby;
	}

	public void setLastupdatedby(String lastupdatedby) {
		this.lastupdatedby = lastupdatedby;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "lastupdatedon", length = 13)
	public Date getLastupdatedon() {
		return this.lastupdatedon;
	}

	public void setLastupdatedon(Date lastupdatedon) {
		this.lastupdatedon = lastupdatedon;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "lastwritten", length = 13)
	public Date getLastwritten() {
		return this.lastwritten;
	}

	public void setLastwritten(Date lastwritten) {
		this.lastwritten = lastwritten;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organisationunit")
	public Set<Cosdauthorizationgroup> getCosdauthorizationgroups() {
		return this.cosdauthorizationgroups;
	}

	public void setCosdauthorizationgroups(Set<Cosdauthorizationgroup> cosdauthorizationgroups) {
		this.cosdauthorizationgroups = cosdauthorizationgroups;
	}

}
