
/* Licensed Materials - 
 Property of IBM 6949 - 67L 
 Copyright IBM Corp. 2017, 2018 All Rights Reserved */
package  com.ibm.gbs.auth.model;
// Generated Sep 21, 2017 1:52:20 PM by Hibernate Tools 5.1.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.ibm.gbs.util.Constant;
/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", schema = Constant.SCHEMANAME )
public class Users implements java.io.Serializable {

	private String username;
	private String password;
	private String rolename;
	private String firstname;
	private String lastname;
	private String email;
	private Set<Cosdauthorizationgroup> cosdauthorizationgroups = new HashSet<Cosdauthorizationgroup>(0);

	public Users() {
	}

	public Users(String username) {
		this.username = username;
	}

	public Users(String username, String password, String rolename, String firstname, String lastname, String email,
			Set<Cosdauthorizationgroup> cosdauthorizationgroups) {
		this.username = username;
		this.password = password;
		this.rolename = rolename;
		this.firstname = firstname;
		this.lastname = lastname;
		this.email = email;
		this.cosdauthorizationgroups = cosdauthorizationgroups;
	}

	@Id
	@Column(name = "username", unique = true, nullable = false, length = 64)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", length = 60)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "rolename", length = 50)
	public String getRolename() {
		return this.rolename;
	}

	public void setRolename(String rolename) {
		this.rolename = rolename;
	}

	@Column(name = "firstname", length = 50)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", length = 50)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Cosdauthorizationgroup> getCosdauthorizationgroups() {
		return this.cosdauthorizationgroups;
	}

	public void setCosdauthorizationgroups(Set<Cosdauthorizationgroup> cosdauthorizationgroups) {
		this.cosdauthorizationgroups = cosdauthorizationgroups;
	}

}
