/* Licensed Materials - 
 Property of IBM 6949 - 67L 
 Copyright IBM Corp. 2017, 2018 All Rights Reserved */
package  com.ibm.gbs.vo;
// Generated Sep 21, 2017 1:52:20 PM by Hibernate Tools 5.1.0.Beta1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cosdauthorizationgroup generated by hbm2java
 */

public class CosdauthorizationgroupVO   {

	private String authGroupName;
	
	public String getAuthGroupName() {
		return authGroupName;
	}

	public void setAuthGroupName(String authGroupName) {
		this.authGroupName = authGroupName;
	}
	
	public BigDecimal getAuthorizationgroupid() {
		return authorizationgroupid;
	}

	public void setAuthorizationgroupid(BigDecimal authorizationgroupid) {
		this.authorizationgroupid = authorizationgroupid;
	}

	public long getCosdabaccontrolgroup() {
		return cosdabaccontrolgroup;
	}

	public void setCosdabaccontrolgroup(long cosdabaccontrolgroup) {
		this.cosdabaccontrolgroup = cosdabaccontrolgroup;
	}

	public long getOrganisationunit() {
		return organisationunit;
	}

	public void setOrganisationunit(long organisationunit) {
		this.organisationunit = organisationunit;
	}

	public String getSecurityrole() {
		return securityrole;
	}

	public void setSecurityrole(String securityrole) {
		this.securityrole = securityrole;
	}

	public String getUsers() {
		return users;
	}

	public void setUsers(String users) {
		this.users = users;
	}

	public BigDecimal getJobid() {
		return jobid;
	}

	public void setJobid(BigDecimal jobid) {
		this.jobid = jobid;
	}

	public String getCreatedby() {
		return createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	public Date getCreatedon() {
		return createdon;
	}

	public void setCreatedon(Date createdon) {
		this.createdon = createdon;
	}

	public String getLastupdatedby() {
		return lastupdatedby;
	}

	public void setLastupdatedby(String lastupdatedby) {
		this.lastupdatedby = lastupdatedby;
	}

	public Date getLastupdatedon() {
		return lastupdatedon;
	}

	public void setLastupdatedon(Date lastupdatedon) {
		this.lastupdatedon = lastupdatedon;
	}
    
	private BigDecimal authorizationgroupid;
	private long cosdabaccontrolgroup;
	private long organisationunit;
	private String securityrole;
	private String users;
	private BigDecimal jobid;
	private String createdby;
	private Date createdon;
	private String lastupdatedby;
	private Date lastupdatedon;

	private String controlgroupname ;
	public String getControlgroupname() {
		return controlgroupname;
	}

	public void setControlgroupname(String controlgroupname) {
		this.controlgroupname = controlgroupname;
	}

	public String getOrganisationname() {
		return organisationname;
	}

	public void setOrganisationname(String organisationname) {
		this.organisationname = organisationname;
	}

	public String getJob() {
		return job;
	}

	public void setJob(String job) {
		this.job = job;
	}

	private String organisationname ;
	private String job ;
	
	public CosdauthorizationgroupVO() {
	}

	public String getJobuserName() {
		return jobuserName;
	}

	public void setJobuserName(String jobuserName) {
		this.jobuserName = jobuserName;
	}

	private String jobuserName ;

}
