/* Licensed Materials - 
 Property of IBM 6949 - 67L 
 Copyright IBM Corp. 2017, 2018 All Rights Reserved */
package  com.ibm.gbs.consentmgmt.dto;
// Generated Sep 21, 2017 1:52:20 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.ibm.gbs.util.Constant;
/**
 * C360SavedResults generated by hbm2java
 */
@Entity
@Table(name = "c360_saved_results", schema = Constant.SCHEMANAME , uniqueConstraints = @UniqueConstraint(columnNames = "id"))
public class C360SavedResults implements java.io.Serializable {

	private C360SavedResultsId id;

	public C360SavedResults() {
	}

	public C360SavedResults(C360SavedResultsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "id", unique = true, nullable = false)),
			@AttributeOverride(name = "referralnum", column = @Column(name = "referralnum", nullable = false, length = 19)),
			@AttributeOverride(name = "username", column = @Column(name = "username", nullable = false, length = 12)),
			@AttributeOverride(name = "inactiveflag", column = @Column(name = "inactiveflag", length = 250)),
			@AttributeOverride(name = "saveddate", column = @Column(name = "saveddate", length = 13)),
			@AttributeOverride(name = "personfname", column = @Column(name = "personfname", length = 25)),
			@AttributeOverride(name = "personlname", column = @Column(name = "personlname", length = 25)),
			@AttributeOverride(name = "personaddress", column = @Column(name = "personaddress", length = 250)),
			@AttributeOverride(name = "sourcesys", column = @Column(name = "sourcesys", length = 12)),
			@AttributeOverride(name = "sourcesyspersonid", column = @Column(name = "sourcesyspersonid", length = 12)),
			@AttributeOverride(name = "usercomments", column = @Column(name = "usercomments", length = 10485760)) })
	public C360SavedResultsId getId() {
		return this.id;
	}

	public void setId(C360SavedResultsId id) {
		this.id = id;
	}

}
