/* Licensed Materials - 
 Property of IBM 6949 - 67L 
 Copyright IBM Corp. 2017, 2018 All Rights Reserved */
package  com.ibm.gbs.consentmgmt.dto;
// Generated Sep 21, 2017 1:52:20 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.ibm.gbs.util.Constant;

/**
 * Clientdetails generated by hbm2java
 */
@Entity
@Table(name = "clientdetails", schema = Constant.SCHEMANAME )
public class Clientdetails implements java.io.Serializable {

	private String appid;
	private String resourceids;
	private String appsecret;
	private String scope;
	private String granttypes;
	private String redirecturl;
	private String authorities;
	private Integer accessTokenValidity;
	private Integer refreshTokenValidity;
	private String additionalinformation;
	private String autoapprovescopes;

	public Clientdetails() {
	}

	public Clientdetails(String appid) {
		this.appid = appid;
	}

	public Clientdetails(String appid, String resourceids, String appsecret, String scope, String granttypes,
			String redirecturl, String authorities, Integer accessTokenValidity, Integer refreshTokenValidity,
			String additionalinformation, String autoapprovescopes) {
		this.appid = appid;
		this.resourceids = resourceids;
		this.appsecret = appsecret;
		this.scope = scope;
		this.granttypes = granttypes;
		this.redirecturl = redirecturl;
		this.authorities = authorities;
		this.accessTokenValidity = accessTokenValidity;
		this.refreshTokenValidity = refreshTokenValidity;
		this.additionalinformation = additionalinformation;
		this.autoapprovescopes = autoapprovescopes;
	}

	@Id
	@Column(name = "appid", unique = true, nullable = false, length = 256)
	public String getAppid() {
		return this.appid;
	}

	public void setAppid(String appid) {
		this.appid = appid;
	}

	@Column(name = "resourceids", length = 256)
	public String getResourceids() {
		return this.resourceids;
	}

	public void setResourceids(String resourceids) {
		this.resourceids = resourceids;
	}

	@Column(name = "appsecret", length = 256)
	public String getAppsecret() {
		return this.appsecret;
	}

	public void setAppsecret(String appsecret) {
		this.appsecret = appsecret;
	}

	@Column(name = "scope", length = 256)
	public String getScope() {
		return this.scope;
	}

	public void setScope(String scope) {
		this.scope = scope;
	}

	@Column(name = "granttypes", length = 256)
	public String getGranttypes() {
		return this.granttypes;
	}

	public void setGranttypes(String granttypes) {
		this.granttypes = granttypes;
	}

	@Column(name = "redirecturl", length = 256)
	public String getRedirecturl() {
		return this.redirecturl;
	}

	public void setRedirecturl(String redirecturl) {
		this.redirecturl = redirecturl;
	}

	@Column(name = "authorities", length = 256)
	public String getAuthorities() {
		return this.authorities;
	}

	public void setAuthorities(String authorities) {
		this.authorities = authorities;
	}

	@Column(name = "access_token_validity")
	public Integer getAccessTokenValidity() {
		return this.accessTokenValidity;
	}

	public void setAccessTokenValidity(Integer accessTokenValidity) {
		this.accessTokenValidity = accessTokenValidity;
	}

	@Column(name = "refresh_token_validity")
	public Integer getRefreshTokenValidity() {
		return this.refreshTokenValidity;
	}

	public void setRefreshTokenValidity(Integer refreshTokenValidity) {
		this.refreshTokenValidity = refreshTokenValidity;
	}

	@Column(name = "additionalinformation", length = 4096)
	public String getAdditionalinformation() {
		return this.additionalinformation;
	}

	public void setAdditionalinformation(String additionalinformation) {
		this.additionalinformation = additionalinformation;
	}

	@Column(name = "autoapprovescopes", length = 256)
	public String getAutoapprovescopes() {
		return this.autoapprovescopes;
	}

	public void setAutoapprovescopes(String autoapprovescopes) {
		this.autoapprovescopes = autoapprovescopes;
	}

}
