/* Licensed Materials - 
 Property of IBM 6949 - 67L 
 Copyright IBM Corp. 2017, 2018 All Rights Reserved */
package  com.ibm.gbs.consentmgmt.dto;
// Generated Sep 21, 2017 1:52:20 PM by Hibernate Tools 5.1.0.Beta1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.ibm.gbs.util.Constant;
/**
 * Cosdabactransaction generated by hbm2java
 */
@Entity
@Table(name = "cosdabactransaction", schema = Constant.SCHEMANAME )
public class Cosdabactransaction implements java.io.Serializable {

	private BigDecimal transactionid;
	private String transactiontype;
	private String transactionname;
	private String defaultaccess;
	private String createdby;
	private Date createdon;
	private String lastupdatedby;
	private Date lastupdatedon;
	private byte versionno;
	private Set<Cosdconsentgrouptxn> cosdconsentgrouptxns = new HashSet<Cosdconsentgrouptxn>(0);
	private Set<Cosdabaccontrolobject> cosdabaccontrolobjects = new HashSet<Cosdabaccontrolobject>(0);

	public Cosdabactransaction() {
	}

	public Cosdabactransaction(BigDecimal transactionid, String transactiontype, String transactionname,
			String defaultaccess, byte versionno) {
		this.transactionid = transactionid;
		this.transactiontype = transactiontype;
		this.transactionname = transactionname;
		this.defaultaccess = defaultaccess;
		this.versionno = versionno;
	}

	public Cosdabactransaction(BigDecimal transactionid, String transactiontype, String transactionname,
			String defaultaccess, String createdby, Date createdon, String lastupdatedby, Date lastupdatedon,
			byte versionno, Set<Cosdconsentgrouptxn> cosdconsentgrouptxns,
			Set<Cosdabaccontrolobject> cosdabaccontrolobjects) {
		this.transactionid = transactionid;
		this.transactiontype = transactiontype;
		this.transactionname = transactionname;
		this.defaultaccess = defaultaccess;
		this.createdby = createdby;
		this.createdon = createdon;
		this.lastupdatedby = lastupdatedby;
		this.lastupdatedon = lastupdatedon;
		this.versionno = versionno;
		/*this.cosdconsentgrouptxns = cosdconsentgrouptxns;
		this.cosdabaccontrolobjects = cosdabaccontrolobjects;*/
	}

	@Id	 
	@SequenceGenerator(schema = Constant.SCHEMANAME ,name  = "transactionSeq", sequenceName = "transactionSeq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="transactionSeq")
	@Column(name = "transactionid", unique = true, nullable = false, scale = 0)
	public BigDecimal getTransactionid() {
		return this.transactionid;
	}

	public void setTransactionid(BigDecimal transactionid) {
		this.transactionid = transactionid;
	}

	@Column(name = "transactiontype", nullable = false, length = 10)
	public String getTransactiontype() {
		return this.transactiontype;
	}

	public void setTransactiontype(String transactiontype) {
		this.transactiontype = transactiontype;
	}

	@Column(name = "transactionname", nullable = false, length = 100)
	public String getTransactionname() {
		return this.transactionname;
	}

	public void setTransactionname(String transactionname) {
		this.transactionname = transactionname;
	}

	@Column(name = "defaultaccess", nullable = false, length = 10)
	public String getDefaultaccess() {
		return this.defaultaccess;
	}

	public void setDefaultaccess(String defaultaccess) {
		this.defaultaccess = defaultaccess;
	}

	@Column(name = "createdby", length = 64)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdon", length = 13)
	public Date getCreatedon() {
		return this.createdon;
	}

	public void setCreatedon(Date createdon) {
		this.createdon = createdon;
	}

	@Column(name = "lastupdatedby", length = 64)
	public String getLastupdatedby() {
		return this.lastupdatedby;
	}

	public void setLastupdatedby(String lastupdatedby) {
		this.lastupdatedby = lastupdatedby;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "lastupdatedon", length = 13)
	public Date getLastupdatedon() {
		return this.lastupdatedon;
	}

	public void setLastupdatedon(Date lastupdatedon) {
		this.lastupdatedon = lastupdatedon;
	}

	@Column(name = "versionno", nullable = false, precision = 2, scale = 0)
	public byte getVersionno() {
		return this.versionno;
	}

	public void setVersionno(byte versionno) {
		this.versionno = versionno;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cosdabactransaction")
	public Set<Cosdconsentgrouptxn> getCosdconsentgrouptxns() {
		return this.cosdconsentgrouptxns;
	}

	public void setCosdconsentgrouptxns(Set<Cosdconsentgrouptxn> cosdconsentgrouptxns) {
		this.cosdconsentgrouptxns = cosdconsentgrouptxns;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cosdabactransaction")
	public Set<Cosdabaccontrolobject> getCosdabaccontrolobjects() {
		return this.cosdabaccontrolobjects;
	}

	public void setCosdabaccontrolobjects(Set<Cosdabaccontrolobject> cosdabaccontrolobjects) {
		this.cosdabaccontrolobjects = cosdabaccontrolobjects;
	}

}
