/* Licensed Materials - 
 Property of IBM 6949 - 67L 
 Copyright IBM Corp. 2017, 2018 All Rights Reserved */
package  com.ibm.gbs.consentmgmt.dto;
// Generated Sep 21, 2017 1:52:20 PM by Hibernate Tools 5.1.0.Beta1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.ibm.gbs.util.Constant;

/**
 * Cosdpersonconsent generated by hbm2java
 */
@Entity
@Table(name = "cosdpersonconsent", schema = Constant.SCHEMANAME )
public class Cosdpersonconsent implements java.io.Serializable {

	private BigDecimal personconsentid;
	private BigDecimal fileid;
	private BigDecimal clientid;

	

	private BigDecimal concernroleid;
	private Date startdate;
	private Date enddate;
	private String thirdpartyrelationship;
	private String thirdpartyfirstname;
	private String thirdpartylastname;
	private String thirdpartyotherrelationship;
	private String identificationno;
	private String identificationtype;
	private String identificationother;
	private BigDecimal contactaddressid;
	private String contactphone;
	private String authpersonnameone;
	private String authpersonrelone;
	private String authpersoncontactinfoone;
	private String authpersonnametwo;
	private String authpersonreltwo;
	private String authpersoncontactinfotwo;
	private String createdby;
	private Date createdon;
	private String lastupdatedby;
	private Date lastupdatedon;
	
	private String consentCatGrp;
	private String histroyRecord;
	
	
	@Column(name = "ClientId", nullable = false, scale = 0)
	public BigDecimal getClientid() {
		return clientid;
	}

	public void setClientid(BigDecimal clientid) {
		this.clientid = clientid;
	}
	
	@Column(name = "HistoryRecord", length = 20)
	public String getHistroyRecord() {
		return histroyRecord;
	}

	public void setHistroyRecord(String histroyRecord) {
		this.histroyRecord = histroyRecord;
	}

	private String customerName;
	
	@Column(name = "CONSENT_CATGRP", length = 50)
	public String getConsentCatGrp() {
		return consentCatGrp;
	}

	public void setConsentCatGrp(String consentUser) {
		this.consentCatGrp = consentUser;
	}
	
	@Column(name = "customer_name", length = 50)
	public String getCustomerName() {
		return customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}
	
	@Column(name = "Street", length = 30)
	public String getStreet() {
		return Street;
	}

	public void setStreet(String street) {
		Street = street;
	}
    
	@Column(name = "City", length = 30)
	public String getCity() {
		return City;
	}

	public void setCity(String city) {
		City = city;
	}
	
	@Column(name = "AppSuite", length = 30)
	public String getAppSuite() {
		return AppSuite;
	}

	public void setAppSuite(String appSuite) {
		AppSuite = appSuite;
	}

	@Column(name = "State", length = 30)
	public String getState() {
		return State;
	}

	public void setState(String state) {
		State = state;
	}

	@Column(name = "zipCode", length = 30)
	public String getZipCode() {
		return zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}
	
	private String Street ;
	private String City ;
	private String AppSuite ;
	private String  State ;
	private String zipCode ;
	
	private Set<Cosdconsentexception> cosdconsentexceptions = new HashSet<Cosdconsentexception>(0);
	private Set<Cosdproxypersonconsent> cosdproxypersonconsents = new HashSet<Cosdproxypersonconsent>(0);
	private Set<Cosdpersonconsenthistory> cosdpersonconsenthistories = new HashSet<Cosdpersonconsenthistory>(0);

	public Cosdpersonconsent() {
	}

	public Cosdpersonconsent(BigDecimal personconsentid, BigDecimal concernroleid) {
		this.personconsentid = personconsentid;
		this.concernroleid = concernroleid;
	}

	public Cosdpersonconsent(BigDecimal personconsentid, BigDecimal concernroleid, Date startdate, Date enddate,
			String thirdpartyrelationship, String thirdpartyfirstname, String thirdpartylastname,
			String thirdpartyotherrelationship, String identificationno, String identificationtype,
			String identificationother, BigDecimal contactaddressid, String contactphone, String authpersonnameone,
			String authpersonrelone, String authpersoncontactinfoone, String authpersonnametwo, String authpersonreltwo,
			String authpersoncontactinfotwo, String createdby, Date createdon, String lastupdatedby, Date lastupdatedon,
			Set<Cosdconsentexception> cosdconsentexceptions, Set<Cosdproxypersonconsent> cosdproxypersonconsents,
			Set<Cosdpersonconsenthistory> cosdpersonconsenthistories) {
		this.personconsentid = personconsentid;
		this.concernroleid = concernroleid;
		this.startdate = startdate;
		this.enddate = enddate;
		this.thirdpartyrelationship = thirdpartyrelationship;
		this.thirdpartyfirstname = thirdpartyfirstname;
		this.thirdpartylastname = thirdpartylastname;
		this.thirdpartyotherrelationship = thirdpartyotherrelationship;
		this.identificationno = identificationno;
		this.identificationtype = identificationtype;
		this.identificationother = identificationother;
		this.contactaddressid = contactaddressid;
		this.contactphone = contactphone;
		this.authpersonnameone = authpersonnameone;
		this.authpersonrelone = authpersonrelone;
		this.authpersoncontactinfoone = authpersoncontactinfoone;
		this.authpersonnametwo = authpersonnametwo;
		this.authpersonreltwo = authpersonreltwo;
		this.authpersoncontactinfotwo = authpersoncontactinfotwo;
		this.createdby = createdby;
		this.createdon = createdon;
		this.lastupdatedby = lastupdatedby;
		this.lastupdatedon = lastupdatedon;
		this.cosdconsentexceptions = cosdconsentexceptions;
		this.cosdproxypersonconsents = cosdproxypersonconsents;
		this.cosdpersonconsenthistories = cosdpersonconsenthistories;
	}

	@Id
	@SequenceGenerator(schema = Constant.SCHEMANAME ,name  = "consentPerson", sequenceName = "consentPerson", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="consentPerson")		
	@Column(name = "personconsentid", unique = true, nullable = false, scale = 0)
	public BigDecimal getPersonconsentid() {
		return this.personconsentid;
	}

	public void setPersonconsentid(BigDecimal personconsentid) {
		this.personconsentid = personconsentid;
	}

	@Column(name = "concernroleid", scale = 0)
	public BigDecimal getConcernroleid() {
		return this.concernroleid;
	}

	public void setConcernroleid(BigDecimal concernroleid) {
		this.concernroleid = concernroleid;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "startdate", length = 13)
	public Date getStartdate() {
		return this.startdate;
	}

	public void setStartdate(Date startdate) {
		this.startdate = startdate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "enddate", length = 13)
	public Date getEnddate() {
		return this.enddate;
	}

	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}

	@Column(name = "thirdpartyrelationship", length = 100)
	public String getThirdpartyrelationship() {
		return this.thirdpartyrelationship;
	}

	public void setThirdpartyrelationship(String thirdpartyrelationship) {
		this.thirdpartyrelationship = thirdpartyrelationship;
	}

	@Column(name = "thirdpartyfirstname", length = 131)
	public String getThirdpartyfirstname() {
		return this.thirdpartyfirstname;
	}

	public void setThirdpartyfirstname(String thirdpartyfirstname) {
		this.thirdpartyfirstname = thirdpartyfirstname;
	}

	@Column(name = "thirdpartylastname", length = 131)
	public String getThirdpartylastname() {
		return this.thirdpartylastname;
	}

	public void setThirdpartylastname(String thirdpartylastname) {
		this.thirdpartylastname = thirdpartylastname;
	}

	@Column(name = "thirdpartyotherrelationship", length = 300)
	public String getThirdpartyotherrelationship() {
		return this.thirdpartyotherrelationship;
	}

	public void setThirdpartyotherrelationship(String thirdpartyotherrelationship) {
		this.thirdpartyotherrelationship = thirdpartyotherrelationship;
	}

	@Column(name = "identificationno", length = 40)
	public String getIdentificationno() {
		return this.identificationno;
	}

	public void setIdentificationno(String identificationno) {
		this.identificationno = identificationno;
	}

	@Column(name = "identificationtype", length = 10)
	public String getIdentificationtype() {
		return this.identificationtype;
	}

	public void setIdentificationtype(String identificationtype) {
		this.identificationtype = identificationtype;
	}

	@Column(name = "identificationother", length = 40)
	public String getIdentificationother() {
		return this.identificationother;
	}

	public void setIdentificationother(String identificationother) {
		this.identificationother = identificationother;
	}

	@Column(name = "contactaddressid", scale = 0)
	public BigDecimal getContactaddressid() {
		return this.contactaddressid;
	}

	public void setContactaddressid(BigDecimal contactaddressid) {
		this.contactaddressid = contactaddressid;
	}

	@Column(name = "contactphone", length = 40)
	public String getContactphone() {
		return this.contactphone;
	}

	public void setContactphone(String contactphone) {
		this.contactphone = contactphone;
	}

	@Column(name = "authpersonnameone", length = 142)
	public String getAuthpersonnameone() {
		return this.authpersonnameone;
	}

	public void setAuthpersonnameone(String authpersonnameone) {
		this.authpersonnameone = authpersonnameone;
	}

	@Column(name = "authpersonrelone", length = 50)
	public String getAuthpersonrelone() {
		return this.authpersonrelone;
	}

	public void setAuthpersonrelone(String authpersonrelone) {
		this.authpersonrelone = authpersonrelone;
	}

	@Column(name = "authpersoncontactinfoone", length = 100)
	public String getAuthpersoncontactinfoone() {
		return this.authpersoncontactinfoone;
	}

	public void setAuthpersoncontactinfoone(String authpersoncontactinfoone) {
		this.authpersoncontactinfoone = authpersoncontactinfoone;
	}

	@Column(name = "authpersonnametwo", length = 142)
	public String getAuthpersonnametwo() {
		return this.authpersonnametwo;
	}

	public void setAuthpersonnametwo(String authpersonnametwo) {
		this.authpersonnametwo = authpersonnametwo;
	}

	@Column(name = "authpersonreltwo", length = 50)
	public String getAuthpersonreltwo() {
		return this.authpersonreltwo;
	}

	public void setAuthpersonreltwo(String authpersonreltwo) {
		this.authpersonreltwo = authpersonreltwo;
	}

	@Column(name = "authpersoncontactinfotwo", length = 100)
	public String getAuthpersoncontactinfotwo() {
		return this.authpersoncontactinfotwo;
	}

	public void setAuthpersoncontactinfotwo(String authpersoncontactinfotwo) {
		this.authpersoncontactinfotwo = authpersoncontactinfotwo;
	}

	@Column(name = "createdby", length = 64)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdon", length = 13)
	public Date getCreatedon() {
		return this.createdon;
	}

	public void setCreatedon(Date createdon) {
		this.createdon = createdon;
	}

	@Column(name = "lastupdatedby", length = 64)
	public String getLastupdatedby() {
		return this.lastupdatedby;
	}

	public void setLastupdatedby(String lastupdatedby) {
		this.lastupdatedby = lastupdatedby;
	}
	
	@Column(name = "fileid", nullable = false, scale = 0)
	public BigDecimal getFileid() {
		return fileid;
	}

	public void setFileid(BigDecimal fileid) {
		this.fileid = fileid;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "lastupdatedon", length = 13)
	public Date getLastupdatedon() {
		return this.lastupdatedon;
	}

	public void setLastupdatedon(Date lastupdatedon) {
		this.lastupdatedon = lastupdatedon;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cosdpersonconsent")
	public Set<Cosdconsentexception> getCosdconsentexceptions() {
		return this.cosdconsentexceptions;
	}

	public void setCosdconsentexceptions(Set<Cosdconsentexception> cosdconsentexceptions) {
		this.cosdconsentexceptions = cosdconsentexceptions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cosdpersonconsent")
	public Set<Cosdproxypersonconsent> getCosdproxypersonconsents() {
		return this.cosdproxypersonconsents;
	}

	public void setCosdproxypersonconsents(Set<Cosdproxypersonconsent> cosdproxypersonconsents) {
		this.cosdproxypersonconsents = cosdproxypersonconsents;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cosdpersonconsent")
	public Set<Cosdpersonconsenthistory> getCosdpersonconsenthistories() {
		return this.cosdpersonconsenthistories;
	}

	public void setCosdpersonconsenthistories(Set<Cosdpersonconsenthistory> cosdpersonconsenthistories) {
		this.cosdpersonconsenthistories = cosdpersonconsenthistories;
	}

}
