/* Licensed Materials - 
 Property of IBM 6949 - 67L 
 Copyright IBM Corp. 2017, 2018 All Rights Reserved */
package  com.ibm.gbs.consentmgmt.dto;
// Generated Sep 21, 2017 1:52:20 PM by Hibernate Tools 5.1.0.Beta1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.ibm.gbs.util.Constant;

/**
 * Cosdpersonconsenthistory generated by hbm2java
 */
@Entity
@Table(name = "cosdpersonconsenthistory", schema = Constant.SCHEMANAME )
public class Cosdpersonconsenthistory implements java.io.Serializable {

	private BigDecimal consenthistoryid;
	private Cosdpersonconsent cosdpersonconsent;
	private String actiontype;
	private String cancelreason;
	private String createdby;
	private Date createdon;
	private String lastupdatedby;
	private Date lastupdatedon;

	public Cosdpersonconsenthistory() {
	}

	public Cosdpersonconsenthistory(BigDecimal consenthistoryid) {
		this.consenthistoryid = consenthistoryid;
	}

	public Cosdpersonconsenthistory(BigDecimal consenthistoryid, Cosdpersonconsent cosdpersonconsent, String actiontype,
			String cancelreason, String createdby, Date createdon, String lastupdatedby, Date lastupdatedon) {
		this.consenthistoryid = consenthistoryid;
		this.cosdpersonconsent = cosdpersonconsent;
		this.actiontype = actiontype;
		this.cancelreason = cancelreason;
		this.createdby = createdby;
		this.createdon = createdon;
		this.lastupdatedby = lastupdatedby;
		this.lastupdatedon = lastupdatedon;
	}

	@Id
	@SequenceGenerator(schema = Constant.SCHEMANAME ,name  = "consentPersonH", sequenceName = "consentPersonH", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="consentPersonH")		
	@Column(name = "consenthistoryid", unique = true, nullable = false, scale = 0)
	public BigDecimal getConsenthistoryid() {
		return this.consenthistoryid;
	}

	public void setConsenthistoryid(BigDecimal consenthistoryid) {
		this.consenthistoryid = consenthistoryid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "personconsentid")
	public Cosdpersonconsent getCosdpersonconsent() {
		return this.cosdpersonconsent;
	}

	public void setCosdpersonconsent(Cosdpersonconsent cosdpersonconsent) {
		this.cosdpersonconsent = cosdpersonconsent;
	}

	@Column(name = "actiontype", length = 10)
	public String getActiontype() {
		return this.actiontype;
	}

	public void setActiontype(String actiontype) {
		this.actiontype = actiontype;
	}

	@Column(name = "cancelreason", length = 300)
	public String getCancelreason() {
		return this.cancelreason;
	}

	public void setCancelreason(String cancelreason) {
		this.cancelreason = cancelreason;
	}

	@Column(name = "createdby", length = 64)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdon", length = 13)
	public Date getCreatedon() {
		return this.createdon;
	}

	public void setCreatedon(Date createdon) {
		this.createdon = createdon;
	}

	@Column(name = "lastupdatedby", length = 64)
	public String getLastupdatedby() {
		return this.lastupdatedby;
	}

	public void setLastupdatedby(String lastupdatedby) {
		this.lastupdatedby = lastupdatedby;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "lastupdatedon", length = 13)
	public Date getLastupdatedon() {
		return this.lastupdatedon;
	}

	public void setLastupdatedon(Date lastupdatedon) {
		this.lastupdatedon = lastupdatedon;
	}

}
